### DISCUSSION TITLE
Custom pseudo-class :--dialog for styling views inside Dialogs

### DISCUSSION THREAD

**Discussion by CatchABus** [NativeScript/NativeScript#10524] [Ideas]
Given the PR I'm currently working on https://github.com/NativeScript/NativeScript/pull/10514, I had the inspiration of including a way to style views that specifically reside inside dialogs.
That's currently a big problem since there's no easy way to style them.

I was thinking we could use Google Chrome's custom pseudo-classes for such scenarios: https://css-tricks.com/custom-state-pseudo-classes-in-chrome/#aa-custom-states
Custom ones differ in the fact that they start with `--`.

Example:
```css
Button:--dialog {
    color: black;
}
```

or another alternative implementation
```css
:--dialog {
    color: black;
}
```

**Comment by rigor789** [comment]
I like the idea of moving towards web-standards in general. Even for other custom css properties, I'd prefer we slowly moved towards spec-compliance, for example:
```css
.example {
  placeholder-color: red;
}
```
would become
```css
.example {
  --placeholder-color: red;
}
```

to stay spec-compliant.
