### DISCUSSION TITLE
Error trying to build in Xcode

### DISCUSSION THREAD

**Discussion by fernando-porto** [NativeScript/NativeScript#10561] [Q&A] [answered]
### Issue Description

The app is running normally, but when a i try to build in Xcode, throws an error.

I read in the documentation that it is to be installed specifically Ruby 2.7, but it is no longer possible to install this version on Mac Sonoma.

### Reproduction

When i build in Xcode, throws this error:
![image](https://github.com/NativeScript/NativeScript/assets/173197581/fb8ae9c4-2d20-430b-abe2-0ed1e98d426a)

### Environment

```yaml
OS: macOS 14.0
CPU: (4) x64 Intel(R) Core(TM) i9-14900K
Shell: /bin/zsh
node: 22.3.0
npm: 10.8.1
nativescript: 8.7.2

# android
java: Not Found
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 15.4/15F31d
cocoapods: 1.15.2
python: Not Found
python3: 3.9.6
ruby: 3.3.3
platforms: 
  - DriverKit 23.5
  - iOS 17.5
  - macOS 14.5
  - tvOS 17.5
  - visionOS 1.2
  - watchOS 10.5
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~14.0.6",
  "@angular/common": "~14.0.6",
  "@angular/compiler": "~14.0.6",
  "@angular/core": "~14.0.6",
  "@angular/forms": "~14.0.6",
  "@angular/platform-browser": "~14.0.6",
  "@angular/platform-browser-dynamic": "~14.0.6",
  "@angular/router": "~14.0.6",
  "@bigin/ns-url-handler": "^1.0.6",
  "@nativescript-community/ui-material-bottom-navigation": "7.0.20",
  "@nativescript-community/ui-material-tabs": "7.1.3",
  "@nativescript-community/ui-pager": "^13.0.35",
  "@nativescript/angular": "~14.0.2",
  "@nativescript/core": "~8.3.0",
  "@nativescript/datetimepicker": "^2.1.10",
  "@nativescript/geolocation": "^8.0.2",
  "@nativescript/google-maps": "1.4.4",
  "@nativescript/social-share": "^2.3.0",
  "@nativescript/theme": "~3.0.2",
  "@nativescript/unit-test-runner": "^3.0.4",
  "@ngx-translate/core": "^14.0.0",
  "@nstudio/nativescript-cardview": "^2.0.1",
  "@nstudio/nativescript-loading-indicator": "^4.1.2",
  "@triniwiz/nativescript-toasty": "^4.1.3",
  "angular2-uuid": "^1.1.1",
  "decode-google-map-polyline": "^1.0.1",
  "dotenv": "^16.4.1",
  "jwt-decode": "^3.1.2",
  "nativescript-barcodescanner": "^4.1.2",
  "nativescript-exit": "^1.0.1",
  "nativescript-oauth2": "^3.0.9",
  "nativescript-pdf-view": "^3.0.0-1",
  "nativescript-sqlite": "^2.8.6",
  "nativescript-ui-autocomplete": "^15.2.3",
  "nativescript-ui-calendar": "^8.0.2",
  "nativescript-ui-chart": "^9.0.1",
  "nativescript-ui-listview": "^10.0.2",
  "nativescript-ui-sidedrawer": "^10.0.2",
  "nativescript-windowed-modal": "^7.0.0",
  "rxjs": "~7.5.0",
  "zone.js": "~0.11.5"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~14.0.6",
  "@angular/compiler-cli": "~14.0.6",
  "@jsdevtools/coverage-istanbul-loader": "3.0.5",
  "@nativescript/android": "8.5.4",
  "@nativescript/ios": "8.7.2",
  "@nativescript/types": "~8.2.0",
  "@nativescript/webpack": "~5.0.6",
  "@ngtools/webpack": "~14.0.6",
  "@types/jasmine": "4.0.0",
  "karma": "6.3.0",
  "karma-coverage": "2.2.0",
  "karma-jasmine": "4.0.2",
  "karma-nativescript-launcher": "0.4.0",
  "nyc": "15.1.0",
  "typescript": "~4.7.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
