### DISCUSSION TITLE
How to can i build for android using github actions

### DISCUSSION THREAD

**Discussion by John4650-hub** [NativeScript/NativeScript#10693] [Q&A] [answered]
I have setup a workflow file using menny/android image for container. I usually use that for my android projects. 
Here is my workflow, so i wanted to see what the template "myCoolApp" for javascript looked like and tried building it , 
```yml
name: nativeScript

on:
  push:
    branches: Nad
jobs:
  build:
    runs-on: ubuntu-latest
    container: johnel/nativescript
    steps:
    - uses: actions/checkout@v4
    - name: Run g4f
      run: |
        ns create myCoolApp --js
        cd myCoolApp
        ns build android
        gh release create "${{ github.run_number }}.0.0" myCoolapp.zip
      env:
        GITHUB_TOKEN: ${{ secrets.TK }}
      shell: bash
```
I have ran into the same error that has be reported multiple time by alot of new users. I was detetmined to get started but something like settingup a simple build environment has taken me sometime.
```text
A compatible Android SDK for compilation is found.
Javac is installed and is configured properly.
The Java Development Kit (JDK) is installed and is configured properly.
Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
✖ WARNING: The Android SDK is not installed or is not configured properly. 
 You will not be able to run your apps in the native emulator. To be able to run apps
in the native Android emulator, verify that you have installed the latest Android SDK 
and its dependencies as described in 
``` 

Just incase you need it . I created a simple image
```Dockerfile
FROM menny/android
MAINTAINER John Delvin <johndelvin51@gmail.com>

# NodeJS
RUN apt-get update -y
RUN apt-get install nodejs -y
RUN apt-get install npm -y
RUN wget https://github.com/cli/cli/releases/download/v2.50.0/gh_2.50.0_linux_amd64.deb
RUN apt install -y ./gh_2.50.0_linux_amd64.deb
RUN npm install -g nativescript
```
