### ISSUE TITLE
Border radius is not working on Android API 17

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#1000]
<img width="255" alt="screen shot 2015-10-29 at 5 48 23 pm" src="https://cloud.githubusercontent.com/assets/5018471/10834687/4112eac4-7f00-11e5-9609-4e9bcbae2248.png">

This is a simplified version of our xml:

```xml
<Border class="list-icon" backgroundColor="#FAFAFA" borderColor="black">
    <Label color="red" class="icon-letter" text="H"/>
</Border>
```

and the CSS:

```css
.list-icon {
  border-width: 2;
  horizontal-align: center;
  vertical-align: center;
  margin: 0 0 0 15;
  border-radius: 22;
  width: 44;
  height: 44;
}
.icon-letter {
  horizontal-align: center;
  vertical-align: center;
  font-size: 16;
}
```
