### ISSUE TITLE
Error with SegmentedBar on IOS

### ISSUE THREAD

**Issue by sandruen** [NativeScript/NativeScript#10009]
### Issue Description

When I use SegmentedBar and SegmentedBarItem on IOS I receive following error message:

`ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'setTitleForSegmentAtIndex' of undefined`
  
This happens, when the SegmentedBarItem receives the title property through interpolation. 

So this throws the error:
`<SegmentedBarItem title="{{title1}}"></SegmentedBarItem>`

This works fine:
`<SegmentedBarItem title="my title"></SegmentedBarItem>`

  

### Relevant log output (if applicable)

```shell
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'setTitleForSegmentAtIndex' of undefined
  TypeError: Cannot read property 'setTitleForSegmentAtIndex' of undefined
  at SegmentedBarItem._update (file: src/webpack:/BodenDok/node_modules/@nativescript/core/ui/segmented-bar/index.ios.js:13:0)
  at SegmentedBarItem.set title [as title] (file: .../node_modules/@nativescript/core/ui/segmented-bar/segmented-bar-common.js:18:0)
  at ViewUtil.setPropertyInternal (file: .../node_modules/@nativescript/angular/fesm2015/nativescript-angular.mjs:1999:0)
  at ViewUtil.setProperty (file:///app/vendor.js:155319:12)
  at EmulatedRenderer.setProperty (file: .../node_modules/@nativescript/angular/fesm2015/nativescript-angular.mjs:2638:5)
  at file: .../node_modules/@nativescript/angular/fesm2015/nativescript-angular.mjs:2423:5
  at _ZoneDelegate.invoke (file: .../node_modules/zone.js/fesm2015/zone.js:879:0)
```

### Environment

```yaml
OS: macOS 12.3.1
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Shell: /bin/zsh
node: 18.6.0
npm: 8.15.0
nativescript: 8.3.0

# android
java: 11.0.8
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 13.4.1/13F100
cocoapods: 1.11.3
python: 3.8.5
python3: 3.8.5
ruby: 2.7.6
platforms: 
  - DriverKit 21.4
  - iOS 15.5
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
