### ISSUE TITLE
svelte native broken

### ISSUE THREAD

**Issue by ralyodio** [NativeScript/NativeScript#10007]
### Issue Description

error

### Relevant log output (if applicable)

```shell
Cannot find module '@nativescript/webpack/lib/before-checkForChanges.js'
```

### Environment

npm WARN exec The following package was not found and will be installed: nativescript-envinfo@1.0.9

```yaml
OS: Linux 5.15 Manjaro Linux
CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
Shell: /bin/zsh
node: 18.7.0
npm: 8.15.0
nativescript: 8.3.3

# android
java: 18.0.2
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: Not Found
cocoapods: Not Found
python: 3.10.5
python3: 3.10.5
ruby: 3.0.4
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@nativescript/theme": "^3.0.2",
  "nativescript-audio": "^6.2.6",
  "svelte-native": "*"
},
"devDependencies": {
  "@nativescript/android": "8.3.1",
  "@nativescript/core": "^8.1.3",
  "@nativescript/preview-cli": "1.0.0-beta.18",
  "@nativescript/types": "^8.3.1",
  "@nativescript/types-android": "^8.3.1",
  "@nativescript/types-ios": "^8.3.1",
  "@nativescript/types-minimal": "^8.3.0",
  "@nativescript/webpack": "^5.0.8",
  "svelte": "^3.44.0",
  "svelte-loader": "^3.1.2",
  "svelte-native-preprocessor": "^1.0.0",
  "svelte-preprocess": "^4.7.0",
  "typescript": "^4.5.5"
}
```

➜  calmness-mobile git:(main) ✗ 
$ 

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
