### ISSUE TITLE
ActivityIndicator CSS color support

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#1004]
ActivityIndicator color cannot be set via CSS. For example:
```CSS
ActivityIndicator {
 color: red;
}
```
