### ISSUE TITLE
[IOS] TextView goes behind the Keyboard on typing 

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#10041]
### Issue Description

Hi,

I am creating a chat page, that the body take 80% from the UI and at the bottom goes the Textview, when focussing on the Textview, the `IqKeyboardManager` it does the job and push the textview up, but when typing the first char at the keyboard then the textview goes down and behind the keyboard.

please see [the sample project here](https://github.com/kefahB/keyboardIssue) 

This behavior is occurred only when the textview foes under the keyboard open space range!

### Environment

```yaml
OS: macOS 12.6
CPU: (10) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 16.16.0
npm: 8.17.0
nativescript: 8.3.3

# android
java: 18.0.1
ndk: Not Found
apis: 23, 30, 31, 32, 33
build_tools: 31.0.0, 33.0.0
system_images: 
  - android-33 | Google APIs ARM 64 v8a

# ios
xcode: 13.4.1/13F100
cocoapods: 1.11.3
python: 3.9.12
python3: 3.9.12
ruby: 3.1.2
platforms: 
  - DriverKit 21.4
  - iOS 15.5
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "~8.3.0",
  "@nativescript/iqkeyboardmanager": "^2.0.0",
  "@nativescript/theme": "~3.0.2"
},
"devDependencies": {
  "@nativescript/ios": "8.3.3",
  "@nativescript/preview-cli": "1.0.1",
  "@nativescript/types": "~8.3.0",
  "@nativescript/webpack": "~5.0.6",
  "typescript": "~4.5.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
