### ISSUE TITLE
Error: Build input file cannot be found, when building NativeScript application with Xcode 14.01 using m1 mac

### ISSUE THREAD

**Issue by mb0484** [NativeScript/NativeScript#10051]
### Issue Description

When building nativescript cross-platform application for ios, i get the following error.

error: Build input file cannot be found: '*/platforms/ios/build/Debug-iphonesimulator/metadata-x86_64.bin'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

### Reproduction

1. Update or install Xcode 14.01 on m1 mac
2. Create new nativescript application (ns create some-demo-app, we pick Angular application)
3. Build and run application (ns build/run ios)

### Environment

```yaml
OS: macOS 12.6
CPU: (10) x64 Apple M1 Pro
Shell: /bin/zsh
node: 14.19.1
npm: 6.14.16
nativescript: 8.2.3

# android
java: 11.0.14.1
ndk: Not Found
apis: 26, 28, 29, 30, 31, 32
build_tools: 28.0.3, 29.0.2, 30.0.3, 31.0.0, 32.0.0
system_images: 
  - android-16 | Google APIs ARM EABI v7a
  - android-17 | Google APIs ARM EABI v7a
  - android-23 | ARM 64 v8a
  - android-30 | Google Play ARM 64 v8a
  - android-33 | Google APIs ARM 64 v8a
  - android-33 | Google Play ARM 64 v8a

# ios
xcode: 14.0.1/14A400
cocoapods: 1.11.3
python: 2.7.18
python3: 3.9.6
ruby: 2.7.6
platforms: 
  - DriverKit 21.4
  - iOS 16.0
  - macOS 12.3
  - tvOS 16.0
  - watchOS 9.0
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~14.2.0",
  "@angular/common": "~14.2.0",
  "@angular/compiler": "~14.2.0",
  "@angular/core": "~14.2.0",
  "@angular/forms": "~14.2.0",
  "@angular/platform-browser": "~14.2.0",
  "@angular/platform-browser-dynamic": "~14.2.0",
  "@angular/router": "~14.2.0",
  "@nativescript/angular": "~14.2.0",
  "@nativescript/core": "~8.3.0",
  "@nativescript/theme": "~3.0.2",
  "rxjs": "~7.5.0",
  "zone.js": "~0.11.5"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~14.2.0",
  "@angular/compiler-cli": "~14.2.0",
  "@nativescript/android": "8.2.4",
  "@nativescript/ios": "8.3.0",
  "@nativescript/types": "~8.3.0",
  "@nativescript/webpack": "~5.0.6",
  "@ngtools/webpack": "~14.2.0",
  "typescript": "~4.7.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
