### ISSUE TITLE
WebView not working in iOS simulator

### ISSUE THREAD

**Issue by overwise** [NativeScript/NativeScript#10053]
### Issue Description

WebView element is showing blank/white screen in iOS simulator. Android works fine. Just built it on the real iPhone, it seems like it works there as well.
```
<ActionBar title="test">
    <NavigationButton visibility="hidden" ></NavigationButton>
</ActionBar>
<WebView height="300" width="300"
    src="https://nativescript.org"
    (loadStarted)="onLoadStarted($event)"
    (loadFinished)="onLoadFinished($event)">
</WebView>
```
Android:
![Screenshot 2022-10-13 at 14 50 54](https://user-images.githubusercontent.com/6160910/195601001-51d6b6e6-92a5-42be-a786-20e24c758e8e.png)

iOS:
![Screenshot 2022-10-13 at 14 50 58](https://user-images.githubusercontent.com/6160910/195601038-e2a4da36-1e9d-48a2-94bc-46766b4bf695.png)

### Environment

```yaml
OS: macOS 12.6
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Shell: /bin/zsh
node: 16.14.1
npm: 8.5.0
nativescript: 8.3.3

# android
java: 13.0.1
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.0.1/14A400
cocoapods: 1.11.3
python: 2.7.18
python3: 3.9.6
ruby: 2.6.8
platforms: 
  - DriverKit 21.4
  - iOS 16.0
  - macOS 12.3
  - tvOS 16.0
  - watchOS 9.0
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~14.2.0",
  "@angular/common": "~14.2.0",
  "@angular/compiler": "~14.2.0",
  "@angular/core": "~14.2.0",
  "@angular/forms": "~14.2.0",
  "@angular/platform-browser": "~14.2.0",
  "@angular/platform-browser-dynamic": "~14.2.0",
  "@angular/router": "~14.2.0",
  "@nativescript/angular": "~14.2.0",
  "@nativescript/core": "~8.3.0",
  "@nativescript/theme": "~3.0.2",
  "nativescript-phone": "^3.0.3",
  "rxjs": "~7.5.0",
  "zone.js": "~0.11.5"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~14.2.0",
  "@angular/compiler-cli": "~14.2.0",
  "@nativescript/android": "8.3.1",
  "@nativescript/ios": "8.3.3",
  "@nativescript/types": "~8.3.0",
  "@nativescript/webpack": "~5.0.6",
  "@ngtools/webpack": "~14.2.0",
  "typescript": "~4.7.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
