### ISSUE TITLE
Problem accessing file in Downloads directory on Android 12

### ISSUE THREAD

**Issue by ray007** [NativeScript/NativeScript#10054]
### Issue Description

To import and export config files (in json format), the `Downloads` directory seemed to be a good location so far.

With our new test device with Android 12, that suddenly does not work anymore.
Trying to read or write a file there runs into an `EACCESS` error.

Looking in settings under `App permissions`, my app is allowed `Files and media`, but it's set to `media only` and requires manually setting to `Allow management of all files` before I can import config files from the downloads directory again.

I have even added a line
```xml
<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>
```
to my `AndroidManifest.xml` file and an attribute `android:requestLegacyExternalStorage="true"` to its `application` tag, but nothing seems to help so far.

### Environment

```yaml
OS: Windows 10 10.0.19042
CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
Shell: Not Found
node: 16.17.1
npm: 8.19.2
nativescript: Not Found

# android
java: Not Found
ndk: Not Found
apis: 28, 29, 30, 31, 32
build_tools: 29.0.2, 32.0.0, 32.1.0
system_images: Not Found

# ios
xcode: Not Found
cocoapods: Not Found
python: Not Found
python3: Not Found
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@akylas/nativescript-checkbox": "^2.0.5",
  "@bradmartin/nativescript-urlhandler": "^2.0.1",
  "@nativescript-community/ble": "^3.1.8",
  "@nativescript-community/preferences": "^1.3.0",
  "@nativescript-community/systemui": "^1.1.8",
  "@nativescript-community/ui-collectionview": "^4.0.62",
  "@nativescript-community/ui-material-bottomnavigationbar": "^7.0.28",
  "@nativescript-community/ui-material-bottomsheet": "^7.0.28",
  "@nativescript-community/ui-material-button": "^7.0.28",
  "@nativescript-community/ui-material-progress": "^7.0.28",
  "@nativescript-community/ui-share-file": "^1.2.3",
  "@nativescript/appavailability": "^2.0.0",
  "@nativescript/appversion": "^2.0.0",
  "@nativescript/core": "~8.3.5",
  "@nativescript/secure-storage": "^3.0.0",
  "@nativescript/theme": "^3.0.2",
  "@nota/nativescript-webview-ext": "^8.0.2",
  "@prabudevarrajan/filepicker": "^2.0.0",
  "@sergeymell/nativescript-svg": "^1.1.2",
  "buffer": "^6.0.3",
  "crypto-browserify": "^3.12.0",
  "debounce": "^1.2.1",
  "http-auth-client": "^0.4.1",
  "js-base64": "^3.7.2",
  "js-pkce": "^1.2.1",
  "nativescript-cscreenshot": "^1.2.1",
  "nativescript-drop-down": "^6.0.2",
  "nativescript-inappbrowser": "^3.2.0",
  "nativescript-permissions": "^1.3.12",
  "nativescript-ui-listview": "^10.2.6",
  "nativescript-ui-sidedrawer": "^10.0.2",
  "nativescript-videoplayer": "^5.0.1",
  "nativescript-vue": "^2.9.3",
  "url-search-params-polyfill": "^8.1.1"
},
"devDependencies": {
  "@babel/core": "^7.19.3",
  "@babel/preset-env": "^7.19.3",
  "@nativescript/android": "8.3.1",
  "@nativescript/ios": "8.3.3",
  "@nativescript/types": "~8.3.1",
  "@nativescript/webpack": "~5.0.8",
  "babel-loader": "^8.2.5",
  "nativescript-vue-template-compiler": "^2.9.3",
  "node-sass": "^7.0.3",
  "typescript": "^4.8.4",
  "vue-loader": "^17.0.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
