### ISSUE TITLE
Memory leaks with using builtin Image UI Component

### ISSUE THREAD

**Issue by danishashraf047** [NativeScript/NativeScript#10068]
### Issue Description

When I use the image component so the app does memory leaks and it increases the memory after navigating back to the previous page and then navigating to that page where the image component is there whether I dispose of the native view. I also used GC() method to release the JS garbage. Except for GC(), I couldn't able to find other methods which could release the native view memory.

### Reproduction

Whenever the image component loads. If I get back to the previous page and navigate to that page where the image component is there I see the memory increases.

### Environment

```yaml
OS: macOS 12.3.1
CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
Shell: /bin/zsh
node: 14.17.0
npm: 7.19.1
nativescript: 8.2.3

# android
java: 15.0.2
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 13.3.1/13E500a
cocoapods: 1.10.1
python: 3.7.9
python3: 3.7.9
ruby: 2.7.6
platforms: 
  - DriverKit 21.4
  - iOS 15.4
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {},
"devDependencies": {}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
