### ISSUE TITLE
[IOS] Safe area with scrollview

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#10061]
### Issue Description

Hi,

I am facing a problem with safe area on IOS with a chat layout.

The problem is that in order to resolve the `Keyboard` overflowing the `TextField` we should use `@nativescript/iqkeyboardmanager` and wrapping every think within a `ScrollView`.

The problem if the scrollview has more then one child, the last child doesn't overflow the unsafe area please [see this sample project](https://stackblitz.com/edit/nativescript-stackblitz-templates-3nntxz?file=app%2Fmain-page.xml,package.json&title=NativeScript%20Starter%20TypeScript)  

Any idea for this problem, does I misunderstanding some think ?

Thanks

### Environment

```yaml
OS: macOS 12.6
CPU: (10) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 16.16.0
npm: 8.17.0
nativescript: 8.3.3

# android
java: 18.0.1
ndk: Not Found
apis: 23, 30, 31, 32, 33
build_tools: 31.0.0, 33.0.0
system_images: 
  - android-33 | Google APIs ARM 64 v8a

# ios
xcode: 13.4.1/13F100
cocoapods: 1.11.3
python: 3.9.12
python3: 3.9.12
ruby: 3.1.2
platforms: 
  - DriverKit 21.4
  - iOS 15.5
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@kefah/nativescript-uuid": "^1.0.1",
  "@nativescript-community/fonticon": "^3.0.0",
  "@nativescript-community/ui-canvas": "^4.4.4",
  "@nativescript-community/ui-collectionview": "^4.0.57",
  "@nativescript-community/ui-material-bottom-navigation": "^7.0.25",
  "@nativescript-community/ui-material-bottomnavigationbar": "^7.0.25",
  "@nativescript-community/ui-material-dialogs": "^7.0.28",
  "@nativescript-community/ui-material-tabs": "^7.0.28",
  "@nativescript-community/universal-links": "^3.0.0",
  "@nativescript/appversion": "^2.0.0",
  "@nativescript/background-http": "^6.0.0",
  "@nativescript/core": "^8.3.1",
  "@nativescript/datetimepicker": "^2.1.11",
  "@nativescript/firebase-auth": "^2.3.4",
  "@nativescript/firebase-core": "^2.3.4",
  "@nativescript/firebase-crashlytics": "^2.3.4",
  "@nativescript/firebase-messaging": "^2.3.4",
  "@nativescript/geolocation": "^8.0.2",
  "@nativescript/imagepicker": "^1.0.7",
  "@nativescript/iqkeyboardmanager": "^2.0.0",
  "@nativescript/local-notifications": "^6.0.0",
  "@nativescript/localize": "^5.0.4",
  "@nativescript/secure-storage": "^3.0.0",
  "@nativescript/theme": "^3.0.2",
  "@nstudio/nativescript-cardview": "^2.0.1",
  "@nstudio/nativescript-checkbox": "^2.0.5",
  "@nstudio/nativescript-fancyalert": "^4.0.1",
  "@nstudio/nativescript-filterable-listpicker": "^3.0.1",
  "@nstudio/nativescript-loading-indicator": "^4.1.2",
  "@triniwiz/nativescript-stripe": "^8.0.3",
  "@triniwiz/nativescript-toasty": "^4.1.3",
  "@types/google-libphonenumber": "^7.4.23",
  "base-64": "^1.0.0",
  "build-url-ts": "^6.1.3",
  "crypto-js": "^4.1.1",
  "email-validator": "^2.0.4",
  "google-libphonenumber": "^3.2.29",
  "moment": "^2.29.4",
  "nativescript": "^8.2.3",
  "nativescript-feedback": "^2.0.0",
  "nativescript-intl": "^4.0.2",
  "nativescript-modal-datetimepicker": "^2.1.5",
  "nativescript-phone": "^3.0.3",
  "nativescript-ui-autocomplete": "^8.0.1",
  "nativescript-ui-calendar": "^14.2.1",
  "nativescript-ui-listview": "^10.2.7",
  "nativescript-ui-sidedrawer": "^10.0.2",
  "rxjs": "^7.5.6",
  "url-parse": "^1.5.10",
  "utf8": "^3.0.0",
  "uuid": "^8.3.2"
},
"devDependencies": {
  "@nativescript/android": "8.3.1",
  "@nativescript/ios": "8.3.3",
  "@nativescript/types": "~8.3.1",
  "@nativescript/webpack": "~5.0.6",
  "typescript": "~4.5.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
