### ISSUE TITLE
[iOS 14] ActionBar not respecting safe area, shown under the status bar

### ISSUE THREAD

**Issue by fpaaske** [NativeScript/NativeScript#10067]
### Issue Description

I have an app using nested page routing outlets, and the ActionBar on the _first tab_ of the _nested page router outlet_ will appear under the status bar. The other tabs works as expected.

This only happens on iOS 14.x.

It happened after moving from @nativescript-community/ui-material-bottom-navigation to @nativescript-community/ui-material-bottomnavigationbar. However, it also happens when I remove the usage of the ui-material-bottomnavigationbar as well, and just use a custom tab bar, so it's probably not really linked to that.

There's a similar issue reported here: https://github.com/nativescript-community/ui-material-components/issues/308

I've tried to set padding-/marginTop to force it down, without luck.

This is how it (correctly) looks on iOS 12, 15 and 16.
![image](https://user-images.githubusercontent.com/1579581/197797356-eafb1ea2-4013-44b7-b31b-d98e2df4415a.png)

![image](https://user-images.githubusercontent.com/1579581/197804169-0477833d-d88a-4185-a2e6-1c5eb2fcb298.png)
---
Here's iOS 14 on iPhone 8
![image](https://user-images.githubusercontent.com/1579581/197804351-796b1804-4ff0-4add-8f37-7293218945ea.png)

![image](https://user-images.githubusercontent.com/1579581/197797543-0093ab4a-b3cd-4fef-84d0-caa4155a609d.png)

iPhone X
![image](https://user-images.githubusercontent.com/1579581/197804425-dfb87cd8-49fb-4c81-850c-b62260727c0f.png)

![image](https://user-images.githubusercontent.com/1579581/197797588-cbf8e05d-d0b5-4990-ac72-ee1e824b15fc.png)

iPhone 12 Pro
![image](https://user-images.githubusercontent.com/1579581/197804615-4209eccc-235b-4f16-9185-bd09b0ca0c86.png)

![image](https://user-images.githubusercontent.com/1579581/197797625-21ca104e-8a16-4d2a-a025-5ba69e1cb9dc.png)

### Reproduction

This is from another, simpler app, but same issue.

app.component

```
<page-router-outlet></page-router-outlet>
```

```
const routes: Routes = [
  {
    path: "",
    redirectTo: "tabs/default",
    pathMatch: "full",
  },
  {
    path: "tabs",
    loadChildren: () =>
      import("./features/tabs/tabs.module").then((m) => m.TabsModule),
  },
];
```

---

tabs.component

```
<GridLayout rows="* auto">
  <GridLayout row="0" [hidden]="selectedTabIndex !== 0">
    <page-router-outlet name="charactersTab"></page-router-outlet>
  </GridLayout>
  <GridLayout row="0" [hidden]="selectedTabIndex !== 1">
    <page-router-outlet name="seriesTab"></page-router-outlet>
  </GridLayout>

  <BottomNavigationBar row="1" class="bottom-navigation-bar"
                       (tabSelected)="tabSelected($event)"
                       (tabReselected)="tabReselected($event)"
  >
    <BottomNavigationTab title="Characters">
    </BottomNavigationTab>
    <BottomNavigationTab title="Series">
    </BottomNavigationTab>
  </BottomNavigationBar>
</GridLayout>
```

```
const routes: Routes = [
  {
    path: "default",
    component: TabsComponent,
    children: [
      {
        path: "characters",
        outlet: "charactersTab",
        component: NSEmptyOutletComponent,
        loadChildren: () =>
          import("~/features/character-list/character-list.module").then(
            (m) => m.CharacterListModule
          ),
      },
      {
        path: "series",
        outlet: "seriesTab",
        component: NSEmptyOutletComponent,
        loadChildren: () =>
          import("~/features/series-list/series-list.module").then(
            (m) => m.SeriesListModule
          ),
      },
    ],
  },
];
```
---

characters-list

```
<ActionBar title="Characters"></ActionBar>
<GridLayout rows="auto, *">
...
</GridLayout>
```
---

series-list

```
<ActionBar title="Series"></ActionBar>
<GridLayout rows="auto, *">
...
</GridLayout>
```

---

iPhone X iOS 12, all good:
![image](https://user-images.githubusercontent.com/1579581/197806711-c091ecfd-542c-4841-b76b-5a1befb82e0a.png)

![image](https://user-images.githubusercontent.com/1579581/197806965-e4a0f48c-8a08-4bf5-9788-da61703751b9.png)

iPhone X iOS 14

First tab, characters, NOT OK
![image](https://user-images.githubusercontent.com/1579581/197807153-dfe63535-8a51-4af3-aeff-2147c170e445.png)

![image](https://user-images.githubusercontent.com/1579581/197807644-d3edc502-f357-4219-8715-61fe6367291c.png)

Second tab, series, OK
![image](https://user-images.githubusercontent.com/1579581/197807276-b8569307-0d44-4e26-a343-9faa6ba3815e.png)

![image](https://user-images.githubusercontent.com/1579581/197807873-c8e19213-38b4-424c-be19-431490caa706.png)

### Environment

```yaml
OS: macOS 12.6
CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Shell: /bin/zsh
node: 16.16.0
npm: 8.11.0
nativescript: 8.3.3

# android
java: 11.0.16
ndk: Not Found
apis: 23, 30, 31, 32
build_tools: 30.0.3, 31.0.0, 33.0.0
system_images: 
  - android-23 | Google APIs ARM EABI v7a
  - android-23 | Google APIs Intel x86 Atom
  - android-23 | Google APIs Intel x86 Atom_64
  - android-24 | Google APIs Intel x86 Atom
  - android-30 | Google APIs Intel x86 Atom
  - android-30 | Google APIs Intel x86 Atom_64
  - android-30 | Google Play Intel x86 Atom
  - android-31 | Google APIs Intel x86 Atom_64
  - android-31 | Google Play Intel x86 Atom_64

# ios
xcode: 14.0.1/14A400
cocoapods: 1.11.2
python: 2.7.18
python3: 3.9.13
ruby: 2.7.6
platforms: 
  - DriverKit 21.4
  - iOS 16.0
  - macOS 12.3
  - tvOS 16.0
  - watchOS 9.0
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~14.1.0",
  "@angular/common": "~14.1.0",
  "@angular/compiler": "~14.1.0",
  "@angular/core": "~14.1.0",
  "@angular/forms": "~14.1.0",
  "@angular/platform-browser": "~14.1.0",
  "@angular/platform-browser-dynamic": "~14.1.0",
  "@angular/router": "~14.1.0",
  "@nativescript-community/ui-collectionview": "^4.0.0",
  "@nativescript-community/ui-material-bottomnavigationbar": "^7.0.0",
  "@nativescript-community/ui-material-bottom-navigation": "^7.0.0",
  "@nativescript-community/ui-material-tabs": "^7.0.0",
  "@nativescript/angular": "^14.2.5",
  "@nativescript/core": "~8.3.1",
  "@nativescript/theme": "~3.0.2",
  "crypto-js": "^4.1.1",
  "rxjs": "~7.5.0",
  "zone.js": "~0.11.5"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~14.1.0",
  "@angular/compiler-cli": "~14.1.0",
  "@nativescript/android": "~8.3.1",
  "@nativescript/ios": "~8.3.3",
  "@nativescript/types": "~8.3.1",
  "@nativescript/webpack": "^5.0.8",
  "@ngtools/webpack": "~14.1.0",
  "prettier": "2.7.1",
  "typescript": "~4.7.4"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
