### ISSUE TITLE
ImageSource.fromAsset Memory leak

### ISSUE THREAD

**Issue by brysem** [NativeScript/NativeScript#10087]
### Issue Description

When calling `ImageSource.fromAsset(image)` memory is leaked.

I am aware of the issue https://github.com/NativeScript/NativeScript/issues/9694 which seems to indicate the same problem but it seems that it has returned from the graveyard.

### Reproduction

I created a brand new project to reproduce the issue that I was experiencing in my own app.
https://github.com/atabix/nativescript-image-leak

1. clone the repository
2. npm install
3. ns run ios

![image](https://user-images.githubusercontent.com/2829285/201364323-c530036b-5e26-481e-99ef-b182f9507f47.png)

### Environment

```yaml
OS: macOS 12.5.1
CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
Shell: /bin/zsh
node: 18.7.0
npm: 8.15.0
nativescript: 8.3.3

# android
java: 1.8.0_275
ndk: Not Found
apis: 29, 30, 31
build_tools: 29.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
system_images:
  - android-29 | Google APIs Intel x86 Atom
  - android-30 | Google APIs Intel x86 Atom
  - android-30 | Google Play Intel x86 Atom

# ios
xcode: 14.1/14B47b
cocoapods: 1.11.3
python: 2.7.18
python3: 3.9.6
ruby: 2.6.8
platforms:
  - DriverKit 22.1
  - iOS 16.1
  - macOS 13.0
  - tvOS 16.1
  - watchOS 9.1
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "~8.3.0",
  "@nativescript/imagepicker": "^1.0.7",
  "@nativescript/theme": "~3.0.2"
},
"devDependencies": {
  "@nativescript/ios": "8.3.3",
  "@nativescript/types": "~8.3.0",
  "@nativescript/webpack": "~5.0.9",
  "typescript": "~4.5.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
