### ISSUE TITLE
Using non-default font-family & styling

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#1008]
I am trying to apply a different font other than the default one to the entire app. Found this to be usefull for iOS: http://iosfonts.com/

Now, When I set my css for Page to be like below, and a separate class for making fonts bold. 
The new font is **not** loaded and bold **does** work.
```css
Page {
font-family: "Avenir"
}
.make-it-bold{
font-weight: bold;
}
```

But if I set it like this, font **is** loaded. But bolding fonts does **not** work. 
I had to use specific class that uses the bold variant of the font. 
```css
Page {
font-family: "Avenir-Roman"
}
.make-it-bold{
font-weight: bold;
}
.make-it-bold-avenir{
font-family: "Avenir-Heavy"
}
```

Is this the way things work or is it a glitch? Am I using the font-family correctly?
