### ISSUE TITLE
Android 12 android:exported issue not able to upload to playstore

### ISSUE THREAD

**Issue by kranthi-kiki** [NativeScript/NativeScript#10099]
### Issue Description

I have added android: exported to the activity and service section in the AndroidManifest file. but while Uploading the APK to the play store  getting issues like 
`You uploaded an APK or Android App Bundle which has an activity, activity alias, service or broadcast receiver with intent filter, but without the 'android:exported' property set. This file can't be installed on Android 12 or higher. `

<img width="1442" alt="image" src="https://user-images.githubusercontent.com/46471488/202890070-94297d80-5218-4000-be97-1f57cc4a0ce9.png">

### Environment

```yaml
OS: macOS 11.4
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Shell: /bin/zsh
node: 16.14.0
npm: 8.3.1
nativescript: 8.3.3

# android
java: 11.0.14.1
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 12.4/12D4e
cocoapods: 1.10.1
python: 2.7.16
python3: 3.10.6
ruby: 2.6.3
platforms: 
  - iOS 14.4
  - DriverKit 20.2
  - macOS 11.1
  - tvOS 14.3
  - watchOS 7.2
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "^12.2.5",
  "@angular/common": "^12.2.5",
  "@angular/compiler": "^12.2.5",
  "@angular/core": "^12.2.5",
  "@angular/forms": "^12.2.5",
  "@angular/platform-browser": "^12.2.5",
  "@angular/platform-browser-dynamic": "^12.2.5",
  "@angular/router": "^12.2.5",
  "@master.technology/permissions": "^2.0.1",
  "@nativescript/angular": "^12.2.0",
  "@nativescript/appversion": "^2.0.0",
  "@nativescript/camera": "^5.0.10",
  "@nativescript/core": "~8.1.1",
  "@nativescript/firebase": "^11.1.3",
  "@nativescript/geolocation": "^8.0.2",
  "@nativescript/imagepicker": "^1.0.6",
  "@nativescript/social-share": "^2.0.4",
  "@nativescript/theme": "~2.3.0",
  "@ngneat/effects": "^1.0.0",
  "@ngneat/effects-ng": "^1.0.0",
  "@ngneat/elf": "^1.5.0",
  "@ngneat/elf-cli-ng": "^1.0.0",
  "@ngneat/elf-devtools": "^1.2.0",
  "@ngneat/elf-entities": "^4.0.1",
  "@ngneat/elf-pagination": "^1.0.0",
  "@ngneat/elf-persist-state": "^1.1.1",
  "@ngneat/elf-requests": "^1.1.2",
  "@ngneat/elf-state-history": "^1.0.1",
  "@nstudio/nativescript-cardview": "^2.0.0",
  "@nstudio/nativescript-fancyalert": "^4.0.1",
  "@nstudio/nativescript-loading-indicator": "^4.0.0",
  "@nstudio/nativescript-snackbar": "^2.1.0",
  "@triniwiz/nativescript-toasty": "^4.1.3",
  "date-fns": "^2.28.0",
  "nativescript-carousel": "^7.0.1",
  "nativescript-exit": "^1.0.1",
  "nativescript-gif": "^5.0.0",
  "nativescript-image-cache": "^1.1.6",
  "nativescript-phone": "^3.0.3",
  "nativescript-sqlite": "^2.6.4",
  "nativescript-theme-core": "~1.0.6",
  "nativescript-ui-listview": "^9.0.1",
  "nativescript-ui-sidedrawer": "~9.0.0",
  "reflect-metadata": "~0.1.12",
  "rxjs": "~7.3.0",
  "rxjs-compat": "^6.4.0",
  "ts-pattern": "^3.3.5",
  "zone.js": "~0.11.1"
},
"devDependencies": {
  "@angular/compiler-cli": "^12.2.5",
  "@nativescript/android": "8.0.0",
  "@nativescript/ios": "~8.1.0",
  "@nativescript/webpack": "~5.0.0",
  "@ngneat/elf-cli": "^2.2.0",
  "@ngtools/webpack": "^12.2.5",
  "codelyzer": "~6.0.0",
  "install": "^0.13.0",
  "sass": "~1.39.0",
  "tslint": "~6.1.3",
  "tslint-config-prettier": "^1.18.0",
  "typescript": "~4.3.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
