### ISSUE TITLE
Slider CSS color/background-color support

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#1010]
Slider color and background-color not working properly. For example:
```CSS
Slider {
 color: red;
 background-color: red;
}
```
