### ISSUE TITLE
ios question regarding 8.4

### ISSUE THREAD

**Issue by serrg1994** [NativeScript/NativeScript#10119]
### Issue Description

Previously my app was running 8.3.6 version and all was very smooth and after updating to latest version it started to be very very laggy and it almost impossible to use it.  On Android I did not notice any issues

### Environment

```yaml
OS: macOS 13.0.1
CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Shell: /bin/zsh
node: 14.19.0
npm: 8.5.0
nativescript: 8.3.3

# android
java: 18.0.1
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.1/14B47b
cocoapods: 1.11.3
python: 2.7.18
python3: 3.9.6
ruby: 2.6.10
platforms: 
  - DriverKit 22.1
  - iOS 16.1
  - macOS 13.0
  - tvOS 16.1
  - watchOS 9.1
```

### Dependencies

```json
"dependencies": {
  "@nativescript-community/text": "^1.5.10",
  "@nativescript-community/ui-collectionview": "4.0.64",
  "@nativescript-community/ui-material-bottomsheet": "7.0.31",
  "@nativescript-community/ui-material-button": "7.0.31",
  "@nativescript-community/ui-material-ripple": "7.0.31",
  "@nativescript/appversion": "2.0.0",
  "@nativescript/background-http": "6.0.0",
  "@nativescript/camera": "5.0.13",
  "@nativescript/core": "8.4.1",
  "@nativescript/datetimepicker": "2.1.11",
  "@nativescript/email": "2.0.5",
  "@nativescript/firebase": "11.1.3",
  "@nativescript/google-maps": "1.4.9",
  "@nativescript/localize": "5.0.4",
  "@nativescript/social-share": "2.3.0",
  "@nativescript/theme": "3.0.2",
  "@nstudio/nativescript-cardview": "2.0.1",
  "@nstudio/nativescript-carousel": "8.0.3",
  "@nstudio/nativescript-pulltorefresh": "3.0.2",
  "@ticnat/nativescript-image-cache": "1.0.7",
  "@triniwiz/nativescript-image-zoom": "4.1.3",
  "axios": "^0.27.2",
  "fs-extra": "11.1.0",
  "jwt-decode": "3.1.2",
  "nativescript-audio": "6.2.6",
  "nativescript-clipboard": "2.1.1",
  "nativescript-numeric-keyboard": "5.0.2",
  "nativescript-orientation": "2.2.5",
  "nativescript-permissions": "1.3.12",
  "nativescript-qr-generator": "3.0.0",
  "nativescript-taptic-engine": "2.1.0",
  "nativescript-ui-chart": "14.2.1",
  "nativescript-urlhandler": "1.3.0-master-31",
  "nativescript-uuid": "0.0.1",
  "nativescript-videoplayer": "5.0.1",
  "nativescript-vue": "2.9.3",
  "nativescript-vue-lifecycle-hooks": "1.0.0",
  "nativescript-windowed-modal": "7.0.0",
  "querystring": "0.2.1",
  "url-parse": "1.5.10",
  "vue-class-component": "7.2.6",
  "vue-property-decorator": "7.3.0",
  "vuex": "3.6.2",
  "x2js": "3.4.4",
  "xml-escape": "1.1.0"
},
"devDependencies": {
  "@babel/core": "^7.11.4",
  "@babel/preset-env": "^7.11.0",
  "@nativescript/android": "^8.2.3",
  "@nativescript/ios": "8.3.3",
  "@nativescript/webpack": "~5.0.6",
  "babel-loader": "^8.0.2",
  "nativescript-vue-template-compiler": "2.9.3",
  "typescript": "^3.9.7"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
