### ISSUE TITLE
Webpack compilation time increased from v4 to v5

### ISSUE THREAD

**Issue by felixkrautschuk** [NativeScript/NativeScript#10124]
### Issue Description

After upgrading one of our projects from using @nativescript/webpack 4.1.0 -> 5.0.12 (or even 5.0.0), the webpack compilation got really slow.
In our app folder we have a styles folder with about 70 css files (different color templates, the user can choose from).

When creating a new blank NS project and just add this styles folder, I see a huge difference when testing with webpack 4.1.0 and 5.0.12:

- 4.1.0: about 2-3 seconds
- 5.0.12: about 17 seconds

> webpack 5.75.0 compiled successfully in 16847 ms
> Webpack compilation complete. Watching for file changes.

### Reproduction

The following sample app is a new blank NS project and I just added a styles folder with about 70 css files, they contain all the same dummy css from https://www.w3schools.com/w3css/4/w3.css just for demonstration purposes.

Webpack 5:
[ns_webpack_5.zip](https://github.com/NativeScript/NativeScript/files/10174530/ns_webpack_5.zip)

Webpack 4:
[ns_webpack_4.zip](https://github.com/NativeScript/NativeScript/files/10174533/ns_webpack_4.zip)

### Relevant log output (if applicable)

```shell
n/a
```

### Environment

```yaml
OS: macOS 13.0.1
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Shell: /bin/zsh
node: 16.17.0
npm: 8.15.0
nativescript: 8.4.0

# android
java: 11.0.11
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.1/14B47b
cocoapods: 1.11.3
python: 2.7.18
python3: 3.10.8
ruby: 2.7.6
platforms: 
  - DriverKit 22.1
  - iOS 16.1
  - macOS 13.0
  - tvOS 16.1
  - watchOS 9.1
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "^8.4.1"
},
"devDependencies": {
  "@nativescript/android": "^8.4.0",
  "@nativescript/ios": "^8.4.0",
  "@nativescript/webpack": "^5.0.12"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
