### ISSUE TITLE
iOS: When execute more than one animation it is not canceled

### ISSUE THREAD

**Issue by vallemar** [NativeScript/NativeScript#10143]
### Issue Description

When you run an animation and then run another on the same element on ios the first animation is not cancelled. In android it works fine

### Environment

```yaml
OS: macOS 13.1
CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor            
Shell: /bin/zsh
node: 18.12.1
npm: 8.19.2
nativescript: 8.4.0

# android
java: 11.0.17
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.2/14C18
cocoapods: 1.11.3
python: 3.11.1
python3: 3.11.1
ruby: 2.7.7
platforms: 
  - DriverKit 22.2
  - iOS 16.2
  - macOS 13.1
  - tvOS 16.1
  - watchOS 9.1
```

### Dependencies

```json
"dependencies": {
  "@nativescript-community/text": "^1.5.11",
  "@nativescript-community/ui-canvaslabel": "^1.1.8",
  "@nativescript-community/ui-collectionview": "^4.0.64",
  "@nativescript-community/ui-label": "^1.2.16",
  "@nativescript-community/ui-lottie": "^5.0.3",
  "@nativescript-community/ui-material-cardview": "^7.0.31",
  "@nativescript-community/ui-material-tabs": "^7.0.31",
  "@nativescript-community/ui-material-textfield": "^7.0.33",
  "@nativescript-community/ui-svg": "^0.1.2",
  "@nativescript/core": "^8.4.1",
  "@nativescript/firebase-core": "^2.4.4",
  "@nativescript/firebase-messaging": "^2.4.4",
  "@nativescript/geolocation": "^8.1.0",
  "@nativescript/google-maps": "^1.4.9",
  "@nstudio/nativescript-shimmer": "^1.0.7",
  "axios": "^0.19.2",
  "moment": "^2.29.4",
  "nativescript-vue": "^3.0.0-beta.5",
  "patch-package": "^6.5.0",
  "pinia": "^2.0.27",
  "router-vue-native": "^2.0.0"
},
"devDependencies": {
  "@nativescript/android": "^8.4.0",
  "@nativescript/ios": "8.4.0",
  "@nativescript/tailwind": "^2.0.1",
  "@nativescript/types": "~8.4.0",
  "@nativescript/webpack": "~5.0.0",
  "@types/node": "~17.0.21",
  "sass": "^1.56.1",
  "sass-loader": "^13.2.0",
  "tailwindcss": "^3.1.8",
  "typescript": "~4.8.4",
  "vue": "^3.2.45"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
