### ISSUE TITLE
ios only: starting a navigation transition after an animation was canceled causes current page to be cleared, seems related to a bug in CSS

### ISSUE THREAD

**Issue by cjohn001** [NativeScript/NativeScript#10163]
### Issue Description

Hello together,
after having a discussion on Discord in regards to the issue where it was mentioned that this might be a Core rather than an Angular problem, I thought it make sense to cross reference the issue here.

https://github.com/NativeScript/angular/issues/105

I was unfortunately not able to create a demo showcasing the bug. If someone could give me directions where to look at I would try to look at the issue more closely.

### Environment

```yaml
OS: macOS 13.0.1
CPU: (10) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 18.12.1
npm: 8.19.2
nativescript: 8.4.0

# android
java: 11.0.16.1
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.2/14C18
cocoapods: 1.11.3
python: 3.9.14
python3: 3.9.6
ruby: 2.7.6
platforms: 
  - DriverKit 22.2
  - iOS 16.2
  - macOS 13.1
  - tvOS 16.1
  - watchOS 9.1
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "15.0.4",
  "@angular/common": "15.0.4",
  "@angular/compiler": "15.0.4",
  "@angular/core": "15.0.4",
  "@angular/forms": "15.0.4",
  "@angular/platform-browser": "15.0.4",
  "@angular/platform-browser-dynamic": "15.0.4",
  "@angular/router": "15.0.4",
  "@apollo/client": "3.7.3",
  "@mnd/external-web-view": "file:../mnd-plugins/dist/packages/external-web-view/mnd-external-web-view-1.0.0.tgz",
  "@nativescript/angular": "15.0.1",
  "@nativescript/core": "8.4.3",
  "@nativescript/iqkeyboardmanager": "2.1.0",
  "@nativescript/localize": "5.0.4",
  "@nativescript/mlkit-barcode-scanning": "1.0.6",
  "@nativescript/mlkit-core": "1.0.6",
  "@nativescript/secure-storage": "3.0.0",
  "@nativescript/theme": "3.0.2",
  "@nativescript/ui-charts": "0.2.4",
  "apollo-angular": "4.2.0",
  "apollo3-cache-persist": "0.14.1",
  "d3-ease": "3.0.1",
  "graphql": "16.6.0",
  "graphql-tag": "2.12.6",
  "intl": "1.2.5",
  "moment": "2.29.4",
  "nativescript-health-data": "file:../mnd-custom-plugins/nativescript-health-data/publish/package/nativescript-health-data-2.0.0.tgz",
  "nativescript-oauth2-ext": "file:../mnd-custom-plugins/nativescript-oauth2-ext/publish/package/nativescript-oauth2-ext-3.0.0.tgz",
  "nativescript-sqlite": "2.8.6",
  "nativescript-ui-calendar": "14.2.1",
  "nativescript-ui-gauge": "14.2.1",
  "rxjs": "7.8.0",
  "uuid": "9.0.0",
  "zone.js": "0.12"
},
"devDependencies": {
  "@angular-devkit/build-angular": "15.0.5",
  "@angular/compiler-cli": "15.0.4",
  "@graphql-codegen/cli": "2.16.3",
  "@graphql-codegen/fragment-matcher": "3.3.3",
  "@graphql-codegen/introspection": "2.2.3",
  "@graphql-codegen/typescript": "2.8.7",
  "@graphql-codegen/typescript-apollo-angular": "3.5.6",
  "@graphql-codegen/typescript-operations": "2.5.12",
  "@nativescript/android": "8.4.0",
  "@nativescript/ios": "8.4.0",
  "@nativescript/types": "8.4.0",
  "@nativescript/webpack": "5.0.12",
  "@ngtools/webpack": "15.0.5",
  "@types/d3-ease": "3.0.0",
  "@types/intl": "1.2.0",
  "@types/node": "18.11.18",
  "@types/uuid": "9.0.0",
  "keycloak-request-token": "0.1.0",
  "rimraf": "3.0.2",
  "sass": "1.57.1",
  "ts-node": "10.9.1",
  "typescript": "4.8.4"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
