### ISSUE TITLE
Performance issues on iOS starting from core@8.4.0, slow/sluggish animation

### ISSUE THREAD

**Issue by dkzeb** [NativeScript/NativeScript#10189]
### Issue Description

After updating the @nativescript/core package on our application, we started noticing severely degraded performance on iOS - Android version has no performance issues. 

The application is super slow and sluggish when updating the UI, e.g. input takes 1-2 secs to register, navigation between pages takes 2-5 seconds to react and so on

We are using @nativescript/vue@2.9.3
Any version of @nativescript/core > 8.3.6 has the issue

### Environment

```yaml
OS: Windows 10 10.0.19044
CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
Shell: Not Found
node: 16.13.0
npm: 8.1.0
nativescript: Not Found

# android
java: javac 11
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: Not Found
cocoapods: Not Found
python: 3.8.2
python3: Not Found
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@nativescript/appversion": "~2.0.0",
  "@nativescript/core": "8.3.6",
  "@nativescript/firebase-analytics": "~2.5.2",
  "@nativescript/firebase-core": "~2.5.2",
  "@nativescript/firebase-crashlytics": "~2.5.2",
  "@nativescript/firebase-messaging": "~2.5.2",
  "@nativescript/firebase-remote-config": "~2.5.2",
  "@nativescript/local-notifications": "~6.0.0",
  "@nativescript/localize": "~5.0.4",
  "@nativescript/theme": "~3.0.2",
  "@nota/nativescript-accessibility-ext": "~7.0.3",
  "animate.css": "~4.1.1",
  "axios": "~0.23",
  "crypto-js": "~4.1.1",
  "jwt-decode": "~3.1.2",
  "moment": "~2.29.4",
  "nativescript-exit": "~1.0.1",
  "nativescript-oauth2": "~3.0.10",
  "nativescript-phone": "~3.0.3",
  "nativescript-rsa": "~1.2.0",
  "nativescript-vue": "~2.9.3",
  "net": "~1.0.2",
  "vuex": "~3.6.2"
},
"devDependencies": {
  "@babel/core": "~7.20.12",
  "@babel/plugin-proposal-class-properties": "~7.18.6",
  "@babel/preset-env": "~7.20.2",
  "@nativescript/android": "~8.4.0",
  "@nativescript/ios": "~8.4.1",
  "@nativescript/types": "~8.4.0",
  "@nativescript/webpack": "~5.0.12",
  "assert": "~2.0.0",
  "browserify-zlib": "~0.2.0",
  "buffer": "~6.0.3",
  "crypto-browserify": "~3.12.0",
  "https-browserify": "~1.0.0",
  "nativescript-vue-template-compiler": "~2.9.3",
  "os-browserify": "~0.3.0",
  "patch-package": "~6.5.1",
  "path-browserify": "~1.0.1",
  "stream-browserify": "~3.0.0",
  "stream-http": "~3.2.0",
  "tty-browserify": "~0.0.1",
  "typescript": "~4.9.4",
  "util": "~0.12.5",
  "vue": "^2.6.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
