### ISSUE TITLE
DPIs difference between Android and IOS

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#10187]
### Issue Description

I have sizing difference between IOS and Android! 

Android has some 5 DPIs more than android ! it is confusing because when loggin the `width` and the `height` is log same think but visually isn't the same!

is that the expected behavior ?
![Screenshot_1674944280](https://user-images.githubusercontent.com/18148534/215293619-a4d5b20b-33c1-4cdb-a19d-a25ce273a882.png)
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-01-29 at 02 18 02](https://user-images.githubusercontent.com/18148534/215293625-cc09be59-13ca-4cf8-b9dd-4e62b3a1d958.png)

### Environment

```yaml
OS: macOS 12.6.1
CPU: (10) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 16.16.0
npm: 8.17.0
nativescript: 8.4.0

# android
java: 18.0.1
ndk: Not Found
apis: 23, 30, 31, 32, 33
build_tools: 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1
system_images: 
  - android-33 | Google APIs ARM 64 v8a
  - android-33 | Google Play ARM 64 v8a

# ios
xcode: 14.1/14B47b
cocoapods: 1.11.3
python: 3.9.12
python3: 3.9.12
ruby: 3.1.2
platforms: 
  - DriverKit 22.1
  - iOS 16.1
  - macOS 13.0
  - tvOS 16.1
  - watchOS 9.1
```

### Dependencies

```json
"dependencies": {
  "@kefah/nativescript-otp": "^1.0.4",
  "@kefah/nativescript-uuid": "^1.0.1",
  "@nativescript-community/fonticon": "^3.0.0",
  "@nativescript-community/text": "^1.5.11",
  "@nativescript-community/ui-canvas": "^4.4.5",
  "@nativescript-community/ui-material-bottom-navigation": "^7.0.33",
  "@nativescript-community/ui-material-bottomnavigationbar": "^7.0.31",
  "@nativescript-community/ui-material-dialogs": "^7.0.31",
  "@nativescript-community/ui-material-tabs": "^7.0.31",
  "@nativescript-community/universal-links": "^3.0.0",
  "@nativescript/appversion": "^2.0.0",
  "@nativescript/background-http": "^6.0.0",
  "@nativescript/core": "^8.4.6",
  "@nativescript/datetimepicker": "^2.1.11",
  "@nativescript/firebase-auth": "^2.4.4",
  "@nativescript/firebase-core": "^2.4.4",
  "@nativescript/firebase-crashlytics": "^2.4.4",
  "@nativescript/firebase-messaging": "^2.4.4",
  "@nativescript/geolocation": "^8.1.0",
  "@nativescript/imagepicker": "^1.0.7",
  "@nativescript/iqkeyboardmanager": "^2.0.0",
  "@nativescript/local-notifications": "^6.0.0",
  "@nativescript/localize": "^5.0.4",
  "@nativescript/picker": "^4.0.2",
  "@nativescript/secure-storage": "^3.0.0",
  "@nativescript/social-share": "^2.2.1",
  "@nativescript/theme": "^3.0.2",
  "@nstudio/nativescript-cardview": "^2.0.1",
  "@nstudio/nativescript-checkbox": "^2.0.5",
  "@nstudio/nativescript-fancyalert": "^4.0.1",
  "@nstudio/nativescript-filterable-listpicker": "^3.0.1",
  "@nstudio/nativescript-loading-indicator": "^4.1.2",
  "@triniwiz/nativescript-star-ratings": "^2.0.3",
  "@triniwiz/nativescript-stripe": "^9.0.0-beta.1",
  "@triniwiz/nativescript-toasty": "^4.1.3",
  "@types/google-libphonenumber": "^7.4.23",
  "base-64": "^1.0.0",
  "build-url-ts": "^6.1.3",
  "crypto-js": "^4.1.1",
  "email-validator": "^2.0.4",
  "google-libphonenumber": "^3.2.29",
  "moment": "^2.29.4",
  "nativescript-feedback": "^2.0.0",
  "nativescript-intl": "^4.0.2",
  "nativescript-modal-datetimepicker": "^2.1.5",
  "nativescript-numeric-keyboard": "^5.0.2",
  "nativescript-phone": "^3.0.3",
  "nativescript-ui-autocomplete": "^14.2.1",
  "nativescript-ui-calendar": "^14.2.1",
  "nativescript-ui-listview": "^14.2.4",
  "sort-array": "^4.1.5",
  "url-parse": "^1.5.10",
  "utf8": "^3.0.0",
  "uuid": "^8.3.2"
},
"devDependencies": {
  "@nativescript/android": "8.4.0",
  "@nativescript/ios": "^8.4.1",
  "@nativescript/types": "^8.4.0",
  "@nativescript/webpack": "^5.0.13",
  "jscrambler-webpack-plugin": "^6.4.1",
  "typescript": "^4.9.4"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
