### ISSUE TITLE
ActionBar in iOS16

### ISSUE THREAD

**Issue by jorgeMoovein** [NativeScript/NativeScript#10222]
### Issue Description

I have an app in plain JavaScript for both Android and iOS, the same code is ok in Android, and it was ok in iOS 15, but on iOS16 the NavigationButton and ActionItem inside the ActionBar don't have the sames distance to the edge of the screen. 

ios15 - iphone 6s plus
![ios15](https://user-images.githubusercontent.com/60516864/221533870-30eddb7c-b90d-427a-abb4-c1aad24a2190.jpg)

ios16 - iphone 11 promax
![ios16](https://user-images.githubusercontent.com/60516864/221533925-db18b378-a05a-4468-ac48-bcbf959c5ee8.jpg)

Code: 
`<Page backgroundColor="#ffffff" backgroundSpanUnderStatusBar="true" loaded="pageLoaded" navigatingTo="onNavigatingTo" class="page"
    xmlns="http://www.nativescript.org/tns.xsd"
    xmlns:imovelControl="./Componentes/Imovel">`
   `<ActionBar title="Mensagem" id="action" class="action-bar" backgroundColor="#ffffff" color="#EF4832">
        <NavigationButton text="" android:icon="~/assets/images/actionbar/back@3x.png" tap="onNavigateBack"></NavigationButton>
        <ActionItem id="btnarquivar" visibility="visible" tap="onArquivar" text="Arquivar" ios.position="right"></ActionItem>
    </ActionBar>`

There's an opened issue that looks kinda related but is far away from the edge of the screen: 
[https://github.com/NativeScript/NativeScript/issues/9576]

### Environment

```yaml
OS: macOS 13.2.1
CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
Shell: /bin/zsh
node: 16.14.2
npm: 8.19.2
nativescript: 8.4.0

# android
java: 11.0.17
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.2/14C18
cocoapods: 1.11.3
python: 3.9.6
python3: 3.9.6
ruby: 2.7.6
platforms: 
  - DriverKit 22.2
  - iOS 16.2
  - macOS 13.1
  - tvOS 16.1
  - watchOS 9.1
```

### Dependencies

```json
"dependencies": {
  "@kefah/nativescript-google-maps": "~1.0.7",
  "@nativescript-community/ui-document-picker": "^1.1.12",
  "@nativescript/core": "~8.4.0",
  "@nativescript/datetimepicker": "~2.1.12",
  "@nativescript/firebase": "~11.1.3",
  "@nativescript/firebase-core": "~2.5.2",
  "@nativescript/geolocation": "~8.1.0",
  "@nativescript/imagepicker": "^1.0.9",
  "@nativescript/iqkeyboardmanager": "~2.1.1",
  "@nativescript/theme": "~3.0.2",
  "@triniwiz/nativescript-image-cache-it": "~7.3.0",
  "google-libphonenumber": "~3.2.32",
  "n7-google-places-autocomplete": "~1.0.11",
  "nativescript-carousel": "~7.0.1",
  "nativescript-drop-down": "~6.0.2",
  "nativescript-mediafilepicker": "~4.0.2",
  "nativescript-photoviewer": "~3.0.1",
  "nativescript-ui-calendar": "~14.2.1",
  "nativescript-ui-listview": "~14.2.4"
},
"devDependencies": {
  "@nativescript/android": "~8.4.0",
  "@nativescript/ios": "~8.4.1",
  "@nativescript/webpack": "~5.0.13"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
