### ISSUE TITLE
Error with link and alias the installed python3

### ISSUE THREAD

**Issue by jhonjoffre** [NativeScript/NativeScript#10237]
### Issue Description

After install and follow the documentation available at : https://docs.nativescript.org/environment-setup.html#macos-ios

I've stumble with an issue: with the line:

link and alias the installed python3
version to be available to XCode as python
>sudo ln -s $(which python3) /usr/local/bin/python 

If I use the command this is the terminal response:

>XXX@XXXX-Mac-mini ~ % sudo ln -s $(which python3) /usr/local/bin/python
>Password:
>ln: /usr/local/bin/python: No such file or directory

Digging into the path I've found that the folder referred in the documentation /local/ does not exist at all, python is located at /usr/bin/python

I've tried 
Anyway to work around or fix the path?

### Reproduction

>XXX@XXXX-Mac-mini ~ % sudo ln -s $(which python3) /usr/local/bin/python
>Password:
>ln: /usr/local/bin/python: No such file or directory

### Relevant log output (if applicable)

```shell
XXXXXXX@Jhons-Mac-mini ~ % ns doctor
✔ Getting environment information 

There seem to be issues with your configuration.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.4.0 version and is up to date.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Xcode version 14.2.0 satisfies minimum required version 10.
✖ WARNING: Couldn't retrieve installed python packages. 
 We cannot verify your python installation is setup correctly. Please, make sure you have both 'python' and 'pip' installed.
Error while validating Python packages. Error is: Command failed: python -c "import six"
/bin/sh: python: command not found
 

✖ WARNING: The Python 'six' package not found. 
 This package is required by the Debugger library (LLDB) for iOS. You can install it by first making sure you have pip installed and then running 'pip install six' from the terminal. 

Your environment is not configured properly and you will not be able to execute local builds.
Verify that your environment is configured according to the system requirements described at
https://docs.nativescript.org/environment-setup.html.
jhonjoffre@Jhons-Mac-mini ~ % sudo ln -s $(which python3) /usr/local/bin/python
Password:
ln: /usr/local/bin/python: No such file or directory
XXXXXX@Jhons-Mac-mini ~ % sudo ln -s $(which python3) /usr/bin/python 
ln: /usr/bin/python: Operation not permitted
XXXXXX@Jhons-Mac-mini ~ % python --version
Python 3.9.6
XXXXXX@Jhons-Mac-mini ~ % pip --version 
pip 23.0.1 from /Users/XXXXXX/Library/Python/3.9/lib/python/site-packages/pip (python 3.9)
XXXXXX@Jhons-Mac-mini ~ %
```

### Environment

```yaml
OS: macOS 13.2.1
CPU: (8) arm64 Apple M1
Shell: /bin/zsh
node: 18.15.0
npm: 9.5.0
nativescript: 8.4.0

# android
java: 11.0.18
ndk: Not Found
apis: 30, 31, 33, 33, 33
build_tools: 33.0.2
system_images: 
  - android-33-ext4 | Google Play ARM 64 v8a
  - android-33-ext4 | Google Play Intel x86_64 Atom
  - android-33-ext5 | Google Play ARM 64 v8a
  - android-33-ext5 | Google Play Intel x86_64 Atom
  - android-33 | Android TV ARM 64 v8a
  - android-33 | Android TV Intel x86 Atom
  - android-33 | Google TV ARM 64 v8a
  - android-33 | Google TV Intel x86 Atom
  - android-33 | Google APIs ARM 64 v8a
  - android-33 | Google APIs Intel x86_64 Atom
  - android-33 | Google Play ARM 64 v8a
  - android-33 | Google Play Intel x86_64 Atom
  - android-TiramisuPrivacySandbox | Google Play ARM 64 v8a
  - android-TiramisuPrivacySandbox | Google Play Intel x86_64 Atom

# ios
xcode: 14.2/14C18
cocoapods: 1.12.0
python: Not Found
python3: 3.9.6
ruby: 2.7.7
platforms: 
  - DriverKit 22.2
  - iOS 16.2
  - macOS 13.1
  - tvOS 16.1
  - watchOS 9.1
```

### Dependencies

```json
"dependencies": {
  "formidable": "^3.2.5",
  "nativescript": "^8.4.0"
},
"devDependencies": {}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
