### ISSUE TITLE
NS 8.4+: ScrollView has no scroll bar anymore on Android

### ISSUE THREAD

**Issue by felixkrautschuk** [NativeScript/NativeScript#10234]
### Issue Description

After upgrading @nativescript/core from 8.3.6 to 8.4.0, ScrollViews on Android have no scroll bar anymore.

```
<Page navigatingTo="onNavigatingTo">
    <ActionBar title="My App"/>

    <ScrollView>
        <GridLayout rows="*" padding="12">
            <Label text="{{ text }}" fontSize="16" textWrap="true"/>
        </GridLayout>
    </ScrollView>
</Page>
```

I already tried adding the following to the loaded event of the ScrollView:

```
export function onScrollViewLoaded(args) {
  if(isAndroid) {
    args.object.android.setVerticalScrollBarEnabled(true);
    args.object.android.setScrollbarFadingEnabled(true);
  }
}
```

But that did not help.

### Reproduction

[ns-scrollview-android.zip](https://github.com/NativeScript/NativeScript/files/10956073/ns-scrollview-android.zip)

### Relevant log output (if applicable)

```shell
-
```

### Environment

```yaml
OS: macOS 13.2.1
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Shell: /bin/zsh
node: 16.17.0
npm: 8.19.3
nativescript: 8.4.0

# android
java: 11.0.11
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.2/14C18
cocoapods: 1.11.3
python: 2.7.18
python3: 3.10.9
ruby: 2.6.10
platforms: 
  - DriverKit 22.2
  - iOS 16.2
  - macOS 13.1
  - tvOS 16.1
  - watchOS 9.1
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "^8.4.7",
  "@nativescript/theme": "~3.0.2"
},
"devDependencies": {
  "@nativescript/android": "8.4.0",
  "@nativescript/ios": "8.4.1",
  "@nativescript/webpack": "~5.0.12"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
