### ISSUE TITLE
TextField removes last character, TextView works ok instead.

### ISSUE THREAD

**Issue by subjekt-iv** [NativeScript/NativeScript#10280]
### Issue Description

When typing into a TextField (credentials in this case) both username and password text fields display correctly the characters but when I press the login button to, which triggers the login request method, the last character of both the strings is cut.

### Environment

```yaml
OS: macOS 13.0
CPU: (8) x64 Apple M2
Shell: /bin/bash
node: 14.18.0
npm: 6.14.15
nativescript: 8.5.3

# android
java: 11.0.15
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.3/14E222b
cocoapods: 1.12.0
python: 3.9.9
python3: 3.9.9
ruby: 2.7.8
platforms: 
  - DriverKit 22.4
  - iOS 16.4
  - macOS 13.3
  - tvOS 16.4
  - watchOS 9.4
```

### Dependencies

```json
"dependencies": {
  "@bradmartin/nativescript-urlhandler": "^2.0.1",
  "@nativescript/appversion": "^2.0.0",
  "@nativescript/background-http": "^6.0.0",
  "@nativescript/camera": "^5.0.15",
  "@nativescript/core": "~8.5.2",
  "@nativescript/datetimepicker": "^2.1.13",
  "@nativescript/email": "^2.0.5",
  "@nativescript/firebase-core": "^3.0.0",
  "@nativescript/firebase-messaging": "^3.0.0",
  "@nativescript/imagepicker": "^1.0.10",
  "@nativescript/iqkeyboardmanager": "^2.1.1",
  "@nativescript/theme": "^2.2.1",
  "@triniwiz/nativescript-socketio": "^4.0.3",
  "@triniwiz/nativescript-toasty": "^4.1.3",
  "@vue/devtools": "^5.3.3",
  "cocoapods": "^0.0.0",
  "moment": "^2.29.1",
  "n7-google-places-autocomplete": "^1.0.11",
  "nativescript-appversion": "^1.4.4",
  "nativescript-barcodescanner": "^4.1.2",
  "nativescript-clipboard": "^2.1.1",
  "nativescript-toasty": "^3.0.0-alpha.2",
  "nativescript-vue": "^2.9.3",
  "nativescript-vue-devtools": "^1.4.0",
  "nativescript-vue-shadow-ns-7": "^10.1.0",
  "vuex": "^3.3.0",
  "xcode": "^3.0.1"
},
"devDependencies": {
  "@babel/core": "^7.0.0",
  "@babel/preset-env": "^7.0.0",
  "@nativescript/android": "~8.5.0",
  "@nativescript/ios": "8.5.1",
  "@nativescript/types": "~8.5.0",
  "@nativescript/webpack": "~5.0.0",
  "@types/node": "^18.0.3",
  "babel-loader": "^8.1.0",
  "nativescript-vue-template-compiler": "^2.6.0",
  "prettier": "^2.8.7",
  "sass": "~1.49.9",
  "typescript": "~4.8.4",
  "vue-loader": "^15.9.1"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
