### ISSUE TITLE
Light/Darkmode does not work when manually setting view background-color (declarative and procedural)

### ISSUE THREAD

**Issue by cjohn001** [NativeScript/NativeScript#10301]
Please do not spent time in analyzing the issue for the moment. I think I found the problem but I need to verify it first. Seems like I have to add .ns-root in CSS before each class definition in order for light/dark mode changes to be reflected. However, I am not sure yet if this is also responsible for the described bug. I will provide an update as soon I were able to check it.

### Issue Description

Hello together,
I am currently trying to get light/darkmode working with nativescript theme without the need to restart the application on mode switch (which I am currently doing as a workaround to the problem I am experiencing).

The problem is that once the color of a view was set manually, the CSS is not applied anymore to the respective view if a light/darkmode switch happens.

I tried it out in several ways no. Procedural approach with attribute directives as described here: https://github.com/NativeScript/angular/issues/116

procedural with reaction to touch events, should be same as attribute directive approach

and declarative with new TouchManager. I assume internally it does the same I am doing.

Only option to get it working is define all animations in CSS directly

### Further Comment
Independent of the previously mentioned behaviour, I am also seeing issues when the app is initially started in dark mode. Than switching to light mode does not work for most page elements.

### Reproduction

Please not, I tried with my current app with the most recent packages and with a hello-world demo app, therefore I provide content below twice.

```yaml
OS: macOS 13.4
CPU: (10) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 18.12.1
npm: 8.19.2
nativescript: 8.5.3

# android
java: 11.0.18
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.3.1/14E300c
cocoapods: 1.12.0
python: 3.11.2
python3: 3.11.2
ruby: 2.7.7
platforms: 
  - DriverKit 22.4
  - iOS 16.4
  - macOS 13.3
  - tvOS 16.4
  - watchOS 9.4
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "16.0.4",
  "@angular/common": "16.0.4",
  "@angular/compiler": "16.0.4",
  "@angular/core": "16.0.4",
  "@angular/forms": "16.0.4",
  "@angular/platform-browser": "16.0.4",
  "@angular/platform-browser-dynamic": "16.0.4",
  "@angular/router": "16.0.4",
  "@apollo/client": "3.7.15",
  "@mnd/external-web-view": "file:../mnd-plugins/dist/packages/external-web-view/mnd-external-web-view-1.0.0.tgz",
  "@nativescript/angular": "16.0.0",
  "@nativescript/core": "8.5.3",
  "@nativescript/iqkeyboardmanager": "2.1.1",
  "@nativescript/localize": "5.1.0",
  "@nativescript/mlkit-barcode-scanning": "2.0.0",
  "@nativescript/mlkit-core": "2.0.0",
  "@nativescript/secure-storage": "3.0.0",
  "@nativescript/theme": "3.0.2",
  "@nativescript/ui-charts": "0.2.4",
  "apollo-angular": "5.0.0",
  "apollo3-cache-persist": "0.14.1",
  "d3-ease": "3.0.1",
  "graphql": "16.6.0",
  "graphql-tag": "2.12.6",
  "intl": "1.2.5",
  "moment": "2.29.4",
  "nativescript-health-data": "file:../mnd-custom-plugins/nativescript-health-data/publish/package/nativescript-health-data-2.0.0.tgz",
  "nativescript-oauth2-ext": "file:../mnd-custom-plugins/nativescript-oauth2-ext/publish/package/nativescript-oauth2-ext-3.0.1.tgz",
  "nativescript-sqlite": "2.8.6",
  "nativescript-ui-calendar": "15.2.3",
  "nativescript-ui-gauge": "15.2.3",
  "rxjs": "7.8.1",
  "uuid": "9.0.0",
  "zone.js": "0.13.0"
},
"devDependencies": {
  "@angular-devkit/build-angular": "16.0.4",
  "@angular/compiler-cli": "16.0.4",
  "@graphql-codegen/cli": "4.0.1",
  "@graphql-codegen/fragment-matcher": "5.0.0",
  "@graphql-codegen/introspection": "4.0.0",
  "@graphql-codegen/typescript": "4.0.0",
  "@graphql-codegen/typescript-apollo-angular": "3.5.6",
  "@graphql-codegen/typescript-operations": "4.0.0",
  "@nativescript/android": "8.5.0",
  "@nativescript/ios": "8.5.2",
  "@nativescript/types": "8.5.0",
  "@nativescript/webpack": "5.0.14",
  "@ngtools/webpack": "16.0.4",
  "@types/d3-ease": "3.0.0",
  "@types/intl": "1.2.0",
  "@types/node": "20.2.5",
  "@types/uuid": "9.0.1",
  "keycloak-request-token": "0.1.0",
  "rimraf": "5.0.1",
  "sass": "1.62.1",
  "ts-node": "10.9.1",
  "typescript": "4.9.5"
}
```

```yaml
OS: macOS 13.4
CPU: (10) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 18.12.1
npm: 8.19.2
nativescript: 8.5.3

# android
java: 11.0.18
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.3.1/14E300c
cocoapods: 1.12.0
python: 3.11.2
python3: 3.11.2
ruby: 2.7.7
platforms: 
  - DriverKit 22.4
  - iOS 16.4
  - macOS 13.3
  - tvOS 16.4
  - watchOS 9.4
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~15.2.0",
  "@angular/common": "~15.2.0",
  "@angular/compiler": "~15.2.0",
  "@angular/core": "~15.2.0",
  "@angular/forms": "~15.2.0",
  "@angular/platform-browser": "~15.2.0",
  "@angular/platform-browser-dynamic": "~15.2.0",
  "@angular/router": "~15.2.0",
  "@nativescript/angular": "^15.0.0",
  "@nativescript/core": "~8.5.0",
  "@nativescript/theme": "~3.0.2",
  "rxjs": "~7.6.0",
  "zone.js": "~0.13.0"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~15.2.0",
  "@angular/compiler-cli": "~15.2.0",
  "@nativescript/ios": "8.5.2",
  "@nativescript/types": "~8.5.0",
  "@nativescript/webpack": "~5.0.14",
  "@ngtools/webpack": "~15.2.0",
  "typescript": "~4.8.4"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
