### ISSUE TITLE
Worker broken since >=8.5.4 if globals imported

### ISSUE THREAD

**Issue by KG3RK3N** [NativeScript/NativeScript#10334]
### Issue Description

When I start a worker that includes `require("@nativescript/core/globals");` then it thows a runtime exception:

```
ReferenceError: __decorate is not defined
    at file:///data/data/io.flynex.connect.v5/files/app/vendor.js:23784:5
    at ./node_modules/@nativescript/core/ui/builder/xml2ui.js (file:///data/data/io.flynex.connect.v5/files/app/vendor.js:23791:3)
    at __webpack_require__ (file:///data/data/io.flynex.connect.v5/files/app/src_app_workers_exif-metadata_worker_ts-_package_json.js:268:42)
    at ./node_modules/@nativescript/core/ui/builder/index.js (file:///data/data/io.flynex.connect.v5/files/app/vendor.js:23190:65)
    at __webpack_require__ (file:///data/data/io.flynex.connect.v5/files/app/src_app_workers_exif-metadata_worker_ts-_package_json.js:268:42)
    at ./node_modules/@nativescript/core/application/application-common.js (file:///data/data/io.flynex.connect.v5/files/app/vendor.js:9271:69)
```

If I downgrade to v8.5.3 its working without issues.
Seems that the changes on the globals/index.ts from #10315 are the problem. But a quick remove of the line is not enough, than the application dosn't start anymore because the module not initialized early enough.

### Reproduction

1. Create demo application
2. Add worker with some sample code
3. Add import `require("@nativescript/core/globals");` to the worker
4. Run demo app
5. Start worker => Exception

### Environment

```yaml
OS: Windows 10 10.0.19045
CPU: (16) x64 AMD Ryzen 7 1700X Eight-Core Processor
Shell: Not Found
node: 16.16.0
npm: 8.19.0
nativescript: Not Found

# android
java: Not Found
ndk: Not Found
apis: 22, 25, 26, 27, 28, 29, 30, 31, 33, 33
build_tools: 27.0.3, 28.0.2, 28.0.3, 29.0.1, 29.0.2, 30.0.0, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 33.0.2
system_images:
  - android-22 | Google APIs Intel x86 Atom
  - android-27 | Google APIs Intel x86 Atom
  - android-27 | Google Play Intel x86 Atom
  - android-28 | Google APIs Intel x86 Atom
  - android-29 | Intel x86 Atom
  - android-29 | Google APIs Intel x86 Atom
  - android-30 | Google APIs Intel x86 Atom
  - android-31 | Google APIs Intel x86_64 Atom

# ios
xcode: Not Found
cocoapods: Not Found
python: Not Found
python3: Not Found
ruby: 2.5.1
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~15.2.0",
  "@angular/common": "~15.2.0",
  "@angular/compiler": "~15.2.0",
  "@angular/core": "~15.2.0",
  "@angular/forms": "~15.2.0",
  "@angular/platform-browser": "~15.2.0",
  "@angular/platform-browser-dynamic": "~15.2.0",
  "@angular/router": "~15.2.0",
  "@danvick/ngx-translate-nativescript-loader": "^3.0.1",
  "@nativescript-community/perms": "^2.3.0",
  "@nativescript-community/ui-checkbox": "^2.0.9",
  "@nativescript-community/ui-material-bottom-navigation": "^7.1.3",
  "@nativescript-community/ui-material-bottomsheet": "^7.1.3",
  "@nativescript-community/ui-material-snackbar": "^7.1.3",
  "@nativescript-community/ui-pulltorefresh": "^2.5.3",
  "@nativescript/angular": "~15.2.0",
  "@nativescript/appversion": "^2.0.0",
  "@nativescript/core": "<=8.5.3",
  "@nativescript/datetimepicker": "^2.1.13",
  "@nativescript/geolocation": "^8.2.0",
  "@nativescript/imagepicker": "^2.0.2",
  "@nativescript/picker": "^4.1.0",
  "@nativescript/theme": "~3.0.2",
  "@ngx-translate/core": "^14.0.0",
  "@nstudio/nativescript-loading-indicator": "^4.2.0",
  "@triniwiz/nativescript-couchbase": "^1.4.0",
  "@triniwiz/nativescript-downloader": "^3.0.1",
  "@triniwiz/nativescript-toasty": "^4.1.3",
  "@triniwiz/nativescript-tooltip": "^3.0.0",
  "@turf/turf": "^6.5.0",
  "@types/luxon": "^1.27.1",
  "@types/mime": "^3.0.1",
  "@types/semver": "^7.3.13",
  "geojson": "^0.5.0",
  "loglevel": "^1.8.1",
  "luxon": "<2.0.0",
  "mime": "^3.0.0",
  "nativescript-android-sensors": "^2.1.0",
  "nativescript-intl": "^4.0.2",
  "nativescript-ui-listview": "^15.2.3",
  "rxjs": "^7.5.7",
  "semver": "^7.5.3",
  "zone.js": "~0.13.0"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~15.2.0",
  "@angular/compiler-cli": "~15.2.0",
  "@nativescript/android": "8.5.0",
  "@nativescript/types": "~8.5.0",
  "@nativescript/webpack": "~5.0.16",
  "@ngtools/webpack": "~15.2.0",
  "@types/lodash": "^4.14.187",
  "husky": "^8.0.1",
  "lint-staged": "^13.2.3",
  "properties-reader": "^2.2.0",
  "resolve-package-path": "^4.0.3",
  "tslint": "^6.1.3",
  "typescript": "~4.8.4"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
