### ISSUE TITLE
[svelte] @nativescript/webpack dependencies are not installed by default

### ISSUE THREAD

**Issue by lnfel** [NativeScript/NativeScript#10358]
### Issue Description

`@nativescript/webpack` is missing dependencies when running `ns run android`. First it says it is missing `acorn-stage3`, guess I should add it manually. Next run `ns run android again`, says missing `acorn-class-fields`. Added another package then run `ns android` again then it just keep on yelling at me that a certain package is missing. This happens whether the dependencies are installed either with `npm` or `pnpm`. I did run `ns clean` and re-installed the dependicies and even updated everything to latest version but the result is still the same. It would be a pain for developers to install the dependencies manually.

Svelte Native has not been maintained for quite a while, maybe there is another way to introduce nativescript on an existing svelte project without relying on Svelte Native template. I would love to hear it.

### Reproduction

Following the steps in creating svelte with nativescript at https://docs.nativescript.org/tutorial/svelte.html
1. Setup environment with [MacOS + Android](https://docs.nativescript.org/environment-setup.html#macos-android)
2. Create new svelte native application:
```sh
ns create example-app --svelte
```
3. Run the application
```sh
ns run android
```

> Searching for devices...
> Preparing project...
> Error: Cannot find module 'some @nativescript/webpack dependency'
> Require stack:
> path-to-node_modules/@nativescript/webpack/dist/bin/index.js
> ...
> code: 'MODULE_NOT_FOUND',

### Relevant log output (if applicable)

```shell
ns doctor android
✔ Getting environment information 

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.5.3 version and is up to date.
✔ Component @nativescript/core has 8.5.9 version and is up to date.
✔ Component @nativescript/android has 8.5.1 version and is up to date.
```

### Environment

```yaml
OS: macOS 10.15.7
CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
Shell: /bin/zsh
node: 18.14.2
npm: 9.5.0
nativescript: Not Found

# android
java: 19.0.1
ndk: Not Found
apis: 31, 32, 33
build_tools: 29.0.2, 30.0.3, 33.0.1
system_images: 
  - android-29 | Google Play Intel x86 Atom
  - android-33 | Google APIs Intel x86 Atom_64

# ios
xcode: 12.4/12D4e
cocoapods: 1.11.3
python: 2.7.16
python3: 3.11.2
ruby: 3.1.2
platforms: 
  - iOS 14.4
  - DriverKit 20.2
  - macOS 11.1
  - tvOS 14.3
  - watchOS 7.2
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "~8.5.9",
  "@nativescript/theme": "~3.0.2",
  "svelte-native": "~1.0.6"
},
"devDependencies": {
  "@nativescript/android": "8.5.1",
  "@nativescript/types": "~8.5.0",
  "@nativescript/webpack": "^5.0.17",
  "svelte": "~4.1.2",
  "svelte-loader": "^3.1.9",
  "svelte-native-preprocessor": "^1.0.0",
  "svelte-preprocess": "^5.0.4",
  "typescript": "~5.1.6"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
