### ISSUE TITLE
Android Preload TabView Template

### ISSUE THREAD

**Issue by jorgeMoovein** [NativeScript/NativeScript#10362]
### Issue Description

I have a TabView with 5 tabs created with the default {N} Tabs template.
When I open the app (lets consider first tab is tabIndex[0]), in Android the tabIndex[1] onPageLoaded/onNavigatingTo is triggered, and then when i tap tabIndex[1] the functions are not triggered but the tabIndex[2] are. 

I've read the documentation about the androidOffscreenTabLimit in TabView, and set it to "0" in xml without any results, then with further investigation in the node_modules/@nativescript/core/ui/tab-view/index.android.js line 440: 

`const offsideItems = this.androidTabsPosition === 'top' ? this.androidOffscreenTabLimit : 1;`

My TabView is in bottom, but i want the app not to preload any page/tab. 

To test, i've set the `this.androidOffscreenTabLimit : 1` to `this.androidOffscreenTabLimit : 0` and it works (as i expected, only load current tab). 

I tried to set it my main-page.ts but it didn't work. 

I don't actually know if this is a bug or it's like this for some reason. 

Temporarily i solved the issue by editing the node_modules. 

### Environment

```yaml
OS: macOS 13.4.1
CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
Shell: /bin/zsh
node: 18.15.0
npm: 9.6.3
nativescript: 8.5.3

# android
java: 11.0.18
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.3.1/14E300c
cocoapods: 1.11.3
python: 3.9.6
python3: 3.11.3
ruby: 2.7.8
platforms: 
  - DriverKit 22.4
  - iOS 16.4
  - macOS 13.3
  - tvOS 16.4
  - watchOS 9.4
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "~8.5.0",
  "@nativescript/iqkeyboardmanager": "^2.1.1",
  "@nativescript/theme": "~3.0.2",
  "@nstudio/nativescript-carousel": "^8.0.3",
  "@triniwiz/nativescript-image-cache-it": "^7.3.0"
},
"devDependencies": {
  "@nativescript/android": "8.5.0",
  "@nativescript/ios": "8.5.2",
  "@nativescript/types": "~8.5.0",
  "@nativescript/webpack": "~5.0.14",
  "typescript": "~4.8.4"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
