### ISSUE TITLE
Android (33) Http.getImage() returns empty ImageSource

### ISSUE THREAD

**Issue by RGBvision** [NativeScript/NativeScript#10366]
### Issue Description

`Http.getImage(url).then( r => console.log(r));`
returns
`
{
  "android": {}
}
`

### Environment

```yaml
OS: Windows 10 10.0.22621
CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Shell: Not Found
node: 19.8.1
npm: 9.6.2
nativescript: Not Found

# android
java: Not Found
ndk: Not Found
apis: 31, 32, 33
build_tools: 28.0.3, 29.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1
system_images:
  - android-33 | Google APIs Intel x86_64 Atom
  - android-33 | Google Play Intel x86 Atom_64

# ios
xcode: Not Found
cocoapods: Not Found
python: Not Found
python3: Not Found
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@nativescript-community/gps": "3.1.10",
  "@nativescript-community/https": "4.1.1",
  "@nativescript-community/ui-barcodeview": "3.6.1",
  "@nativescript-community/ui-image": "4.3.11",
  "@nativescript-community/ui-mapbox": "6.2.19",
  "@nativescript-community/ui-pager": "14.1.6",
  "@nativescript-community/ui-pulltorefresh": "2.5.3",
  "@nativescript-community/ui-webview": "1.4.9",
  "@nativescript/appsync": "3.0.1",
  "@nativescript/camera": "5.0.15",
  "@nativescript/core": "8.5.9",
  "@nativescript/firebase-core": "2.5.2",
  "@nativescript/firebase-messaging": "2.5.2",
  "@nativescript/imagepicker": "2.0.2",
  "@nativescript/localize": "5.2.0",
  "@nativescript/pdf": "1.0.1",
  "@nativescript/theme": "3.0.2",
  "@nstudio/nativescript-floatingactionbutton": "3.0.4",
  "@triniwiz/nativescript-image-zoom": "4.2.0",
  "@triniwiz/nativescript-toasty": "4.1.3",
  "libphonenumber-js": "1.10.41",
  "moment": "2.29.4",
  "nativescript-dna-deviceinfo": "3.7.3",
  "nativescript-imagecropper": "4.0.3",
  "nativescript-intl": "4.0.2",
  "nativescript-permissions": "1.3.12",
  "nativescript-ripple": "4.0.3",
  "nativescript-windowed-modal": "7.0.0",
  "url": "0.11.1"
},
"devDependencies": {
  "@nativescript/android": "8.5.1",
  "@nativescript/ios": "8.5.2",
  "@nativescript/types": "8.5.0",
  "@nativescript/webpack": "5.0.17",
  "sass": "1.65.1",
  "util": "0.12.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
