### ISSUE TITLE
`requestAnimationFrame` bug

### ISSUE THREAD

**Issue by bigmistqke** [NativeScript/NativeScript#10363]
### Issue Description

In a nativescript + dominative + solid-js project, the app crashes in the android emulator when doing 
```ts 
const loop = () => requestAnimationFrame(loop); 
loop()
```

I could trace the bug to `@nativescript/core/fps-meter/fps-native.android.js`:
If I force `FPSCallback.nativeFramesSupported` to false with 
```ts
_isNativeFramesSupported() {
  return false
}
```
the bug dissapears, so I assume it has something to do with `global.__postFrameCallback`.

### Reproduction

https://github.com/bigmistqke/nativescript-raf-bug

- yarn install
- tns run android

### Environment

```yaml
OS: macOS 13.3.1
CPU: (8) arm64 Apple M1
Shell: /bin/zsh
node: 18.12.1
npm: 8.19.2
nativescript: 8.5.3

# android
java: 11.0.20
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.2/14C18
cocoapods: Not Found
python: 2.7.18
python3: 3.11.1
ruby: 2.6.10
platforms: 
  - DriverKit 22.2
  - iOS 16.2
  - macOS 13.1
  - tvOS 16.1
  - watchOS 9.1
```

### Dependencies

```json
"dependencies": {
  "@nativescript-community/solid-js": "^0.0.4-alpha.4",
  "@nativescript-community/ui-collectionview": "^5.1.8",
  "@nativescript/core": "~8.5.9",
  "dominative": "^0.0.9-alpha.2",
  "prettier": "^3.0.1",
  "solid-js": "^1.7.11",
  "solid-navigation": "^1.0.0-alpha.7",
  "three": "^0.155.0",
  "undom-ng": "^1.0.10"
},
"devDependencies": {
  "@babel/core": "^7.22.10",
  "@babel/preset-env": "^7.20.2",
  "@babel/preset-typescript": "7.22.5",
  "@nativescript-dom/core-types": "^1.0.26",
  "@nativescript-dom/solidjs-types": "^1.0.11",
  "@nativescript/android": "8.5.1",
  "@nativescript/ios": "8.5.2",
  "@nativescript/webpack": "~5.0.17",
  "@types/three": "^0.155.0",
  "babel": "^6.23.0",
  "babel-loader": "^9.1.3",
  "babel-preset-solid": "^1.7.7",
  "patch-package": "^8.0.0",
  "solid-refresh": "^0.5.3",
  "typescript": "4.9.4"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
