### ISSUE TITLE
Embedded iOS App crashes on Launch

### ISSUE THREAD

**Issue by ahosamanedinesh** [NativeScript/NativeScript#10385]
### Issue Description

We are embedding the NativeScript into native iOS. The app crashes on launch with the below exception:
`NativeScript encountered a fatal error: Uncaught SyntaxError: Unexpected token '{'`

### Reproduction

1.`'ns prepare ios'`
2. Copy the app folder to Xcode project path
3. Run the iOS app

### Relevant log output (if applicable)

```shell
***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught SyntaxError: Unexpected token '{'
 at 
	require(:1:137)
	at (file:///i360/runtime.js:149:28)
	at (file:///i360/runtime.js:67:40)
	at (file:///i360/runtime.js:66:67)
	at (file:///i360/runtime.js:113:22)
	at (file:///i360/bundle.js:10035:47)
	at (file:///i360/bundle.js:10040:3)
	at require(:1:137)
```

### Environment

```yaml
OS: macOS 13.5
CPU: (10) arm64 Apple M2 Pro
Shell: /bin/zsh
node: 20.7.0
npm: 10.1.0
nativescript: 8.5.3

# android
java: 11.0.18
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 15.0/15A240d
cocoapods: 1.12.0
python: 3.10.4
python3: 3.10.4
ruby: 2.7.7
platforms: 
  - DriverKit 23.0
  - iOS 17.0
  - macOS 14.0
  - tvOS 17.0
  - watchOS 10.0
```

### Dependencies

```json
"dependencies": {  
"@nativescript-community/ui-chart": "^1.2.26",
  "@nativescript/angular": "^16.0.0",
  "@nativescript/core": "8.5.9",
  "@nativescript/zone-js": "^3.0.4"
},
"devDependencies": {
  "@nativescript/android": "8.5.0",
  "@nativescript/ios": "~8.5.2",
  "@nativescript/nx": "^16.5.2",
  "@nativescript/types": "~8.5.0",
  "@nativescript/webpack": "~5.0.17"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
