### ISSUE TITLE
IOS layout bug 

### ISSUE THREAD

**Issue by kkhalilov** [NativeScript/NativeScript#10398]
### Issue Description

The example below shows 3 variants (in zip file).
1 - if you just wait for the loading to complete and be at that moment on the page where the content is being rendered, then everything is displayed correctly
2 - if at the moment before the content is rendered, go to another page, the content will break
3- if you immediately go to another page and wait until the content is loaded on the previous one, then the content looks normal

BUG: If you go to another page at the moment when the content starts to render, it will break the layout 

This only happens if the content is wrapped in a ScrollView

Template structure (nativescript-vue)
```
<Page>
     <GridLayout>
       <ScrollView>
         <StackLayout>
             ....Content...
         </StackLayout>
       </ScrollView>
     </GridLayout>
   </Page>
```

Item structure 

```
<GridLayout columns="76, *">
    <StackLayout col="0"></StackLayout>
    <StackLayout col="1"></StackLayout>
  </GridLayout>
```

[2023-09-06_20.20.244.mov.zip](https://github.com/NativeScript/NativeScript/files/12841924/2023-09-06_20.20.244.mov.zip)

### Environment

```yaml
OS: macOS 13.3.1
CPU: (10) x64 Apple M1 Pro
Shell: /bin/zsh
node: 15.8.0
npm: 7.5.1
nativescript: 8.5.3

# android
java: 11.0.18
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.2/14C18
cocoapods: 1.12.1
python: 2.7.18
python3: 3.9.10
ruby: 2.7.8
platforms: 
  - DriverKit 22.2
  - iOS 16.2
  - macOS 13.1
  - tvOS 16.1
  - watchOS 9.1
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "^8.5.9",
  "@nativescript/theme": "~3.0.2",
  "nativescript-vue": "~2.9.3"
},
"devDependencies": {
  "@nativescript/android": "8.5.0",
  "@nativescript/ios": "8.5.2",
  "@nativescript/webpack": "~5.0.14",
  "nativescript-vue-template-compiler": "~2.9.3"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
