### ISSUE TITLE
template path option broken in 8.6.0

### ISSUE THREAD

**Issue by Mau04** [NativeScript/NativeScript#10412]
### Issue Description

When I run `ns create` with a local template (`ns create "App" --appid "appId" --template "./template-master-detail"`), it throws the following error: `Error: DirFetcher requires either a tree or an Arborist constructor to pack`.
It works with a package name `ns create "App" --appid "appId" --template "@nativescript/template-master-detail"`.

### Reproduction

1. run `npm i -g nativescript@8.6.0`
2. download a template (e.g. https://github.com/NativeScript/nativescript-app-templates/tree/main/packages/template-master-detail) to your working directory
3. try to create an app from the template with: `ns create "App" --appid "appId" --template "./template-master-detail"`
4. it throws the error: `Error: DirFetcher requires either a tree or an Arborist constructor to pack`

If you replace the nativescript version with 8.5.3, it works as expected.

### Environment

```yaml
OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
CPU: (5) x64 unknown
Shell: /bin/bash
node: 18.13.0
npm: 8.19.3
nativescript: 8.6.0

 

# android
java: 17.0.8.1
ndk: Not Found
apis: 33
build_tools: 33.0.2
system_images: Not Found

 

# ios
xcode: Not Found
cocoapods: Not Found
python: 3.10.12
python3: 3.10.12
ruby: 3.2.1
platforms: Not Found
```

 

### Dependencies

 

```json
"dependencies": {},
"devDependencies": {}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
