### ISSUE TITLE
Using FileSystem getEntities returns only folders inside on android (Expected files)

### ISSUE THREAD

**Issue by armespavong** [NativeScript/NativeScript#10416]
### Issue Description

I'm using getEntities with Folder (FileSystemEntity) on android. In this folder, there are folders and files inside, but getEntities returns only folders.

### Reproduction

Tries

```
const folder: any = knownFolders.documents();
folder.getEntities().then((entities: FileSystemEntity[]) => {
        console.log(entities);
});
```

### Environment

```yaml
OS: macOS 14.0
CPU: (8) arm64 Apple M1
Shell: /bin/zsh
node: 18.18.2
npm: 10.2.1
nativescript: 8.6.0

# android
java: 17.0.6
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 15.0/15A240d
cocoapods: 1.13.0
python: 3.11.4
python3: 3.11.4
ruby: 2.6.10
platforms: 
  - DriverKit 23.0
  - iOS 17.0
  - macOS 14.0
  - tvOS 17.0
  - watchOS 10.0
```

### Dependencies

```json
"dependencies": {
  "@master.technology/permissions": "^2.0.1",
  "@nativescript-community/perms": "^2.3.0",
  "@nativescript-community/ui-document-picker": "^1.1.12",
  "@nativescript/core": "^8.6.0",
  "@prabudevarrajan/filepicker": "^2.0.0",
  "dayjs": "^1.11.9",
  "i18next": "^23.5.1",
  "install": "^0.13.0",
  "nativescript-permissions": "^1.3.12",
  "npm": "^10.2.0",
  "react": "^18.2.0",
  "react-native-base64": "^0.2.1",
  "react-nativescript": "^5.0.0",
  "react-nativescript-navigation": "^5.0.0",
  "sass": "^1.69.4",
  "sql.js": "^1.8.0",
  "svg64": "^2.0.0"
},
"devDependencies": {
  "@nativescript/android": "8.6.2",
  "@nativescript/ios": "8.6.1",
  "@nativescript/preview-cli": "^1.0.5",
  "@nativescript/types": "~8.5.0",
  "@nativescript/webpack": "~5.0.14",
  "@types/react": "npm:types-react-without-jsx-intrinsics@^18.0.17",
  "typescript": "~4.8.4"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
