### ISSUE TITLE
Incompatible with latest Android Studio Giraffe

### ISSUE THREAD

**Issue by abrinckm** [NativeScript/NativeScript#10425]
### Issue Description

When following the ["Setting up Windows"](https://docs.nativescript.org/setup/windows) guide, I installed the latest version of NativeScript (8.6.1 as of now) and then installed the latest Android Studio (Giraffe) for Win64. 

The latest SDK Build-Tools for Android are now version 34

However NS requires versions ">=23 <=33"

Below is a screenshot of the version of build tools from the latest Android Studio. I'm searching for an older version of Android Studio that is compatible, however it would be best if NativeScript could support the latest build tools.

![Screenshot 2023-10-27 133046](https://github.com/NativeScript/NativeScript/assets/8681111/f08025fd-5d84-485d-a4b4-459215bf778d)

### Reproduction

1. Install NativeScript version 8.6.1
2. Install latest Android Studio version: "Giraffe | 2022.3.1 Patch 2 (built on September 14, 2023)"

run `ns doctor android`

### Relevant log output (if applicable)

```shell
There seem to be issues with your configuration.
√ Getting NativeScript components versions information...
√ Component nativescript has 8.6.1 version and is up to date.
√ Your ANDROID_HOME environment variable is set and points to correct directory.
√ Your adb from the Android SDK is correctly installed.
√ The Android SDK is installed.
√ Javac is installed and is configured properly.
√ The Java Development Kit (JDK) is installed and is configured properly.
√ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
× Cannot find a compatible Android SDK for compilation.
To be able to build for Android with your current android runtime, install one of the following supported Android SDK targets:
  android-17
  android-18
  android-19
  android-20
  android-21
  android-22
  android-23
  android-24
  android-25
  android-26
  android-27
  android-28
  android-29
  android-30
  android-31
  android-32
  android-33
```

### Environment

```yaml
OS: Windows 10 10.0.22621
CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Shell: Not Found
node: 21.1.0
npm: 10.2.0
nativescript: Not Found

# android
java: Not Found
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: Not Found
cocoapods: Not Found
python: Not Found
python3: Not Found
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
"dependencies": {},
"devDependencies": {}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
