### ISSUE TITLE
BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

### ISSUE THREAD

**Issue by nethriis** [NativeScript/NativeScript#10453]
### Issue Description

I have created a new native script project and when I do `ns run android` I receive this error:
```shell
FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'C:\Users\david\Documents\Epitech\AreaTest\mobile\native-script\platforms\tempPlugin\core\settings.gradle' (C:\Users\david\.gradle\caches\7.6\scripts\37bupetjbxez4p8emeofjjj0z).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 585ms
Failed to build plugin @nativescript/core : 
Error: Command gradlew.bat failed with exit code 1
```

### Reproduction

Here is the result of `ns doctor android`:
```shell
✔ Getting environment information

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.6.1 version and is up to date.
✔ Component @nativescript/core has 8.6.1 version and is up to date.
✔ Component @nativescript/android has 8.6.2 version and is up to date.
```

### Environment

```yaml
OS: Windows 11 10.0.22621
CPU: (20) x64 13th Gen Intel(R) Core(TM) i9-13900H
Shell: Not Found
node: 18.17.1
npm: 10.2.4
nativescript: Not Found

# android
java: Not Found
ndk: Not Found
apis: 30, 33, 34
build_tools: 30.0.3, 33.0.0, 34.0.0
system_images: 
  - android-30 | Google Play Intel x86 Atom
  - android-34 | Google APIs Intel x86_64 Atom

# ios
xcode: Not Found
cocoapods: Not Found
python: Not Found
python3: Not Found
ruby: 3.2.2
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "~8.6.0",
  "@nativescript/theme": "~3.0.2",
  "nativescript-vue": "~2.9.3"
},
"devDependencies": {
  "@nativescript/android": "8.6.2",
  "@nativescript/types": "~8.6.0",
  "@nativescript/webpack": "~5.0.18",
  "@types/node": "~17.0.21",
  "@vue/runtime-dom": "^3.3.9",
  "nativescript-vue-template-compiler": "~2.9.3",
  "typescript": "~4.8.4",
  "vue": "~2.6.12"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
