### ISSUE TITLE
TimePicker: show minutes incorrectly when setting minute in Android

### ISSUE THREAD

**Issue by liuy97** [NativeScript/NativeScript#10457]
### Issue Description

TimePicker shows the current minutes instead of the given minute value in Android.

### Reproduction

 ns create demo --ng

update item-detail
```
<ActionBar title="Details"></ActionBar>

<FlexboxLayout flexDirection="column">
  <FlexboxLayout class="m-15">
    <Label class="h2" [text]="item.id + '. '"></Label>
    <Label class="h2" [text]="item.name"></Label>
  </FlexboxLayout>
  <Label class="h4 m-15" [text]="item.role"></Label>
  <TimePicker [hour]="hour" [minute]="minute"></TimePicker>
</FlexboxLayout>

```
```
import { Component, OnInit } from "@angular/core";
import { ActivatedRoute } from "@angular/router";

import { Item } from "./item";
import { ItemService } from "./item.service";

@Component({
  selector: "ns-details",
  templateUrl: "./item-detail.component.html",
})
export class ItemDetailComponent implements OnInit {
  item: Item;
  hour = 8;
  minute = 0;

  constructor(
    private itemService: ItemService,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    const id = +this.route.snapshot.params.id;
    this.item = this.itemService.getItem(id);
  }
}

```
ns run android

### Environment

```yaml
OS: macOS 13.3
CPU: (12) arm64 Apple M2 Pro
Shell: /bin/zsh
node: 18.18.0
npm: 9.8.1
nativescript: 8.6.1

# android
java: 17.0.9
ndk: Not Found
apis: 33, 34
build_tools: 33.0.0, 33.0.2, 34.0.0
system_images: 
  - android-33 | Google APIs ARM 64 v8a
  - android-34 | Google APIs ARM 64 v8a

# ios
xcode: 14.3.1/14E300c
cocoapods: 1.12.1
python: Not Found
python3: 3.9.6
ruby: 2.7.8
platforms: 
  - DriverKit 22.4
  - iOS 16.4
  - macOS 13.3
  - tvOS 16.4
  - watchOS 9.4
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~16.2.0",
  "@angular/common": "~16.2.0",
  "@angular/compiler": "~16.2.0",
  "@angular/core": "~16.2.0",
  "@angular/forms": "~16.2.0",
  "@angular/platform-browser": "~16.2.0",
  "@angular/platform-browser-dynamic": "~16.2.0",
  "@angular/router": "~16.2.0",
  "@nativescript/angular": "^16.0.0",
  "@nativescript/core": "~8.6.0",
  "@nativescript/theme": "~3.0.2",
  "rxjs": "~7.8.0",
  "zone.js": "~0.13.0"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~16.2.0",
  "@angular/compiler-cli": "~16.2.0",
  "@nativescript/android": "8.6.2",
  "@nativescript/ios": "8.6.3",
  "@nativescript/types": "~8.6.0",
  "@nativescript/webpack": "~5.0.18",
  "@ngtools/webpack": "~16.2.0",
  "typescript": "~5.1.6"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
