### ISSUE TITLE
New angular project crashes on startup when ns run ios on real device with ios version 12.5.7

### ISSUE THREAD

**Issue by pichurichko** [NativeScript/NativeScript#10463]
### Issue Description

Creating project from scratch and running on real iOS device with 12.5.7 iOS crashes on start. 

### Reproduction

1) Create project using command:
`ns create myCoolAppTest --angular`
2) Run command to launch newly app on real iOS device with 12.5.7 iOS version
`ns run ios`

### Relevant log output (if applicable)

```shell
Exception Type: EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000,
0x0000000000000000
Exception Note: EXC_CORPSE_NOTIFY
Termination Description: DYLD, Symbol not found: _objc_opt_class | Referenced from: /private/var/containers/Bundle/ Application/CA7076DD-4ADD-44E4-
BDB2-78813F0EF534/
myCoolAppTest.app/Frameworks/ TNSWidgets.framework/TNSWidgets
(which was built for iOS 13.0) | Expected in: dyld shared cache
```

### Environment

```yaml
OS: macOS 14.1.2
CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
Shell: /bin/zsh
node: 20.3.0
npm: 9.6.7
nativescript: 8.6.3

# android
java: 15.0.2
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 15.0.1/15A507
cocoapods: 1.14.3
python: 2.7.18
python3: 3.9.6
ruby: 2.7.4
platforms: 
  - DriverKit 23.0
  - iOS 17.0
  - macOS 14.0
  - tvOS 17.0
  - watchOS 10.0
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~16.2.0",
  "@angular/common": "~16.2.0",
  "@angular/compiler": "~16.2.0",
  "@angular/core": "~16.2.0",
  "@angular/forms": "~16.2.0",
  "@angular/platform-browser": "~16.2.0",
  "@angular/platform-browser-dynamic": "~16.2.0",
  "@angular/router": "~16.2.0",
  "@nativescript/angular": "^16.0.0",
  "@nativescript/core": "~8.6.0",
  "@nativescript/theme": "~3.0.2",
  "rxjs": "~7.8.0",
  "zone.js": "~0.13.0"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~16.2.0",
  "@angular/compiler-cli": "~16.2.0",
  "@nativescript/ios": "8.6.3",
  "@nativescript/types": "~8.6.0",
  "@nativescript/webpack": "~5.0.18",
  "@ngtools/webpack": "~16.2.0",
  "typescript": "~5.1.6"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
