### ISSUE TITLE
RootLayout enterFrom animation bugged on iOS

### ISSUE THREAD

**Issue by mBaldasty** [NativeScript/NativeScript#10496]
### Issue Description

I attached a video to illustrate it. For obvious reference I set the duration of the enterFrom and exitTo to 5 seconds.
As seen, the enterFrom gets shifted in immediately while exitTo works as it should. It maybe works in 1 of 10 cases correctly or even less.

https://github.com/NativeScript/NativeScript/assets/74302920/8653c971-4674-43a6-8c39-cebfe25b8384

What I found as a fix was to patch https://github.com/NativeScript/NativeScript/blob/db0a852f5bee60a306b4e3cb14664b6ac32601a2/packages/core/ui/layouts/root-layout/root-layout-common.ts#L98 to set the timeout to 1 instead of nothing like in that line.

### Reproduction

For reproduction I created the repo https://gitlab.com/mBaldasty/RootLayoutAnimationIssue

### Environment

```yaml
OS: macOS 13.4.1
CPU: (10) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 18.16.0
npm: 9.5.1
nativescript: 8.6.5

# android
java: 11.0.18
ndk: Not Found
apis: 28, 29, 30, 31, 32, 33, 33
build_tools: 29.0.3, 30.0.0, 30.0.3, 32.0.0, 33.0.0, 33.0.1, 33.0.2
system_images: 
  - android-27 | Google APIs ARM 64 v8a
  - android-28 | Google APIs ARM 64 v8a
  - android-29 | Google APIs ARM 64 v8a
  - android-31 | ARM 64 v8a
  - android-32 | Google APIs ARM 64 v8a

# ios
xcode: 14.3/14E222b
cocoapods: 1.12.0
python: 3.11.4
python3: 3.11.4
ruby: 2.7.7
platforms: 
  - DriverKit 22.4
  - iOS 16.4
  - macOS 13.3
  - tvOS 16.4
  - watchOS 9.4
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "8.6.2",
  "@nativescript/theme": "~3.0.2",
  "nativescript-vue": "~2.9.3"
},
"devDependencies": {
  "@nativescript/android": "8.6.2",
  "@nativescript/ios": "8.6.3",
  "@nativescript/webpack": "5.0.18",
  "nativescript-vue-template-compiler": "2.9.3"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
