### ISSUE TITLE
Devtools 0.0.1 Error: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by tomcoonen** [NativeScript/NativeScript#10513]
### Issue Description

Seems like some casting is missing for local storage Boolean values? Error: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String.

### Reproduction

Running 8.7.0 with the @nativescript/devtools with existing local storage values.

### Relevant log output (if applicable)

```shell
Error: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
  Error: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
```

### Environment

```yaml
OS: macOS 14.4.1
CPU: (10) arm64 Apple M1 Max
Shell: /bin/zsh
node: 20.11.1
npm: 10.2.4
nativescript: 8.7.0

# android
java: 11.0.22
ndk: Not Found
apis: 23, 30, 31, 33
build_tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1
system_images:
  - android-29 | Google APIs ARM 64 v8a
  - android-30 | Google APIs ARM 64 v8a
  - android-31 | Intel x86 Atom_64

# ios
xcode: 15.3/15E204a
cocoapods: 1.14.2
python: 3.12.2
python3: 3.12.2
ruby: 3.2.0
platforms:
  - DriverKit 23.4
  - iOS 17.4
  - macOS 14.4
  - tvOS 17.4
  - visionOS 1.1
  - watchOS 10.4
```

### Dependencies

```json
"dependencies": {
  "@master.technology/permissions": "^2.0.1",
  "@nativescript/appavailability": "^2.0.0",
  "@nativescript/appversion": "^2.0.0",
  "@nativescript/brightness": "~2.0.0",
  "@nativescript/core": "^8.3.2",
  "@nativescript/devtools": "^0.0.1",
  "@nativescript/firebase-core": "^3.2.0",
  "@nativescript/firebase-crashlytics": "^3.2.0",
  "@nativescript/geolocation": "^8.0.2",
  "@nativescript/localize": "^5.0.4",
  "@nativescript/tailwind": "^2.0.0",
  "@nativescript/theme": "~3.0.2",
  "axios": "^0.28.0",
  "date-fns": "^3.3.1",
  "debug": "^4.3.4",
  "nativescript-audio": "^6.2.6",
  "nativescript-dna-deviceinfo": "^3.7.3",
  "nativescript-phone": "^3.0.3",
  "nativescript-qr-generator": "^3.0.0",
  "nativescript-ui-sidedrawer": "^15.2.3",
  "nativescript-vue": "~2.9.2",
  "nativescript-vue-devtools": "^1.5.1",
  "nativescript-vue-navigator": "^1.2.0",
  "slugify": "^1.6.5",
  "tailwindcss": "^3.1.7",
  "vue-class-component": "^7.2.6",
  "vue-property-decorator": "^9.1.2"
},
"devDependencies": {
  "@babel/core": "^7.18.10",
  "@babel/preset-env": "^7.18.10",
  "@nativescript/android": "~8.7.0",
  "@nativescript/ios": "~8.7.0",
  "@nativescript/types": "~8.7.0",
  "@nativescript/webpack": "~5.0.18",
  "@rushstack/eslint-patch": "^1.10.1",
  "@types/node": "~20.11.19",
  "@typescript-eslint/eslint-plugin": "^7.0.1",
  "@typescript-eslint/parser": "^7.0.1",
  "@vue/cli-plugin-typescript": "^4.5.19",
  "@vue/eslint-config-prettier": "^9.0.0",
  "@vue/eslint-config-typescript": "^12.0.0",
  "babel-loader": "^8.3.0",
  "eslint-config-prettier": "^9.1.0",
  "eslint-plugin-prettier": "^5.1.3",
  "nativescript-vue-template-compiler": "~2.9.0",
  "prettier": "^3.2.5",
  "sass": "^1.49.9",
  "typescript": "~5.4.0",
  "vue": "^2.6.12",
  "vue-loader": "^15.9.3"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
