### ISSUE TITLE
java.io.IOException when updating nativescript/core: File already exists. This may lead to undesired behavior.

### ISSUE THREAD

**Issue by DiegoMacBD** [NativeScript/NativeScript#10564]
### Issue Description

Hi, I have a native class with javaproxy and nativeclass decorators:
`@NativeClass()
@JavaProxy('com.tns.customPushy.PushReceiver')
class PushReceiver extends android.content.BroadcastReceiver {
    ...
 }`
 
When try to update to the latest core version (8.7.2), at the moment of building the app, I get the following error:

`Error executing Static Binding Generator: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
File:/Users/diego/llu.app/platforms/android/app/src/main/java/com/tns/customPushy/PushReceiver.java Class: com.tns.customPushy.PushReceiver
Detailed log here: /Users/diego/llu.app/platforms/android/build-tools/runSbg.log`

Detailed log: 
`Warning: there already is an extend called com.tns.customPushy.PushReceiver.
Warning: The static binding generator will generate extend from:bundle.js implementation
Warning: there already is an extend called com.tns.NotificationActionReceiver.
Warning: The static binding generator will generate extend from:bundle.js implementation
java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
File:/Users/diego/llu.app/platforms/android/app/src/main/java/com/tns/customPushy/PushReceiver.java Class: com.tns.customPushy.PushReceiver
	at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:113)
	at org.nativescript.staticbindinggenerator.Main.main(Main.java:55)`
	
Of course this was not happening before updating, so I located the issue to be on the changes for core 8.5.4, it works as expected on 8.5.3. I saw that there are some changes on the files-system portion of the core packages, so my guess is that the issue should be there, but I haven't been able exactly what is causing the issue, any help on this would be appreciated!

### Relevant log output (if applicable)

```shell
Error executing Static Binding Generator: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
File:/Users/diego/llu.app/platforms/android/app/src/main/java/com/tns/customPushy/PushReceiver.java Class: com.tns.customPushy.PushReceiver
Detailed log here: /Users/diego/llu.app/platforms/android/build-tools/runSbg.log
Warning: there already is an extend called com.tns.customPushy.PushReceiver.
Warning: The static binding generator will generate extend from:bundle.js implementation
Warning: there already is an extend called com.tns.NotificationActionReceiver.
Warning: The static binding generator will generate extend from:bundle.js implementation
java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
File:/Users/diego/llu.app/platforms/android/app/src/main/java/com/tns/customPushy/PushReceiver.java Class: com.tns.customPushy.PushReceiver
	at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:113)
	at org.nativescript.staticbindinggenerator.Main.main(Main.java:55)
```

### Environment

```yaml
OS: macOS 14.2.1
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Shell: /bin/bash
node: 16.20.2
npm: 8.19.4
nativescript: Not Found

# android
java: 11.0.14
ndk: Not Found
apis: 28, 29, 30, 31, 33, 34
build_tools: 22.0.1, 28.0.3, 29.0.2, 30.0.3, 31.0.0, 33.0.0, 34.0.0
system_images: 
  - android-28 | Google APIs Intel x86 Atom
  - android-28 | Google Play Intel x86 Atom
  - android-29 | Google APIs Intel x86 Atom
  - android-29 | Google Play Intel x86 Atom
  - android-30 | Google APIs Intel x86 Atom
  - android-30 | Google Play Intel x86 Atom
  - android-32 | Google Play Intel x86 Atom_64
  - android-33 | Google Play Intel x86 Atom_64
  - android-S | Google APIs Intel x86 Atom_64

# ios
xcode: 15.0.1/15A507
cocoapods: 1.13.0
python: Not Found
python3: 3.9.6
ruby: 2.6.10
platforms: 
  - DriverKit 23.0
  - iOS 17.0
  - macOS 14.0
  - tvOS 17.0
  - watchOS 10.0
```

### Dependencies

```json
"dependencies": {
  "@nativescript-community/arraybuffers": "^1.1.1",
  "@nativescript-community/sentry": "^4.6.12",
  "@nativescript-community/ui-label": "^1.3.6",
  "@nativescript-community/ui-lottie": "^6.0.0",
  "@nativescript/appversion": "^2.0.0",
  "@nativescript/core": "8.7.2",
  "@nativescript/datetimepicker": "^2.1.13",
  "@nativescript/firebase-core": "^3.2.4",
  "@nativescript/firebase-crashlytics": "^3.2.4",
  "@nativescript/firebase-messaging": "^3.2.4",
  "@nativescript/iqkeyboardmanager": "^2.1.1",
  "@nativescript/local-notifications": "^6.1.1",
  "@nativescript/localize": "^5.2.0",
  "@nativescript/secure-storage": "^3.0.2",
  "@nativescript/theme": "^3.0.2",
  "@nstudio/nativescript-cardview": "^2.0.2",
  "@sentry/webpack-plugin": "^1.20.0",
  "mediator-js": "0.11.0",
  "moment": "2.29.4",
  "moment-timezone": "0.5.43",
  "nativescript-android-utils": "git+https://github.com/petekanev/nativescript-android-utils.git",
  "nativescript-drop-down": "6.0.2",
  "nativescript-intl": "4.0.2",
  "nativescript-master-technology": "1.1.3",
  "nativescript-randombytes": "1.0.0",
  "nativescript-sha": "^1.0.4",
  "nativescript-ui-sidedrawer": "15.2.3",
  "nativescript-websockets": "1.5.6",
  "patch-package": "^7.0.0",
  "postinstall-postinstall": "^2.1.0",
  "redux": "4.2.1",
  "validator": "13.9.0"
},
"devDependencies": {
  "@bengourley/source-map-decoder": "^1.0.1-0",
  "@nativescript/android": "8.7.0",
  "@nativescript/debug-ios": "^1.0.0",
  "@nativescript/eslint-plugin": "^0.0.4",
  "@nativescript/ios": "8.7.1",
  "@nativescript/types": "^8.6.1",
  "@nativescript/webpack": "^5.0.21",
  "@types/redux-logger": "3.0.9",
  "@types/remote-redux-devtools": "0.5.5",
  "@types/webpack-env": "1.18.1",
  "@typescript-eslint/eslint-plugin": "6.0.0",
  "@typescript-eslint/parser": "6.0.0",
  "eslint": "7.32.0",
  "eslint-config-prettier": "8.3.0",
  "eslint-loader": "4.0.2",
  "eslint-plugin-llu": "file:./eslint",
  "eslint-plugin-prettier": "5.0.0",
  "lazy": "1.0.11",
  "moment-locales-webpack-plugin": "^1.2.0",
  "prettier": "3.0.0",
  "redux-devtools-cli": "0.0.1-1",
  "redux-logger": "3.0.6",
  "remote-redux-devtools": "0.5.16",
  "sass": "1.63.6",
  "string-replace-loader": "3.0.3",
  "typescript": "~4.8.4",
  "xcode": "^3.0.1",
  "xmldom": "^0.6.0",
  "yarn-check": "0.0.3"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
