### ISSUE TITLE
PageTransition's fade animation has a jarring flash of gray at start of its animation

### ISSUE THREAD

**Issue by jasongitmail** [NativeScript/NativeScript#10572]
### Issue Description

When using the 'fade' transition for a page navigation on iOS, there is a flash of gray before the animation occurs.

For example:
```ts
navigate({ page: Right, transition: { name: 'fade', duration: 300 } });
```

### Reproduction

[Reproduction on StackBlitz](https://stackblitz.com/edit/nativescript-stackblitz-templates-qbem4v?file=app%2Fcomponents%2FHome.svelte,app%2Fcomponents%2FRight.svelte,package.json&title=NativeScript%20Starter%20Svelte)
1. Start the project and click "go right" in the action bar. 
2. Click "close". 
3. Keep doing 1 and 2 and notice the flash of gray. Looks bad when an app has a dark background color.

https://github.com/NativeScript/NativeScript/assets/50032291/5d09f563-2153-4021-84ea-7dd5d20cd284

### Relevant log output (if applicable)

```shell
None.
```

### Environment

Environment from StackBlitz repro:

```yaml
OS: Linux 5.0 undefined
CPU: (2) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Shell: /bin/jsh
node: 18.20.3
npm: 10.2.3
nativescript: Not Found

# android
java: Not Found
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: Not Found
cocoapods: Not Found
python: 0.2.0
python3: 0.2.0
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "~8.7.0",
  "svelte-native": "~1.0.0"
},
"devDependencies": {
  "@nativescript/preview-cli": "1.0.12",
  "@nativescript/stackblitz": "0.0.8",
  "@nativescript/tailwind": "^2.1.0",
  "@nativescript/types-minimal": "~8.7.0",
  "@nativescript/webpack": "~5.0.0",
  "svelte": "~4.2.0",
  "svelte-loader": "^3.2.0",
  "svelte-native-preprocessor": "^1.0.0",
  "svelte-preprocess": "^5.1.3",
  "tailwindcss": "~3.4.0",
  "typescript": "~5.4.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
