### ISSUE TITLE
SharedTransition causes performance issues in the action bar 

### ISSUE THREAD

**Issue by jasongitmail** [NativeScript/NativeScript#10571]
### Issue Description

When a SharedTransition exists on a page, the action bar becomes very slow, will fail to respond to user taps to "go back" until ~2 seconds after the navigation was started. It feels laggy/buggy for users. This is _much_ slower than when a SharedTransition does _not_ exist on the page.

In this video, I tap "go left" and "go right" and the back buttons as quickly as it will allow me. Left has a SharedTransition, Right has a regular page navigation. 

(You can't see it in the video, but when on the left page, I'm tapping "back" multiple times and it is failing to navigate before eventually there is a successful navigation back. When I tap "back" on the right page, it works on the first attempt.)

https://github.com/NativeScript/NativeScript/assets/50032291/ffeeee48-1c86-49cb-9878-75c518967fce

### Reproduction

[Reproduction on StackBlitz](https://stackblitz.com/edit/nativescript-stackblitz-templates-dtvabc?file=app%2Fcomponents%2FHome.svelte,app%2Fcomponents%2FLeft.svelte,app%2Fcomponents%2FRight.svelte&title=NativeScript%20Starter%20Svelte):
1. Click "go left" in the action bar and then try to click "close" as quickly as you can. It will take a couple sections until it's responsive, and you will have many failed attempts tapping "close" until then. This feels slow/laggy/buggy for a user.
2. In contrast, click "go right" (which uses a regular page navigation without a Shared Transition) and click "close" as quickly as you can. It remains responsive as expected.

Versions:
```
    "@nativescript/core": "~8.7.0",
    "svelte-native": "~1.0.0"
```

### Relevant log output (if applicable)

```shell
(no useful logs)
```

### Environment

Sharing the environment from StackBlitz where the reproduction lives:

```yaml
OS: Linux 5.0 undefined
CPU: (2) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Shell: /bin/jsh
node: 18.20.3
npm: 10.2.3
nativescript: Not Found

# android
java: Not Found
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: Not Found
cocoapods: Not Found
python: 0.2.0
python3: 0.2.0
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "~8.7.0",
  "svelte-native": "~1.0.0"
},
"devDependencies": {
  "@nativescript/preview-cli": "1.0.12",
  "@nativescript/stackblitz": "0.0.8",
  "@nativescript/tailwind": "^2.1.0",
  "@nativescript/types-minimal": "~8.7.0",
  "@nativescript/webpack": "~5.0.0",
  "svelte": "~4.2.0",
  "svelte-loader": "^3.2.0",
  "svelte-native-preprocessor": "^1.0.0",
  "svelte-preprocess": "^5.1.3",
  "tailwindcss": "~3.4.0",
  "typescript": "~5.4.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
