### ISSUE TITLE
Android only bug: When orientationChangedEvent is called Screen.mainScreen still holds old values

### ISSUE THREAD

**Issue by cjohn001** [NativeScript/NativeScript#10598]
### Issue Description

The bug only appears on Android. iOS behaviour is correct. When registering an EventHandler Screen.mainScreen.widthDIPS and heightDIPS still hold old values.

```
Application.on(Application.orientationChangedEvent, funDeviceOrientationChanged);

function funDeviceOrientationChanged(){
console.log('width:'+ Screen.mainScreen.widthDIPs + ' height:' + Screen.mainScreen.heightDIPs);
}
```

### Environment

```yaml
OS: macOS 14.5
CPU: (10) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 20.11.1
npm: 10.2.4
nativescript: 8.7.2

# android
java: 17.0.12
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 15.4/15F31d
cocoapods: 1.15.2
python: 3.12.4
python3: 3.12.4
ruby: 2.7.8
platforms: 
  - DriverKit 23.5
  - iOS 17.5
  - macOS 14.5
  - tvOS 17.5
  - visionOS 1.2
  - watchOS 10.5
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "18.1.3",
  "@angular/common": "18.1.3",
  "@angular/compiler": "18.1.3",
  "@angular/core": "18.1.3",
  "@angular/forms": "18.1.3",
  "@angular/platform-browser": "18.1.3",
  "@angular/platform-browser-dynamic": "18.1.3",
  "@angular/router": "18.1.1",
  "@apollo/client": "3.11.2",
  "@mnd/external-web-view": "file:../app-plugins/dist/packages/external-web-view/mnd-external-web-view-1.0.1.tgz",
  "@nativescript/angular": "18.1.1",
  "@nativescript/core": "8.7.2",
  "@nativescript/iqkeyboardmanager": "2.1.1",
  "@nativescript/localize": "5.2.0",
  "@nativescript/mlkit-barcode-scanning": "2.1.0",
  "@nativescript/mlkit-core": "2.1.0",
  "@nativescript/secure-storage": "3.0.3",
  "@nativescript/theme": "3.1.0",
  "@nativescript/ui-charts": "0.2.4",
  "apollo-angular": "7.0.2",
  "apollo3-cache-persist": "0.15.0",
  "d3-ease": "3.0.1",
  "graphql": "16.9.0",
  "graphql-tag": "2.12.6",
  "intl": "1.2.5",
  "moment": "2.30.1",
  "nativescript-health-data": "file:../app-plugins-customized/nativescript-health-data/publish/package/nativescript-health-data-2.0.0.tgz",
  "nativescript-oauth2-ext": "file:../app-plugins-customized/nativescript-oauth2-ext/publish/package/nativescript-oauth2-ext-3.0.3.tgz",
  "nativescript-sqlite": "2.8.6",
  "nativescript-sqlite-commercial": "file:../app-plugins-customized/commercial-sqlite/nativescript-sqlite-commercial-1.8.0.tgz",
  "nativescript-sqlite-encrypted": "file:../app-plugins-customized/commercial-sqlite/nativescript-sqlite-encrypted-1.6.0.tgz",
  "nativescript-ui-calendar": "15.2.3",
  "nativescript-ui-gauge": "15.2.3",
  "qs": "npm:querystring@0.2.1",
  "rxjs": "7.8.1",
  "util": "0.12.5",
  "uuidjs": "5.1.0",
  "zone.js": "0.14.8"
},
"devDependencies": {
  "@angular-devkit/build-angular": "18.1.3",
  "@angular/compiler-cli": "18.1.3",
  "@graphql-codegen/cli": "5.0.2",
  "@graphql-codegen/fragment-matcher": "5.0.2",
  "@graphql-codegen/introspection": "4.0.3",
  "@graphql-codegen/typescript": "4.0.9",
  "@graphql-codegen/typescript-apollo-angular": "4.0.0",
  "@graphql-codegen/typescript-operations": "4.2.3",
  "@nativescript/android": "8.7.0",
  "@nativescript/ios": "8.7.2",
  "@nativescript/types": "8.7.0",
  "@nativescript/webpack": "5.0.22",
  "@ngtools/webpack": "18.1.3",
  "@types/d3-ease": "3.0.2",
  "@types/intl": "1.2.2",
  "@types/lodash": "4.17.7",
  "@types/node": "22.0.2",
  "keycloak-request-token": "0.1.0",
  "rimraf": "6.0.1",
  "sass": "1.77.8",
  "ts-node": "10.9.2",
  "typescript": "5.4.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
