### ISSUE TITLE
Error in create project

### ISSUE THREAD

**Issue by Robson96** [NativeScript/NativeScript#10610]
### Issue Description

I'm trying to create a project in several ways but it always gives the same error

### Reproduction

 ns create myCoolApp --js

### Relevant log output (if applicable)

```shell
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'C:\Users\user\Documents\native-script\myCoolApp\node_modules\npm\bin\npm-cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.10.0
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'C:\Users\user\Documents\native-script\myCoolApp\node_modules\npm\bin\npm-cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.10.0
Command "npm.cmd" failed with exit code 1
```

### Environment

PS C:\Users\user\Documents\native-script> ns -v
8.8.1
✔ Up to date.

```yaml
OS: Windows 11 10.0.22631
CPU: (8) x64 AMD Ryzen 5 7520U with Radeon Graphics
Shell: Not Found
node: 20.10.0
npm: 10.2.3
nativescript: Not Found

# android
java: Not Found
ndk: Not Found
apis: 32, 33, 34
build_tools: 30.0.3, 33.0.1, 34.0.0
system_images:
  - android-27 | Google Play Intel x86 Atom
  - android-31 | Google Play Intel x86_64 Atom
  - android-33 | Google Play Intel x86_64 Atom
  - android-34 | Google APIs Intel x86_64 Atom

# ios
xcode: Not Found
cocoapods: Not Found
python: Not Found
python3: Not Found
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
"dependencies": {},
"devDependencies": {}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
