### ISSUE TITLE
XCode 16 Provisioning Profile folder location

### ISSUE THREAD

**Issue by sepccom** [NativeScript/NativeScript#10633]
### Issue Description

When using MACOS Terminal to run 'ns publish ios --appleApplicationSpecificPassword <password> --provision <name>' I receive an error:
ENDENT: No such file or directory, scandir 'Users/<user>/Library/MobileDevice/Provisioning Profiles'

I believe XCode 16 now stores Provisioning Profiles in a different location:
~/Library/Developer/Xcode/UserData/Provisioning Profiles

Very similar to Issue:
https://github.com/xamarin/xamarin-macios/issues/20771

I can confirm that my Provisioning Profile exists in ~/Library/Developer/Xcode/UserData/Provisioning Profiles/ folder location.

I have only just setup a new MacOS Air M3 fresh Nativescript Install, so all files are update-to-date to latest.

### Reproduction

1. run 'ns publish ios --appleApplicationSpecificPassword <password> --provision <name>

### Environment

```yaml
OS: macOS 14.5
CPU: (8) arm64 Apple M3
Shell: /bin/zsh
node: 22.9.0
npm: 10.9.0
nativescript: 8.8.2

# android
java: Not Found
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 16.0/16A242d
cocoapods: 1.15.2
python: Not Found
python3: 3.13.0
ruby: 3.3.5
platforms: 
  - DriverKit 24.0
  - iOS 18.0
  - macOS 15.0
  - tvOS 18.0
  - visionOS 2.0
  - watchOS 11.0
```

### Dependencies

```json
"dependencies": {
  "@nativescript/background-http": "^6.0.0",
  "@nativescript/camera": "^5.0.13",
  "@nativescript/core": "~8.3.0",
  "@nativescript/geolocation": "^8.0.2",
  "@nativescript/theme": "^3.0.2",
  "@nstudio/nativescript-filterable-listpicker": "^3.0.1",
  "@triniwiz/nativescript-image-cache-it": "^7.1.0",
  "@triniwiz/nativescript-image-zoom": "^4.2.0",
  "nativescript-speech-recognition": "^2.0.0",
  "nativescript-ui-dataform": "^8.0.1",
  "nativescript-ui-listview": "^14.2.4",
  "rxjs": "^6.3.3"
},
"devDependencies": {
  "@nativescript/android": "8.2.4",
  "@nativescript/ios": "8.3.3",
  "@nativescript/types": "^8.4.0",
  "@nativescript/webpack": "~5.0.0",
  "nativescript-set-version": "^0.3.0",
  "typescript": "~4.5.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
