### ISSUE TITLE
Line height acts as line spacing

### ISSUE THREAD

**Issue by CatchABus** [NativeScript/NativeScript#10641]
### Issue Description

When I set line height, I expect it to set the height of the line box.
However, that property works as a "line spacing" property so if I set line-height to let's say 16, I'll get extremely large spacing between lines.

See: https://developer.mozilla.org/en-US/docs/Web/CSS/line-height

### Environment

```yaml
OS: Linux 6.8 Ubuntu 20.04.3 LTS (Focal Fossa)
CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
Shell: /bin/bash
node: 22.4.1
npm: 10.8.1
nativescript: 8.8.0

# android
java: 17.0.12
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: Not Found
cocoapods: Not Found
python: 2.7.18
python3: 3.8.10
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "nativescript-theme-core": "^1.0.4"
},
"devDependencies": {
  "@nativescript/hook": "^2.0.0",
  "@nativescript/nx": "^19.0.0",
  "@nstudio/focus": "^19.0.0",
  "@nstudio/nps-i": "~2.0.0",
  "@nx/devkit": "19.4.2",
  "@nx/eslint-plugin": "19.4.2",
  "@nx/jest": "19.4.2",
  "@nx/js": "19.4.2",
  "@nx/node": "19.4.2",
  "@nx/plugin": "19.4.2",
  "@nx/workspace": "19.4.2",
  "@prettier/plugin-xml": "^3.4.1",
  "@types/jest": "~29.5.0",
  "@types/node": "^20.0.0",
  "@typescript-eslint/eslint-plugin": "^7.5.0",
  "@typescript-eslint/parser": "^7.5.0",
  "acorn": "^8.7.0",
  "conventional-changelog-cli": "^4.1.0",
  "copyfiles": "^2.4.0",
  "css": "^3.0.0",
  "css-tree": "^1.1.2",
  "css-what": "^6.1.0",
  "dotenv": "~16.4.0",
  "emoji-regex": "^10.3.0",
  "eslint": "~8.57.0",
  "eslint-config-prettier": "~9.1.0",
  "gonzales": "^1.0.7",
  "husky": "^9.0.0",
  "jest": "~29.7.0",
  "jest-environment-jsdom": "~29.7.0",
  "lint-staged": "^15.2.0",
  "module-alias": "^2.2.2",
  "nativescript": "8.8.0-pre-next-07-03-2024-9781798152",
  "nativescript-typedoc-theme": "1.1.0",
  "nx": "19.4.2",
  "parse-css": "git+https://github.com/tabatkins/parse-css.git",
  "parserlib": "^1.1.1",
  "prettier": "^3.2.5",
  "reduce-css-calc": "~2.1.7",
  "sass": "^1.72.0",
  "shady-css-parser": "^0.1.0",
  "tree-kill": "^1.2.2",
  "ts-jest": "29.1.2",
  "ts-node": "10.9.2",
  "ts-patch": "^3.0.0",
  "tslib": "^2.6.0",
  "typedoc": "^0.25.12",
  "typescript": "~5.4.0",
  "zx": "^7.2.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
