### ISSUE TITLE
npm error ERESOLVE with svelte-native default template

### ISSUE THREAD

**Issue by dmoebius** [NativeScript/NativeScript#10660]
### Issue Description

When I create a new native-script project from the default svelte template, the generated package.json has resolve conflicts.

### Reproduction

Create a new project from the svelte template:
```
$ npx nativescript create svelte-native-app --svelte
```
Then run `npm install` in the created project:
```
$ cd svelte-native-app
$ npm install
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: svelte-native-preprocessor@1.0.0
npm error Found: svelte@4.2.19
npm error node_modules/svelte
npm error   dev svelte@"~4.2.2" from the root project
npm error   peer svelte@">=3.19.0" from svelte-hmr@0.14.12
npm error   node_modules/svelte-hmr
npm error     svelte-hmr@"^0.14.2" from svelte-loader@3.2.4
npm error     node_modules/svelte-loader
npm error       dev svelte-loader@"^3.1.9" from the root project
npm error   3 more (svelte-loader, svelte-native, svelte-preprocess)
npm error
npm error Could not resolve dependency:
npm error peer svelte@"^3.37.0" from svelte-native-preprocessor@1.0.0
npm error node_modules/svelte-native-preprocessor
npm error   dev svelte-native-preprocessor@"^1.0.0" from the root project
npm error
npm error Conflicting peer dependency: svelte@3.59.2
npm error node_modules/svelte
npm error   peer svelte@"^3.37.0" from svelte-native-preprocessor@1.0.0
npm error   node_modules/svelte-native-preprocessor
npm error     dev svelte-native-preprocessor@"^1.0.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

### Environment

```yaml
OS: Linux 6.12 Garuda Linux
CPU: (22) x64 Intel(R) Core(TM) Ultra 9 185H
Shell: /bin/bash
node: 22.12.0
npm: 10.9.0
nativescript: Not Found

# android
java: 21.0.3
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: Not Found
cocoapods: Not Found
python: 3.12.7
python3: 3.12.7
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
"@nativescript/core": "~8.8.0",
"@nativescript/theme": "^3.1.0",
"svelte-native": "~1.0.9"
},
"devDependencies": {
"@nativescript/types": "~8.8.0",
"@nativescript/webpack": "~5.0.0",
"svelte": "~4.2.2",
"svelte-loader": "^3.1.9",
"svelte-native-preprocessor": "^1.0.0",
"svelte-preprocess": "^5.0.4",
"typescript": "~5.4.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
