### ISSUE TITLE
Installing nativescript on windows machine

### ISSUE THREAD

**Issue by RemTech** [NativeScript/NativeScript#10730]
### Issue Description

**Desctiption**: 
- When I run `ns doctor android` command after installing nativesript, the error below in the screenshot comes up.

**Expected Result:** 
- Nativescript to be successfully installed and ready for project creation. 

**Actual  Result:**
- Nativescript not fully installed and project cannot be created.
![Image](https://github.com/user-attachments/assets/d351d127-ffdb-4c4d-9c62-ad02185d4a1c)

### Reproduction

- Follow the instructions via this url https://docs.nativescript.org/setup/windows.

### Relevant log output (if applicable)

```shell

```

### Environment

![Image](https://github.com/user-attachments/assets/68b5ad5a-e84d-4bbf-a78a-409099513119)

npx nativescript-envinfo

```yaml
OS: Windows 11 10.0.26100
CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
Shell: Not Found
node: 22.12.0
npm: 10.9.0
nativescript: Not Found

# android
java: Not Found
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: Not Found
cocoapods: Not Found
python: Not Found
python3: Not Found
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
"dependencies": {},
"devDependencies": {}
```

### Please accept these terms

- [x] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [x] This is a bug report
- [x] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
