### ISSUE TITLE
FormattedString does not respect font scale

### ISSUE THREAD

**Issue by liuy97** [NativeScript/NativeScript#10746]
### Issue Description

Label with FormattedString will not respect font scale.

### Reproduction

```
ns create demo --ng
```

update item-detail.component.html

```
<ActionBar title="Details"></ActionBar>

<FlexboxLayout flexDirection="column">
  <FlexboxLayout class="m-4">
    <Label class="text-3xl text-gray-400" [text]="item()?.id + '. '"></Label>
    <Label class="text-3xl" [text]="item()?.name"></Label>
  </FlexboxLayout>
  <FlexboxLayout class="m-4">
    <Label class="text-3xl text-gray-400">
      <FormattedString>
        <Span [text]="item()?.id + '. '"></Span>
      </FormattedString>
    </Label>
    <Label class="text-3xl">
      <FormattedString>
        <Span [text]="item()?.name"></Span>
      </FormattedString>
    </Label>
  </FlexboxLayout>
  <Label class="text-xl m-4" [text]="item()?.role"></Label>
</FlexboxLayout>
```

When font scale is changed in Android, Label font size with FormattedString will remain unchanged.
![Image](https://github.com/user-attachments/assets/469da167-7274-45b4-a7f9-7315df64c4e2)

### Relevant log output (if applicable)

```shell

```

### Environment

```yaml
OS: macOS 15.2
CPU: (12) arm64 Apple M2 Pro
Shell: /bin/zsh

node: 22.16.0
npm: 10.9.2
nativescript: 8.9.2

# android
java: 17.0.14
ndk: Not Found
apis: 30, 31, 32, 33, 34, 35, 36
build_tools: 30.0.2, 30.0.3, 33.0.0, 33.0.1, 34.0.0, 35.0.0, 35.0.1
system_images: 
  - android-25 | Google APIs ARM 64 v8a
  - android-26 | Google APIs ARM 64 v8a
  - android-27 | Google APIs ARM 64 v8a
  - android-28 | Google ARM64-V8a Play ARM 64 v8a
  - android-29 | Google Play ARM 64 v8a
  - android-33 | Google APIs ARM 64 v8a
  - android-34 | Google APIs ARM 64 v8a
  - android-34 | Google Play ARM 64 v8a
  - android-35 | Google Play ARM 64 v8a
  - android-36 | Google Play ARM 64 v8a

# ios
xcode: 16.2/16C5032a
cocoapods: 1.16.2
python: Not Found
python3: 3.13.3
ruby: 3.3.7
platforms: 
  - DriverKit 24.2
  - iOS 18.2
  - macOS 15.2
  - tvOS 18.2
  - visionOS 2.2
  - watchOS 11.2
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~20.0.0",
  "@angular/common": "~20.0.0",
  "@angular/compiler": "~20.0.0",
  "@angular/core": "~20.0.0",
  "@angular/forms": "~20.0.0",
  "@angular/platform-browser": "~20.0.0",
  "@angular/platform-browser-dynamic": "~20.0.0",
  "@angular/router": "~20.0.0",
  "@nativescript/angular": "^20.0.0",
  "@nativescript/core": "~8.9.0",
  "rxjs": "~7.8.0",
  "zone.js": "~0.15.0"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~20.0.0",
  "@angular/compiler-cli": "~20.0.0",
  "@nativescript/android": "8.9.1",
  "@nativescript/ios": "8.9.2",
  "@nativescript/tailwind": "^2.1.0",
  "@nativescript/types": "~8.9.0",
  "@nativescript/webpack": "~5.0.0",
  "@ngtools/webpack": "~20.0.0",
  "tailwindcss": "~3.4.0",
  "typescript": "~5.8.0"
}
```

### Please accept these terms

- [x] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [x] This is a bug report
- [x] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
