### ISSUE TITLE
tsgo.exe sometimes consumes 55GB(!) of memory

### ISSUE THREAD

**Issue by Zlatkovsky** [NativeScript/NativeScript#10756]
### Issue Description

When using tsgo.exe (version 7.0.0-dev.20250630.1) with the latest VS Code insider (1.102.0-insider), the memory consumed sometimes balloons to up to 55GB! (Good thing my machine has 64GB).
And even in "normal" mode, it often hovers around 18GB.

The image below was from when it was ramping up to reach 55GB eventually; this is midway through:
![Image](https://github.com/user-attachments/assets/0dafb816-704d-417e-9dfd-bd91243e2f5e)

It has also caused my VS Code to crash:
![Image](https://github.com/user-attachments/assets/b2b251b9-e025-46b8-9cef-eda16d22e205)

And on two occasions my computer froze completely and required me to forcefully reboot it (though at that time, tsgo was at a relatively lower memory consumption, so maybe that wasn't related; or at least, not to memory, but something else in tsgo/VSCode)

Version: 1.102.0-insider (user setup)
Commit: 6ccdb0f1561e1723f5ff5dfb1e3c8c037b60e700
Date: 2025-06-30T05:03:46.894Z
Electron: 35.6.0
ElectronBuildId: 11847422
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
OS: Windows_NT x64 10.0.26120

### Reproduction

This is happening on a monorepo project that has a couple hundred individual packages. I work at Microsoft, feel free to reach out to me (look me up by name, Michael Zlatkovsky).

### Relevant log output (if applicable)

```shell

```

### Environment

```yaml
OS: Windows 11 10.0.26120
CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900K
Shell: Not Found
node: 22.16.0
npm: 10.9.2
nativescript: Not Found

# android
java: Not Found
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: Not Found
cocoapods: Not Found
python: Not Found
python3: Not Found
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@typescript/native-preview": "^7.0.0-dev.20250617.1"
},
"devDependencies": {}
```

### Please accept these terms

- [x] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [x] This is a bug report
- [x] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
