### ISSUE TITLE
Label.formattedText Spans don't seem to be styleable with CSS

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#1401]
Sample XML
``` XML
        <Label class="logo-label" textWrap="false">
            <Label.formattedText>
                <FormattedString>
                    <FormattedString.spans>
                        <Span text="MED" class="prefix" />
                        <Span text="PORTAL" class="postfix" />
                    </FormattedString.spans>
                </FormattedString>
            </Label.formattedText>
        </Label>
```

CSS
``` CSS
.prefix{
    background-color: red;
    color: red;
}

.postfix{
    background-color: blue;
    color: blue;
}
```

Result:
![image](https://cloud.githubusercontent.com/assets/1542376/12429733/e799719e-beb9-11e5-80bd-a3978cee7632.png)

The "logo-label" on the root label can be styled with margins\padding just fine... but the inner spans don't get anything.
