### ISSUE TITLE
Add support for CSS 3 animations & transitions

### ISSUE THREAD

**Issue by tzraikov** [NativeScript/NativeScript#1608]
This feature will allow adding animations directly through CSS code. Currently adding animations is possible only with JS(TypeScript) code. Making this feature available will separate the animation logic from the application one and the process of adding new animations will be easier. Moreover, it will be theoretically easy to use existing CSS3 animation libraries (e.g. [animate.css](https://daneden.github.io/animate.css/)). Adding support for CSS pseudo selectors will streamline the process of triggering animations by adding visual states (e.g. button1:highlighted).

In order to add initial support for CSS animations, the following CSS properties should be supported:
 
- [x] animation
- [x] animation-name
- [x] animation-delay
- [x] animation-duration
- [x] animation-iteration-count
- [x] animation-timing-function
- [x] @keyframes

The following animation properties could be implemented at later stages:
- [x] animation-direction
- [x] animation-fill-mode

In addition to animation properties, the following CSS property should be supported:
- [x] transform

Currently only the following properties are animatable in {N}:
- [x] opacity
- [x] backgroundColor
- [x] scaleX
- [x] scaleY
- [x] translateX
- [x] translateY
- [x] rotate
- [x] rotateX
- [x] rotateY

Example: 

```CSS
.button1 {
    background-color: white;
}

.button1:highlighted {
    animation-duration: 0.75s;
    animation-name: test;
}

@keyframes test {
from { background-color: red; }
  to { background-color: white; }
}
```

CSS animations can be improved further by implementing #1894 and #1895

**Comment by mikeres0** [comment]
+1

**Comment by myninka** [comment]
#1767

**Comment by PanayotCankov** [comment]
The following animation:
```
@keyframes intro-logo-bg-enter {
    from {
        transform: scale(10, 10);
    }
    to {
        transform: translate(0, -40);
    }
}
#intro-logo-bg {
    animation-name: intro-logo-bg-enter;
    animation-duration: 3;
    animation-timing-function: ease-out;
    animation-fill-mode: forwards;
}
```
Must leave the object after the animation scaled 1, 1 and translated 40 pixels down.
Currently it animates it properly but at the end the object jumps to scale 10 10 and probably 40 pixels down.

**Comment by PanayotCankov** [comment]
Consider allowing multiple animations to be chained using the `animation:` shorthand property, such as:
```
@keyframes anim1 {
    to {
         background-color: red;
    }
}
@keyframes anim2 {
    from {
        background-color: red;
    }
    to {
         background-color: green;
    }
}
div#myDiv {
    animation: anim1 2s ease-out, anim2 1s 2s forwards;
}
```

**Comment by PanayotCankov** [comment]
Consider supporting timing functions per keyframe:
``` CSS
@keyframes mymove {
    0% {
        transform: translate(0px, 0px);
        animation-timing-function: ease-out;
    }
    50% {
        transform: translate(0, 100px);
        animation-timing-function: ease-in;
    }
    100% { transform: translate(0, 200px); }
}
```
