### ISSUE TITLE
CSS animations from the application-wide .css file do not aply

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#1893]
The CSS animations from the application-wide *.css* (app.css) file do not apply. For example:
```css
.button {
    background-color: green;
}

.button_selected {
    animation-name: button_selected;
    animation-duration: 2s;
    animation-fill-mode: forwards;
}

@keyframes button_selected {
    from { background-color: yellow; }
    to { background-color: red; }
}
```
will output the following error:
```
JS: Error: Css styling failed: TypeError: Cannot set property 'button_selected' of undefined
```
