### ISSUE TITLE
Support for multiple css class per view

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#2330]
This is something very useful we have in web, that does not seem to work yet in {N}
```XML
<Label text="something" class="foo bar" />
```
```css
.foo { color: red; }
.bar { background-color: black;}
```
I would be expecting to see a black colored label with red text, but instead neither of the classes are applied.
