### ISSUE TITLE
Flip animation (rotateX & rotateY) missing?

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#2349]
According to this issue here https://github.com/NativeScript/NativeScript/issues/1608 rotateY and rotateX should be supported. Can someone show us an example of how to use it?

I've tried with the following:
```css
@keyframes flipper {
    from { transform: rotateY(0); }
    to { transform: rotateY(180);  }
}
```
But the app crashes with the following error message: `No animation property specified`

Using CLI & runtime: 2.0.1
