### ISSUE TITLE
iOS keyframe translate animation jumps back to original location or throws an error.

### ISSUE THREAD

**Issue by Rachnerd** [NativeScript/NativeScript#2597]
### Tell us about the problem
Keyframe animations jump back to their "from" state after the animation is finished in iOS. 
In Android the animation ends with the "to" state as expected.

Before posting this issue I also scaled the animation from small to normal size. On iOS this also jumps back to the "from" scale but was resolved by adding: "animation-fill-mode: forwards;" to the css class. However this didn't fix the translate behavior.

iOS sometimes does behave like expected but throws an Animation Cancelled error. 

(We use webpack + Angular 2).
```
CONSOLE ERROR file:///app/bundle.js:29891:28: Unhandled Promise rejection: Animation cancelled. ;
Zone: <root> ; Task: Promise.then ; Value: Error: Animation cancelled. _rejectAnimationFinishedPromise@file:///app/bundle.js:11653:32
animationFinishedCallback@file:///app/bundle.js:11158:58
animationDidStopFinished@file:///app/bundle.js:11110:36
UIApplicationMain@[native code]
start@file:///app/bundle.js:5462:27
nativeScriptBootstrap@file:///app/bundle.js:222:23
file:///app/bundle.js:64:37
__webpack_require__@file:///app/bundle.js:21:34
file:///app/bundle.js:41:37
anonymous@file:///app/bundle.js:42:12
evaluate@[native code]
moduleEvaluation@[native code]
[native code]
promiseReactionJob@[native code]
```
### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.2.1
- Cross-platform modules: 2.2.0
- Runtime(s): 2.2.0

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```css
@keyframes hide-to-left {
    from {
        transform: translate(0,0);
    }
    to {
        transform: translate(-200,0);
    }
}
.wizard-page-leave {
    animation-name: hide-to-left;
    animation-duration: .4s;
    animation-fill-mode: forwards;
}
```
```html
<StackLayout class="wizard-page-leave">
    <Label text="Some content"></Label>
</StackLayout>
```

Android: StackLayout ends 200 left of the "from" state.
iOS: StackLayout ends where it started.

Added the class on the first page of the app and it behaved like normal but throws an error.
On the second page the same class animates and jumps back.
