### ISSUE TITLE
SegmentedBar CSS color not applied correctly when items are bound

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#267]
Example:
```XML
<Page loaded="MyPageLoaded">
  <StackLayout>
    <SegmentedBar items="{{ someItems }}" />
  </StackLayout>
</Page>
```
```JavaScript
function MyPageLoaded(args) {
    var page = args.object;
    page.bindingContext = { someItems: [{ title: "One" }, { title: "Two" }, { title: "Three" }] };
}
exports.MyPageLoaded = MyPageLoaded;
```
```CSS
SegmentedBar
{
    background-color: red;
    color: blue;
    font-size: 30;
}
```
