### ISSUE TITLE
Android: ActionBar Images not displaying correctly (working in 2.2.1, broken in master)

### ISSUE THREAD

**Issue by colinskow** [NativeScript/NativeScript#2674]
I installed `tns-core-modules` from master and the logo image in my ActionBar is not displaying correctly on android. It displays correctly in the 2.2.1 release.

```xml
<ActionBar title="VRX" class="ab-primary">
  <StackLayout orientation="horizontal"
               ios:horizontalAlignment="center"
               android:horizontalAlignment="center">
    <Image src="res://vrx_logo" class="action-image"></Image>
  </StackLayout>
</ActionBar>
```

Here's the CSS:

```css
ActionBar.ab-primary {
    background-color: #1A237E;
    color: white;
}

.action-image {
    height: 40;
    vertical-align: center;
    horizontal-align: center;
}
```

2.2.1 Displays Correctly
![screenshot_20160903-202205](https://cloud.githubusercontent.com/assets/5303269/18229087/1e6eb850-721f-11e6-9977-80e89d1cf930.png)

2.4.0 (Master) Displays Incorrectly
![screenshot_20160903-201019](https://cloud.githubusercontent.com/assets/5303269/18229088/23170376-721f-11e6-8c9a-ee5458b22937.png)
