### ISSUE TITLE
[2.3.0] Image gets covered with color of Page color property

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#2733]
**Platform:** iOS
**TNS:** 2.3.0

If I set this in app.css:

```css
Page {
  background-color: #ffffff;
  color: #ff0000;
}
```

Then add an Image, with a functional src value. The Image gets covered with the color inherited from the color property of Page. This makes the Image not rendering the image at all, and acts more like a colored box. I feel like this is related to #2649.
