### ISSUE TITLE
Be CSS standard compliant?

### ISSUE THREAD

**Issue by vjeux** [NativeScript/NativeScript#29]
The filename is .css and it has the same parser but it is not compatible with CSS.

- horizontal-align doesn't exist
- font-size and margin need `px` at the end

I wonder what motivated the deviation? It is certainly easier to write but at the same time it's not CSS anymore. It is likely to cause many confusion.

```css
.title {
    font-size: 30;
    horizontal-align: center;
    margin:20;
}
```
