### ISSUE TITLE
Unable to set padding using px unit

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#3274]
**Platform:** iOS
**TNS:** 2.4.0

```css
StackLayout {
  padding-left: 5;
  padding-left: 5px; /* Removing this line will make it work */
}
```

Not sure if this has already been worked on. But at least now it's been reported.
