### ISSUE TITLE
[Enhancement] Ability to register custom css rules for plugins with multiple UI elements

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#4267]
So in the DropDown plugin I want to add ability to define different styles for the label that shows the selected value and the popup/spinner (https://github.com/PeterStaev/NativeScript-Drop-Down/issues/44). Is there any built in way that I can achieve this? I first thought to add two separate properties that would define a class for the label and a class for the spinner, but that does not seem very right. Also from what I see there is no method that can return to me the evaluated style properties for a given css class in the current scope. Ideally I want to be able to have something like:
```css
/* styles only the label */
.drop-down {
  background-color: red;
}
/* styles the spinner */
.drop-down>option {
  background-color: blue;
}
```
Then somehow "register" in my plugin that it has an inner UI control named `option` and then be able to use the new property system's `setNative` functions to style the native element of either the main widget or any secondary UI elements that widget has registered.
