### ISSUE TITLE
Observable notify mutable listeners list

### ISSUE THREAD

**Issue by SBD580** [NativeScript/NativeScript#4392]
In Observable.notify method all listeners are executed (in reverse order) by index.
If some listener remove another listener(s) this will shrink the array and the next index might be invalid

```
Calling js method onBackPressed failed
                                                                      
  TypeError: Cannot read property 'thisArg' of undefined
  File: "file:///data/data/<package>/files/app/tns_modules/tns-core-modules/data/observable/observable.js, line: 145, column: 21
  
  StackTrace: 
	Frame: function:'Observable.notify', file:'file:///data/data/<package>/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 145, column: 22
	Frame: function:'ActivityCallbacksImplementation.onBackPressed', file:'file:///data/data/<package>/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 746, column: 29
	Frame: function:'NativeScriptActivity.onBackPressed', file:'file:///data/data/<package>/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 28, column: 25
```

I'm having this on 2.5.2 but seems like the code in 3.x
