### ISSUE TITLE
ScrollView css background-repeat doesn't tile properly

### ISSUE THREAD

**Issue by Roar1827** [NativeScript/NativeScript#4583]
### Did you verify this is a real problem by searching [Stack Overflow](http://stackoverflow.com/questions/tagged/nativescript) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes, I tried to find any similar problems, I haven't seen this reported elsewhere.

### Tell us about the problem

When using a repeated background image inside of a scroll view, it resets tiling after the view port ends.

### Which platform(s) does your issue occur on?
Both

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```xml
<ScrollView class="repeat-bg">
	<WrapLayout>
		<StackLayout *ngFor="let test of tests; let i = index">
	    	    <Image src="{{i.src}}" height="100"></Image>
		</StackLayout>
	</WrapLayout>
</ScrollView>
```

```css
.repeat-bg {
	background-image: url("~/assets/test.png");
	background-repeat: repeat-y;
	background-size: 100% 248;
}
```

The background will repeat correctly until the bottom of the screen. At that point it will start the image again at the top left of the next view port.
