### ISSUE TITLE
Padding value is not set correctly when a more specific css rule is added and removed

### ISSUE THREAD

**Issue by erkanarslan** [NativeScript/NativeScript#5065]
### Did you verify this is a real problem by searching [Stack Overflow]
Yes

### Tell us about the problem
There is a label element which always has a CSS class `test`. That css class sets its padding to a value like this:

````css
.test {
    padding: 8;
}
````
Another css class `test2` is added to and removed from the label element dynamically. It is defined like this:
````css
.test2 {
    padding-left:16;
}
````
Notice that `test2` has a more specific padding rule than `test`. When `test2` is removed from the label padding-left is set to 0. Not 8.

But if I define `test` class as shown below, it works correctly.
````css
.test {
    padding: 8;
    padding-left:8;
}
````

### Which platform(s) does your issue occur on?
Android. Not tested on iOS.

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.2.1
- Cross-platform modules: 3.3.0
- Runtime(s): 3.2.0
