### ISSUE TITLE
TabView Icons font-size affects all text in inner views

### ISSUE THREAD

**Issue by shabib3** [NativeScript/NativeScript#5074]
### Tell us about the problem
When I put icon from any kind of icons font-family source in TabViewItem's head I am trying change his font-size, the css affects correctly on the size on the icon, but at the time it affects all text font-size inside the inner tabView children.
I implemented it that way -> [TabView adding icons example](https://docs.nativescript.org/angular/code-samples/ui/tab-view#tab-view-icon-fonts)

### Which platform(s) does your issue occur on?
Android...didn't check on IOS

### Please tell us how to recreate the issue in as much detail as possible.
HTML:
```
<TabView #myTab selectedIndex="0" class="tab-icon">
    <StackLayout *tabItem="{title: '&#xf0c0;'}">
        <Label text="foooo"></Label>
    </StackLayout>
    <StackLayout *tabItem="{title: '&#xf133;'}">
        <Label text="bar"></Label>
    </StackLayout>
    <StackLayout *tabItem="{title: '&#xf0c9;'}">
        <Label text="Yoooo"></Label>
    </StackLayout>
</TabView>
```

css:
```
.tab-icon {
    font-family: 'FontAwesome';
    font-size: 40;
}
```

You can see that the Labels are changing theirs size, while I want to change only the Icons size.

How can I do it? something like `tab-text-size` like you have `tab-text-color`?

Thanks :)

**Comment by NickIliev** [comment]
@shabib3 

You can explicitly set the CSS styling for the labels using the nested CSS styling convention
For example
```CSS
/* using class name to apply styles for all nested labels */
.tab-icon Label {
    color: green;
    font-size: 24;
}

/* using class="label" for the wanted label */
.tab-icon .label {
    color: red;
    font-size: 18;
}

```
