### ISSUE TITLE
textWrap NativeScript property is not accessible via CSS

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#5355]
As stated in [this documentation section](https://docs.nativescript.org/ui/styling#accessing-nativescript-component-properties-with-css) the NativeScript specific properties should be accessible via CSS
with syntax like
```CSS
Label {
    text-wrap: true;
}

StackLayout {
    orientation: horizontal;
}
```

However, the `text-wrap` can't be set via CSS. Playground demo demonstrating the issue can be found [here](https://play.nativescript.org/?template=play-tsc&id=IUOq0x) - reported via the feedback form.
