### ISSUE TITLE
border-radius CSS property not applying properly to image on Android

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#540]
border-radius seems to be applying on iOS fine, but on android you can see that it's behind the image itself and not applying to the image

Using the following CSS:

``` css
.header-image{
  margin: 15px 0 0 15px;
  border-radius: 30;
  border-color: gray;
  border-width: 0.5;
  height:60;
  width:60;
}
```

Produces (iOS):
![screen shot 2015-08-03 at 4 22 58 pm](https://cloud.githubusercontent.com/assets/5018471/9030794/f71a6ff8-39fb-11e5-8bd9-adf6527b1c4c.png)

and produces (android):
![screen shot 2015-08-03 at 4 23 06 pm](https://cloud.githubusercontent.com/assets/5018471/9030797/00f261d4-39fc-11e5-94a1-7c9e91f761ac.png)

Note that you can see a couple of pixels to the left of the image, which I assume is the border-radius.
