### ISSUE TITLE
Highlighted pseudo class not working on IOS

### ISSUE THREAD

**Issue by markomiljkovic** [NativeScript/NativeScript#5461]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes

### Tell us about the problem
Highlighted pseudo selector not working on IOS not changing Background or Text color when tapping on Item

```
     <Button class="btn-outline btn-cancel m-10"
                                        text="Cancel" tap="cancel"/>
```

```
.btn-cancel {
color:red;
    background-color: geen;
}
 btn-cancel :highlighted  {
color:#fff;
    background-color: #8F8F8F;
}
```
### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4

**Comment by jogboms** [comment]
@markomiljkovic Maybe its just the github formatting, but the CSS code you wrote is not correct.
```css
.btn-cancel {
    color: red;
    background-color: green;
}
.btn-cancel:highlighted  {
    color: #fff;
    background-color: #8F8F8F;
}
```
