### ISSUE TITLE
Action repeats for recycled components

### ISSUE THREAD

**Issue by thedjdoorn** [NativeScript/NativeScript#6066]
### Tell us about the problem
Okay, so I have this ListView with custom components (card-like, contains about six labels, a button, and an image, so it's pretty complicated), where a user has the ability to bookmark an item by pressing a button in said component. The button press triggers a little bounce animation and changes the color of the button. If the list overflows, and about 6 components fit on my screen, every 6th item has the changed button, starting with the one you just pressed. I think this has something to do with Android recycling the components when you scroll through the ListView. How can I prevent this behavior?

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0
- Cross-platform modules: 4.0.0
- Runtime(s): 4.0.1

### Please tell us how to recreate the issue in as much detail as possible.
Create an overflowing Listview with some custom components, us ngClass and a property in the TypeScript file to make it interactive.
Enable the interaction in one of the items.
Scroll down.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

event-card-component.xml
``` xml
<StackLayout loaded="componentLoaded" class="nw-event-card">
    <GridLayout [nsRouterLink]="['/programma', event.id]" pageTransition="slideLeft"
                columns="*, auto, auto"
                rows="auto"
                class="nw-event">
        <StackLayout col="0" row="0">
            <Label class="nw-event-name" [text]="event.name" textWrap="true"></Label>
            <Label class="nw-event-data" [text]="speakerName"></Label>
            <Label class="nw-event-data" [text]="event.location ? event.location.name : ''"></Label>
            <Label class="nw-event-data data-bottom" [text]="event.category"></Label>
        </StackLayout>
        <FlexBoxLayout col="1" row="0" flexDirection="column" justifyContent="center">
            <Button (tap)="toggleBookmark()" [ngClass]="{'bounce':bookmarked}" class="btn btn-outline heart" text="&#xf004;">
            </Button> <!-- this is the button that triggers a bookmark -->
        </FlexBoxLayout>
        <Image col="2" row="0" [src]="speakerPhoto" stretch="aspectFill"
               class="nw-event-image"></Image>
    </GridLayout>
    <FlexBoxLayout class="nw-event-times" flexDirection="row">
        <!-- Scrolling messes this part up as well, the spacing between the labels changes or the labels disappear alltogether -->
        <Label class="nw-event-day" [text]="getDay()"></Label>
        <Label class="nw-event-time" [text]="event.startTime | date:'H:mm'"></Label>
        <Label class="nw-event-time" [text]="event.endTime | date:'H:mm'"></Label>
    </FlexBoxLayout>
</StackLayout>
```

event-card-component.ts
``` typescript
export class EventCardComponent implements OnChanges {

    @Input() event = new Event();
    @Output() bookmarkChanged = new EventEmitter<object>();
    speakerName = '';
    speakerPhoto = BackendService.DEFAULT_IMAGE;
    bookmarked = this.event.bookmarked;

//ngOnInit and the getDay method, not important right now


    toggleBookmark(){
        console.log("Bookmark tapped for " + this.event.id);
        let newState = !this.bookmarked;
        this.bookmarked = newState;
        this.bookmarkChanged.emit({id:this.event.id, newState:newState});
    }
}
```

event-card-component.css
``` css
.heart {
    font-family: "Font Awesome 5 Free" ,"fontawesome-regular-webfont","fontawesome-solid-webfont";
    font-size: 40pt;
    font-weight: 400;
    color: #e74c3c;
    background-color: rgba(255, 0, 0, 0.0);
    border-color:rgba(255, 0, 0, 0.0);
    border-width: 1;
}

.heart.bounce {
    font-family: "Font Awesome 5 Free" ,"fontawesome-solid-webfont";
    animation-name: bounce;
    animation-duration: 0.4s;
}

@keyframes bounce {
    0%{ transform:scale(0.8);}
    50%{ transform:scale(1.3);}
    75%{ transform:scale(0.9);}
    100%{ transform:scale(1);}
}
```
