### ISSUE TITLE
Branding fonts no works in ios only android

### ISSUE THREAD

**Issue by DavoBR** [NativeScript/NativeScript#6222]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?'

Yes, but none helped me

### Tell us about the problem
I am trying use the Branding fonts in my project, but I can not make it work in ios

you can see that example: [Custom Font Playground Sample](https://play.nativescript.org/?template=play-ng&id=6Pz1oU)

Screenshots from my devices

**IPhone 7: (IOS 12 Beta)**
![screenshot_ipone7](https://user-images.githubusercontent.com/498724/44624749-93b57800-a8c4-11e8-8cc4-a08e9b8903a7.jpg)

**Android: (Amazon Fire 7)**
![screenshot_androidfire7](https://user-images.githubusercontent.com/498724/44624750-944e0e80-a8c4-11e8-936d-887cc1e453a5.png)

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
NativeScript Playground

**Comment by NickIliev** [comment]
@DavoBR the thing is that iOS is looking for the **font name** while Android is looking for the **font file name**.(see [here](https://stackoverflow.com/a/40660013/4936697) for details). So in your case after opening the font on iOS with the default font application it seems that the font name is just **Branding**.

```CSS
.branding-m {
    font-family: Branding, BrandingBranding-Medium, Branding Medium;
    color: orangered;
}

.branding-l {
    font-family: Branding, Branding-Light, Branding Light;
    color: slateblue;
}
```

[Working demo Playground ](https://play.nativescript.org/?template=play-ng&id=6Pz1oU&v=2)
