### ISSUE TITLE
Allow property setting in CSS to work with the cascade

### ISSUE THREAD

**Issue by bundyo** [NativeScript/NativeScript#6287]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem
Currently NativeScript setting allows setting component properties through CSS, which is a great help when a CSS property is missing. For instance setting the StackLayout's orientation is not implemented as a CSS property and works by setting the component one. This is great help, but currently rather limited - this is only supported on the root level of the cascade, e.g. this works:

```css
StackLayout {
   orientation: horizontal;
}
```

and this doesn't:

```css
ActionBar ActionItem StackLayout {
   orientation: horizontal;
}
```

I know that using a class at the root level also works, but since we need a better core theme for NativeScript, it would be of great help for its users to not be required to set a class in order to apply the styling. 

And it would be a helpful workaround for all the CSS properties that are not yet implemented.

### Which platform(s) does your issue occur on?
iOS/Android/Both
