### ISSUE TITLE
CSS doesn't work with a selector which includes ActionItem

### ISSUE THREAD

**Issue by bundyo** [NativeScript/NativeScript#6288]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

Yes

### Tell us about the problem
When ActionItem is part of the selector, CSS properties don't get applied - as if the ActionItem doesn't exist as a real element (which is probably true), e.g. this works:

```css
ActionBar Label {
   text-transform: uppercase;
}
```

and this doesn't:

```css
ActionBar ActionItem Label {
   text-transform: uppercase;
}
```

### Which platform(s) does your issue occur on?
Android
