### ISSUE TITLE
CSS linear-gradient doesn't work for ActionBar background

### ISSUE THREAD

**Issue by bundyo** [NativeScript/NativeScript#6313]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem
Setting ActionBar's background to linear-gradient doesn't work.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- Cross-platform modules: 4.2.x

### Please tell us how to recreate the issue in as much detail as possible.
https://play.nativescript.org/?id=MJ30W7&v=3

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```css
.action-bar {
    background-image: linear-gradient(to bottom, rgba(0,0,0,0), rgba(0,0,0,.2));
}
```
