### ISSUE TITLE
Ability to style other native widgets

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#642]
It would be great to be able to use CSS to style the ProgressBar and Switch.

The progress bar could have:
* backgroundColor
* color (the bar itself)
* width and height
* borderRadius (possibility to square it off)

The switch would be much the same, but not sure how possible it is.

**Comment by hshristov** [comment]
Hi @lscown,

you should be able to style these properties even now. They are defined on the View class so all widgets support setting these in CSS.

**Comment by lscown** [comment]
Hey there,

Yes, it does style like you'd expect the view to be styled, however - this is not how you'd expect these elements to style.

So:
```css
.switch {
  margin: 10;
  background-color: red;
  color: yellow;
  width: 70;
  height: 20;
}

.progress {
  margin: 10;
  background-color: red;
  color: yellow;
  width: 400;
  height: 20;
}
```

Comes out:
![screen shot 2015-09-03 at 9 37 47 am](https://cloud.githubusercontent.com/assets/5018471/9645433/a8c39c4e-521f-11e5-850a-f3e3e7067aa4.png)

But rather it would be good to be able to style individual parts of the component. Not sure how possible this is, or whether you want custom CSS properties.

Cheers
