### ISSUE TITLE
CSS pseudo selector `:active` (alias `:highlighted`) broken when a button is created with FormattedString

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#6431]
CSS pseudo selector `:active` (alias `:highlighted`) broken when btn created with FormattedString

Example
main-page.xml
```XML
<Button (tap)="login()" >
            <FormattedString>
                <Span [text]="loginText + '\n'" fontSize="28"></Span>
                <Span [text]="descText" fontSize="12" ></Span>
            </FormattedString>
</Button>
```

main-page.css
```CSS
Button {
    background-color:#1b1d1d;
    color: #E8EAEB;
}

Button:active {
    background-color:#E8EAEB;
    color: #1b1d1d;
}
```

**Note**: The case seems to be reproducble only when using `Button` global styles in `app.css` and a Button created via `FormattedString`

app.css
```CSS
Button {
    color: #343838;
}
```

Demo application demonstrating the above case canb e found [here](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/NativeScript/issue-6431)

Broken with `tns-core-modules` 5.0.0 - working with 4.2.0
