### ISSUE TITLE
Cannot read property '_domId' of undefined when using relative path

### ISSUE THREAD

**Issue by stevenspiel** [NativeScript/NativeScript#6709]
**Environment**
```
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.2.0-2018-12-14-12741 version and is up to date.
✔ Component tns-core-modules has 5.1.0 version and is up to date.
✔ Component tns-android has 5.1.0 version and is up to date.
✔ Component tns-ios has 5.1.0 version and is up to date.
```

I'm using node `v10.13.0`

**Describe the bug**
TLDR: it's not ok to use a relative path in `app.run`.

bad:

```ts
app.run({ moduleName: './main-page' });
```

good

```ts
app.run({ moduleName: 'main-page' });
```

When running `tns run android` or `tns run ios`, or even `tns run ios --hmr`, the apps run fine. When I add `--hmr` or `--bundle` with android, I get:

```
Successfully synced application org.stevenspiel.cattleapp on device emulator-5554.
Will emit event liveSyncStarted with data { projectDir: '/Users/steven/mobile/examples/demo',
  deviceIdentifier: 'emulator-5554',
  applicationIdentifier: 'org.stevenspiel.cattleapp' }
Project dir from hooksArgs is: /Users/steven/mobile/examples/demo.
Hooks directories: [ '/Users/steven/mobile/examples/demo/hooks' ]
AfterHookName for command liveSync is after-liveSync
chromium: [INFO:library_loader_hooks.cc(140)] Chromium logging enabled: level = 0, default verbosity = 0
12-14 09:38:15.787  7707  7707 I cr_BrowserStartup: Initializing chromium process, singleProcess=false
JS: Firebase is ready
12-14 09:38:15.923  7707  7707 E AndroidRuntime: 	at com.tns.Runtime.callJSMethodNative(Native Method)
12-14 09:38:15.923  7707  7707 E AndroidRuntime: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
12-14 09:38:15.923  7707  7707 E AndroidRuntime: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
12-14 09:38:15.923  7707  7707 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:987)
12-14 09:38:15.923  7707  7707 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
12-14 09:38:15.923  7707  7707 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.stevenspiel.cattleapp/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: TypeError: Cannot read property '_domId' of undefined
System.err: File: "file:///data/data/org.stevenspiel.cattleapp/files/app/vendor.js, line: 62241, column: 46
System.err:
System.err: StackTrace:
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.stevenspiel.cattleapp/files/app/vendor.js', line: 62241, column: 47
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.stevenspiel.cattleapp/files/app/vendor.js', line: 62090, column: 14
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/activity.js.NativeScriptActivity.onCreate', file:'file:///data/data/org.stevenspiel.cattleapp/files/app/vendor.js', line: 60031, column: 25
System.err:
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
System.err: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:105)
System.err: 	at android.os.Looper.loop(Looper.java:164)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: Caused by: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: TypeError: Cannot read property '_domId' of undefined
System.err: File: "file:///data/data/org.stevenspiel.cattleapp/files/app/vendor.js, line: 62241, column: 46
System.err:
System.err: StackTrace:
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.stevenspiel.cattleapp/files/app/vendor.js', line: 62241, column: 47
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.stevenspiel.cattleapp/files/app/vendor.js', line: 62090, column: 14
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/activity.js.NativeScriptActivity.onCreate', file:'file:///data/data/org.stevenspiel.cattleapp/files/app/vendor.js', line: 60031, column: 25
System.err:
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:987)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: 	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
System.err: 	at android.app.Activity.performCreate(Activity.java:6975)
System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
System.err: 	... 9 more
JS: [app.js]: Uncaught NativeScript Error: Error: The application crashed because of an uncaught exception. You can look at "stackTrace" or "nativeException" for more detailed information about the exception.
```

Line 62241 (and surrounding lines) of my vendor.js file:

```js
ActivityCallbacksImplementation.prototype.setActivityContent = function (activity, savedInstanceState, fireLaunchEvent) {
        var shouldCreateRootFrame = application.shouldCreateRootFrame();
        var rootView = this._rootView;
        if (frame_common_1.traceEnabled()) {
            frame_common_1.traceWrite("Frame.setActivityContent rootView: " + rootView + " shouldCreateRootFrame: " + shouldCreateRootFrame + " fireLaunchEvent: " + fireLaunchEvent, frame_common_1.traceCategories.NativeLifecycle);
        }
        if (!rootView) {
            var mainEntry = application.getMainEntry();
            var intent = activity.getIntent();
            if (fireLaunchEvent) {
                rootView = notifyLaunch(intent, savedInstanceState);
            }
            if (shouldCreateRootFrame) {
                var extras = intent.getExtras();
                var frameId = -1;
                if (extras) {
                    frameId = extras.getInt(INTENT_EXTRA, -1);
                }
                if (savedInstanceState && frameId < 0) {
                    frameId = savedInstanceState.getInt(INTENT_EXTRA, -1);
                }
                if (!rootView) {
                    rootView = getFrameByNumberId(frameId) || new Frame();
                }
                if (rootView instanceof Frame) {
                    rootView.navigate(mainEntry);
                }
                else {
                    throw new Error("A Frame must be used to navigate to a Page.");
                }
            }
            else {
                rootView = rootView || builder_1.createViewFromEntry(mainEntry);
            }
            this._rootView = rootView;
/* 62241 */   activityRootViewsMap.set(rootView._domId, new WeakRef(rootView)); 
        }
        if (shouldCreateRootFrame) {
            rootView._setupUI(activity);
        }
        else {
            rootView._setupAsRootView(activity);
        }
        activity.setContentView(rootView.nativeViewProtected, new org.nativescript.widgets.CommonLayoutParams());
    };
```

In an earlier version of node (v8), I was getting a different error:

```
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
```

This might be something worth putting in the documentation or something to support. I was banging my head against a wall for a long time trying to figure it out.
