### ISSUE TITLE
Add support for :focus psudoclass on TextField/TextView

### ISSUE THREAD

**Issue by bundyo** [NativeScript/NativeScript#7395]
Currently the only way to style the focus state in {N} is to attach focus/blur events on the TextField and change classes. Adding support for :focus psudoclass will be of great help, like this:

```scss
TextView,
TextField {
    border-width: 1;
    border-color: #999;

    &:focus {
        border-color: red;
    }
}
```
