### ISSUE TITLE
[Tabs] TabStripItem selection highlight not visible with TabStripItem background color set

### ISSUE THREAD

**Issue by manoldonev** [NativeScript/NativeScript#7494]
**Environment**
 - CLI: rc
 - Cross-platform modules: rc
 - Android Runtime: rc

**Describe the bug**
The TabStripItem selected / highlight indicator is not visible in case TabStripItem background color is set.

**To Reproduce**
Use the following setup (also visible in e2e/ui-tests-app -> tabs -> background-color example):
``` xml
<Tabs>
  <TabStrip>
      <TabStripItem title="First" class="special"></TabStripItem>
      <TabStripItem title="Second"></TabStripItem>
  </TabStrip>

  <TabContentItem class="special">
      <GridLayout>
        <Label text="First View" />
      </GridLayout>
  </TabContentItem>

  <TabContentItem>
      <GridLayout>
        <Label text="Second View" />
      </GridLayout>
  </TabContentItem>
</Tabs>
```
``` css
TabStripItem.special {
  background-color: teal;
}

TabStripItem.special:active {
  background-color: yellowgreen;
}
```

**Expected behavior**
Highlight indicator should be visible if tabstripitem is selected no matter whether any css is applied.
