### ISSUE TITLE
[Tabs] Cannot change active text color for selected tabstripitem

### ISSUE THREAD

**Issue by manoldonev** [NativeScript/NativeScript#7507]
**Environment**
 - CLI: 6.0.0
 - Cross-platform modules: 6.0.1
 - Android Runtime: 6.0.0
 - iOS Runtime: 6.0.0

**Describe the bug**
Cannot change text color for selected tabstripitem applied via "active" pseudoselector.

**To Reproduce**
Use the following snippet (also available in e2e/ui-tests-app -> tabs -> color example):
``` xml
  <Tabs>
    <TabStrip>
        <TabStripItem title="First" class="special"></TabStripItem>
        <TabStripItem title="Second"></TabStripItem>
    </TabStrip>

    <TabContentItem class="special">
        <GridLayout>
          <Label text="First View" />
        </GridLayout>
    </TabContentItem>

    <TabContentItem>
        <GridLayout>
          <Label text="Second View" />
        </GridLayout>
    </TabContentItem>
  </Tabs>
```
``` css
Tabs {
  color: gold;
}

TabContentItem.special {
  color: olive;
}

TabStrip {
  color: skyblue;
}

TabStripItem.special {
  color: teal;
}

TabStripItem.special:active {
  color: yellowgreen;
}
```

**Expected behavior**
Should be able to change text color for selected tabstripitem applied via "active" pseudoselector.
