### ISSUE TITLE
[BottomNavigation][Tabs][iOS] TabStripItem font icon doesn't apply own classes

### ISSUE THREAD

**Issue by MartoYankov** [NativeScript/NativeScript#7547]
**Environment**
 - CLI: 6.0.1
 - Cross-platform modules: 6.0.1
 - Android Runtime: 6.0.0
 - iOS Runtime: 6.0.1

**Describe the bug**
On iOS TabStripItem font icon doesn't get the element's classes.

**To Reproduce**
Use the following setup (also visible in e2e/ui-tests-app -> tabs -> font icons example):
``` xml
  <Tabs>
    <TabStrip>
        <TabStripItem title="First" iconSource="font://&#xF10B;" class="font-awesome font-size color"></TabStripItem>
    </TabStrip>
  ...
  </Tabs>
```
``` css
.font-awesome {
  font-family: "FontAwesome";
}

.font-size {
  font-size: 36;
}

.color {
  color: blue;
} 
```

With this setup, the font icon isn't shown on iOS.

**Expected behavior**
The font icon should be shown properly.

**Additional Context**
This alternative works because of inheritance:
``` xml
  <Tabs class="font-awesome">
    <TabStrip>
        <TabStripItem title="First" iconSource="font://&#xF10B;" class="font-awesome font-size color"></TabStripItem>
    </TabStrip>
  ...
  </Tabs>
```
