### ISSUE TITLE
GridLayout rows/columns cannot be set from CSS

### ISSUE THREAD

**Issue by m-abs** [NativeScript/NativeScript#7783]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.0
 - Cross-platform modules: 6.1.0
 - Android Runtime: 6.1.0
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**

Normal view properties can be set from CSS in NativeScript, but we can't set `rows`/`columns` with a "*" value.
"*" is invalid CSS and the string "star" logs the error:
```bash
[OnePlus 3T]: Error: Failed to apply property [rows] with value [star] to GridLayout(21). Error: Cannot parse item spec from string: star
[OnePlus 3T]: Error: Failed to apply property [columns] with value [star] to GridLayout(21). Error: Cannot parse item spec from string: star
```

**To Reproduce**

Set rows/columns with a star/* value from CSS.
```css
GridLayout {
    rows: star;
    columns: star;
}
```

**Expected behavior**
I'd like
```css
GridLayout {
    rows: star;
    columns: star;
}
```

To behave the same as:
```HTML
<GridLayout rows="*" columns="*">
 ... STUFF ...
</GridLayout>
```

**Sample project**

https://play.nativescript.org/?template=play-ng&id=upsNyH&v=2

**Additional context**

**Comment by m-abs** [comment]
If I write the css like @manoldonev suggested on the PR, this isn't an issue.

```css
GridLayout {
    rows: \*;
    columns: \*;
}
```
