### ISSUE TITLE
Buttons not getting ripple back if border-radius is set back to 0 with additional CSS

### ISSUE THREAD

**Issue by bundyo** [NativeScript/NativeScript#7788]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - Android Runtime: 6.1.0

**Describe the bug**
If you set border-width, border-radius, background-image or clip-path, the Button ripple is gone, and can be got back by removing them later. However, if the CSS is added on the fly, the ripple is not restored. Something like this:

```css
Button {
    border-radius: 1;
	background-color: #ccc;
}
```
Then add this CSS later:
```css
.something Button {
    border-radius: 0;
}
```

**To Reproduce**
https://play.nativescript.org/?template=play-js&id=vjUfza&v=2

**Expected behavior**
The ripple to be restored
