### ISSUE TITLE
iOS sets a white background on modals instead of transparent

### ISSUE THREAD

**Issue by alexbrbr** [NativeScript/NativeScript#7924]
Hello, 
thanks for your help.

**Environment**
 - CLI: "tns-ios": {
            "version": "6.1.1"
 - iOS Runtime: 12.4.1
 - Plugin(s): _

**Describe the bug**
When opening a modal on iOS, the background of the modal cannot be transparent to display the content behind the modal. It is transparent during the animation then at the end a white background is added.

**To Reproduce**
```ts
// home.component.ts
        const options = {
            context: {},
            viewContainerRef: this.vcRef,
            fullscreen: true
        };
        this.modalService.showModal(TestComponent, options);
```
```css
/*test.component.css*/
.test {
        /* inside this margin we should see the home component in the , instead we get a white background */
	margin-top: 150;
	background-color: orange; 
}
```
https://play.nativescript.org/?_ga=2.140130864.227599284.1570541779-1662554929.1566205673&template=play-ng&id=CkwdrX

**Expected behavior**
In the provided example I should have a red background on top of the orange modal.

**Sample project**
https://play.nativescript.org/?_ga=2.140130864.227599284.1570541779-1662554929.1566205673&template=play-ng&id=CkwdrX
