### ISSUE TITLE
(android) Setting border or border-radius to Buttons removes ripple

### ISSUE THREAD

**Issue by bundyo** [NativeScript/NativeScript#8036]
- Cross-platform modules: 6.2
 - Android Runtime: 6.2

**Describe the bug**
Setting any border or border-radius to Buttons (probably other elements) will remove their ripple effect on Android.

**To Reproduce**
```css
.ns-root Button {
    border-width: 1;
    border-color: red;
}
```

**Expected behavior**
The button to have a ripple.

This is a transfer of NativeScript/theme#151 bug.
