### ISSUE TITLE
Cannot set color of TextField using css

### ISSUE THREAD

**Issue by tillsanders** [NativeScript/NativeScript#8289]
**Describe the bug**
I tried to set various properties of a TextField, including (but possibly not limited to) color, border-width, border-color. CSS definitions didn't result in the expected outcome. Only setting these attributes directly on the element works.

**To Reproduce**
1. Add a TextView.
2. Try setting the color of the TextView using an attribute (`<TextField color="red" />`). Works.
3. Try setting the color of the TextView using CSS. Doesn't work.

**Expected behavior**
Apply color, etc. using CSS.

**Sample project**
https://play.nativescript.org/?template=play-js&id=JsOp89&v=5

**Comment by NickIliev** [comment]
@tillsanders its because you are using the `@nativescript/theme` which is setting a default themed colors based on the element selectors (`TextField`). 

Remove the theme and you will be able to modify the color
```CSS
/* @import '~@nativescript/theme/css/core.css';
@import '~@nativescript/theme/css/default.css'; */

TextField {
    color: blueviolet;
}

.tf {
    color: orangered;
}
```

If you want to use the theme and overwrite the default calss you could do it as follows:
```CSS
@import '~@nativescript/theme/css/core.css';
@import '~@nativescript/theme/css/default.css';

TextField.tf {
    color: orangered;
}
```

**Comment by tillsanders** [comment]
@NickIliev Thanks, that works! However, I would expect a simple class selector to work in combination with the theme as well, since it has a higher specificity.

I tried it in the Playground, but as you already indicated, it doesn't work that way:
https://play.nativescript.org/?template=play-js&id=JsOp89&v=10

Is this something that can be fixed?

**Comment by NickIliev** [comment]
@tillsanders you are right that the behavior is not as expected. So I've dug into this specific case, and it appears that after all the whole scenario is expected and is due to how NativeScript is handling the newly introduced **Dark Mode**. The thing is that there are [there light/dark mode-specific selectors ](https://docs.nativescript.org/ui/dark-mode#how-does-it-work)(which are also used by the Theme) which are changing the CSS specifity.

So, in two wrods, to be able to overwrite the element selector for **dark mode** you need to use **.ns-dark** CSS class and respectively **.ns-light** for the **light mode**.

```CSS
@import '~@nativescript/theme/css/core.css';
@import '~@nativescript/theme/css/default.css';

.ns-light TextField {
    color: blue;
}

.ns-dark TextField {
    color: red;
}

```
