### ISSUE TITLE
[Tabs] CSS styles not applied for TabStripItem {iOS only}

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#8345]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.4
 - Cross-platform modules:6.4.0
 - Android Runtime:6.4
 - iOS Runtime:6.4

**Describe the bug**

CSS (`color` and `background-color`) are not applied for **TabStripItem** elements of **Tabs**. Reproducible on iOS only.

Works as expected on Android.
Works as expected with **BottomNavigation**

**To Reproduce**
Use[ this test Playground ](https://play.nativescript.org/?template=play-tsc&id=R9esgF&v=2)and observe the styles in **app.css**

**Expected behavior**
See Android (or BottomNavigation)

**Sample project**
https://play.nativescript.org/?template=play-tsc&id=R9esgF&v=2

**Additional context**

Styling works when applied on **TabStrip**

**Comment by NickIliev** [comment]
Reported via t. 1453753

**Comment by NickIliev** [comment]
With NativeScript 6.5.0 the styling options for TabStrip are now expanded with two new properties:
- `selectedItemColor`
- `unSelectedItemColor`

Here s a basic example on how we could style the TabStrip component via CSS
```CSS
TabStrip {
    background-color: #79d2a6;
    highlight-color: green; /* color of the underline for the selected item */
    selected-item-color: yellow; /* text color of selelcted item + also sets the color of icon if the icon is Icon Font set via font://  */
    un-selected-item-color: blue; /* text color of all unselelcted items + also sets the color of icon if the icon is Icon Font set via font://*/
}
```

There are no options to style each TabStripItem individually - the styling for selected/unselected states is now supported via the above properties.
