### ISSUE TITLE
Unable to change background color of ActionBar installed on a device.

### ISSUE THREAD

**Issue by ElecTreeFrying** [NativeScript/NativeScript#8469]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: `6.5`
 - Android Runtime: `6.5`
 - Plugin(s): `nativescript-ui-sidedrawer`, `nativescript-material-ripple`

**Describe the bug**

Changing the background color of `ActionBar` in css works perfectly fine in emulator. 

Installing the app on a device, removes the background color set in css.

**To Reproduce**

``` html
<ActionBar class="action-bar"></ActionBar>
```

``` css
.action-bar {
  background-color: violet;
}
```

**Expected behavior**

Change background color of `ActionBar` installed on a device by css.

**Comment by NickIliev** [comment]
@ElecTreeFrying it works as expected on my side - see [this demo Playground](https://play.nativescript.org/?template=play-tsc&id=WXN4gV).

Note that if you are if the phone is with the dark mode you might need to set the new classes using those two special classes (see [the documentation](https://docs.nativescript.org/ui/dark-mode#how-does-it-work)).

```CSS

/* 
    You will need to use .ns-dark and .ns-light to overwrite dark/light modes
*/


/* This style will be applied on devis with dark mode enabled */
.ns-dark .my-action-bar {
    background-color: orangered;
    color: antiquewhite;
}

/* This style will be applied on devices with light mode enabled */
.ns-light .my-action-bar {
    background-color: blue;
    color: antiquewhite;
}
```

**Comment by ElecTreeFrying** [comment]
@NickIliev I tried adding this snippet to my app.scss

``` scss
.my-action-bar {
  background-color: #530034;
  ...
}
```

On my device, the color of `ActionBar` hasn't change.

![image](https://user-images.githubusercontent.com/19801459/77913540-023f9080-72c7-11ea-903a-cca2a393d215.png)

This is my previous setup. I added `.action-bar` class to all my `ActionBar`s.

``` scss
.action-bar {
  background-color: #530034;
  ...
}
```

Im using Angular with Nativescript.
