### ISSUE TITLE
[ActionBar] Background is not being applied on iOS

### ISSUE THREAD

**Issue by LouieTian0209** [NativeScript/NativeScript#9338]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.1
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - XCode Version:
 - Plugin(s):

**Describe the bug**
`background` attribute set in css on `ActionBar` is being applied normally on Android, but not on iOS.
```css
ActionBar {
	background: linear-gradient(180deg, rgba(0, 115, 150, 0.85) 0%, rgba(25, 160, 172, 0.85) 100%);
	color: white;
	padding: 0;
}
```
Android screenshot:
![2021-04-16_16-54](https://user-images.githubusercontent.com/53802606/115001227-10624e00-9ed6-11eb-94e8-5fa1ec8f38da.png)

iOS screenshot:
<img width="332" alt="截屏2021-04-16 下午4 45 46" src="https://user-images.githubusercontent.com/53802606/115001275-1821f280-9ed6-11eb-9280-3848ffc69ab3.png">

The ActionBar is still there on iOS and I am able to alter the background color with `background-color: black;`, but I need to set the background color with a gradient color value and only `background` attribute supports gradient color.
