### ISSUE TITLE
Not suport box-shadow and border radius on 8.1.0-alpha.4

### ISSUE THREAD

**Issue by vallemar** [NativeScript/NativeScript#9527]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ Component nativescript has 8.0.2 version and is up to date.
⚠ Update available for component @nativescript/core. Your current version is 8.1.0-alpha.4 and the latest available version is 8.0.8.
✔ Component @nativescript/ios has 8.0.0 version and is up to date.
✖ Component @nativescript/android is not installed.

**Describe the bug**
if you join border-radius and box-shadow the border will be applied but the box-shadow will not. This happens in version 8.1.0-alpha.4

```css
.card {
  border-radius: 25;
  background: white;
  box-shadow: 0 8 8 rgba(0, 0, 0, 0.25);
  height: 100;
  width: 100;
}
```
