### ISSUE TITLE
Please provide ARM64 Binaries for nativescript-ui plugins

### ISSUE THREAD

**Issue by cjohn001** [NativeScript/NativeScript#9636]
### Issue Description

I have seen that the nativescript-ui plugins were updated in order to support ARM64 archs  using XCFrameworks. I tried to build with these plugins for simulator and got the following errors:

nativescript-ui-autocomplete/platforms/ios/TNSAutoComplete.xcframework' is missing architecture(s) required by this target (arm64)
nativescript-ui-calendar/platforms/ios/TNSCalendar.xcframework' is missing architecture(s) required by this target (arm64)
nativescript-ui-gauge/platforms/ios/TNSGauge.xcframework' is missing architecture(s) required by this target (arm64)
nativescript-ui-core/platforms/ios/TNSCore.xcframework' is missing architecture(s) required by this target (arm64)

Seems like there is something wrong with the configuration of the XCFrameworks as the ARM64 binaries cannot be found by the linker. 

Would be great if you could add them.

### Environment

```yaml
OS: macOS 12.0.1
CPU: (10) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 16.13.0
npm: 8.1.2
nativescript: 8.1.4

# android
java: 11.0.10
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 13.1/13A1030d
cocoapods: 1.11.2
python: 2.7.18
python3: 3.8.9
ruby: 2.7.4
platforms:
  - DriverKit 21.0.1
  - iOS 15.0
  - macOS 12.0
  - tvOS 15.0
  - watchOS 8.0
```

### Dependencies

```json
"dependencies": {},
"devDependencies": {}
```

### 

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
