### ISSUE TITLE
`main` key on `nativescript.config.ts` is not working

### ISSUE THREAD

**Issue by luiguild** [NativeScript/NativeScript#9658]
### Issue Description

The `main` key in `nativescript.config.ts` is not working. You can try to change the entry point of the application but the CLI still keep using `package.json` `main` key as a reference.

The capacity to change the main entry point, and more, this entry point being disconnect from the `package.json` is very useful to build design systems libraries and many other things.

### Reproduction

- Start a fresh installation
- Change `main` on `package.json` to another file that is not the default entry point to another file
- Configure your `nativescript.config.ts` including your entry point on `main` key
- Try to run

### Relevant log output (if applicable)

```shell
Project successfully built.
The build result is located at: ...\app-debug.apk
Installing on device emulator-5554...
Successfully installed on device with identifier 'emulator-5554'.
Restarting application on device emulator-5554...System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{org.nativescript.name/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
```

### Environment

```yaml
OS: Windows 10 10.0.19043
CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Shell: Not Found
node: 16.4.2
npm: 7.11.2
nativescript: 8.1.4

# android
java: Not Found (just a PATH problem)
ndk: Not Found (just a PATH problem)
apis: 28, 29, 31
build_tools: 30.0.3
system_images:
  - android-29 | Google APIs Intel x86 Atom

# ios
xcode: Not Found
cocoapods: Not Found
python: Not Found
python3: Not Found
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
  "dependencies": {
    "@nativescript-community/ui-drawer": "0.0.31",
    "@nativescript/core": "~8.1.1",
    "@panter/vue-i18next": "^0.15.2",
    "i18next": "^21.3.3",
    "nativescript-vue": "~2.9.0",
    "nativescript-vue-navigator": "^1.2.0",
    "vuex": "^3.6.2"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/eslint-parser": "^7.11.5",
    "@babel/eslint-plugin": "^7.11.5",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/preset-env": "^7.4.5",
    "@nativescript/android": "8.1.1",
    "@nativescript/webpack": "~5.0.0",
    "@vue/cli-plugin-babel": "^3.9.0",
    "@vue/cli-plugin-eslint": "^3.9.0",
    "@vue/cli-service": "^4.1.2",
    "@vue/eslint-config-standard": "^4.0.0",
    "cross-env": "^7.0.3",
    "eslint": "^5.16.0",
    "eslint-plugin-babel": "^5.3.1",
    "eslint-plugin-vue": "^5.0.0",
    "nativescript-vue-template-compiler": "~2.9.0",
    "pug": "^3.0.1",
    "pug-plain-loader": "^1.0.0",
    "sass": "^1.43.4",
    "sass-loader": "^12.3.0"
  }
```

### 

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
