### ISSUE TITLE
java.lang.NoSuchMethodError for various native modules, on some devices

### ISSUE THREAD

**Issue by kajic** [NativeScript/NativeScript#9690]
### Issue Description

Possibly since upgrading to NativeScript 8, we're seeing a few different seemingly related issues in calling native js methods, but only on a few devices. 

For example:

```
Calling js method onCreateView failed
Error: java.lang.NoSuchMethodError: no non-static method "Lorg/nativescript/widgets/GridLayout;.addView(Ljava/lang/String;I)I"
```
(Samsung SM-A715F)

---

```
Unable to start activity ComponentInfo{com.ronigame.roni/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onActivityCreated failed
Error: java.lang.NoSuchMethodError: no non-static method "Landroid/app/ApplicationPackageManager;.getActivityInfo(Ljava/lang/String;I)I"
```
(Samsung SM-A715F)

---

```
Unable to start activity ComponentInfo{com.ronigame.roni/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
Error: java.lang.NoSuchMethodError: no non-static method "Landroidx/appcompat/app/AppCompatActivity;.setContentView(Ljava/lang/String;I)I"
```
(Pixel 6 Pro)

### Reproduction

I can't reproduce this on a device of my own.

### Environment

```yaml
OS: macOS 11.6
CPU: (8) x64 Intel(R) Core(TM) i7-1060NG7 CPU @ 1.20GHz
Shell: /bin/zsh
node: 14.15.1
npm: 7.5.6
nativescript: 8.1.4

# android
java: 1.8.0_291
ndk: Not Found
apis: 28
build_tools: 28.0.3
system_images: 
  - android-30 | Google APIs Intel x86 Atom

# ios
xcode: 13.1/13A1030d
cocoapods: 1.11.2
python: 2.7.16
python3: 3.9.8
ruby: 2.7.1
platforms: 
  - DriverKit 21.0.1
  - iOS 15.0
  - macOS 12.0
  - tvOS 15.0
  - watchOS 8.0
```

### Dependencies

```json
"dependencies": {
  "@klippa/nativescript-login": "^3.0.1",
  "@nativescript-community/push": "^1.1.9",
  "@nativescript-community/ui-lottie": "^1.0.0",
  "@nativescript-community/ui-material-tabs": "^5.2.31",
  "@nativescript/appversion": "^2.0.0",
  "@nativescript/core": "~8.1.1",
  "@nativescript/firebase": "^11.1.3",
  "@nativescript/iqkeyboardmanager": "^2.0.0",
  "@nativescript/localize": "^5.0.2",
  "@nativescript/social-share": "^2.0.4",
  "@nativescript/theme": "~3.0.1",
  "@nota/nativescript-webview-ext": "^8.0.0",
  "@nstudio/nativescript-pulltorefresh": "^3.0.1",
  "classnames": "^2.2.6",
  "nativescript-intl": "^4.0.2",
  "nativescript-sentry": "^2.0.1",
  "nativescript-sound-kak": "https://github.com/kajic/nativescript-sound.git",
  "nativescript-taptic-engine": "^2.1.0",
  "nativescript-vibrate": "^4.0.1",
  "nativescript-vue": "~2.9.0",
  "rxjs": "^7.0.0",
  "vuex": "^3.6.0",
  "vuex-persistedstate": "^4.0.0-beta.3"
},
"devDependencies": {
  "@nativescript/android": "~8.1.1",
  "@nativescript/ios": "~8.1.0",
  "@nativescript/types": "~8.1.0",
  "@nativescript/webpack": "^5.0.0-beta.9",
  "@sentry/webpack-plugin": "^1.14.0",
  "@types/node": "~14.6.2",
  "dotenv": "^8.2.0",
  "nativescript-vue-template-compiler": "~2.8.0",
  "sass": "~1.39.0",
  "typescript": "~4.3.5",
  "vue": "~2.6.12"
}
```

### 

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
