### ISSUE TITLE
RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 3848.

### ISSUE THREAD

**Issue by samiul-gtmi** [NativeScript/NativeScript#9692]
### Issue Description

I am trying to run my ios app on a physical device to test. It runs fine on iPhone emulator,  but it is being problematic on physical iPhone. Main two issues for me are-
- ```Error is: ENOENT: no such file or directory, scandir '/Users/user02/Library/MobileDevice/Provisioning Profiles/'.```
- ```UnhandledPromiseRejectionWarning: RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 3848.```

### Relevant log output (if applicable)

```
Issues checking in progress...
Updating runtime package.json with configuration values...
Project successfully prepared (ios)
File change detected. Starting incremental webpack compilation...
Building project...
Unable to apply changes on device: 9650bd112fc18df65a9f29e3bcb577f6c07e2a51. Error is: ENOENT: no such file or directory, scandir '/Users/user02/Library/MobileDevice/Provisioning Profiles/'.
(node:4144) UnhandledPromiseRejectionWarning: RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 4144.
    at /Users/user02/Desktop/shigoto/pan8/panama-sp/src/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4144) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4144) UnhandledPromiseRejectionWarning: RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 4144.
    at /Users/user02/Desktop/shigoto/pan8/panama-sp/src/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:4144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
### Environment

```yaml
OS: macOS 11.5.2
CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
Shell: /bin/zsh
node: 14.17.0
npm: 6.14.13
nativescript: 8.1.4

# android
java: 1.8.0_292
ndk: Not Found
apis: 28, 30
build_tools: 28.0.3, 30.0.3
system_images: 
  - android-28 | Google APIs Intel x86 Atom
  - android-30 | Google APIs Intel x86 Atom

# ios
xcode: 13.1/13A1030d
cocoapods: 1.11.2
python: 2.7.16
python3: 3.9.7
ruby: 2.6.6
platforms: 
  - DriverKit 21.0.1
  - iOS 15.0
  - macOS 12.0
  - tvOS 15.0
  - watchOS 8.0
```

### Dependencies

```json
"dependencies": {
  "@nativescript-community/ui-image": "^4.1.0",
  "@nativescript/background-http": "^5.0.2",
  "@nativescript/camera": "^5.0.9",
  "@nativescript/core": "8.0.2",
  "@nativescript/imagepicker": "^1.0.5",
  "@nativescript/localize": "^5.0.4",
  "@nativescript/theme": "^3.0.2",
  "install": "^0.13.0",
  "nativescript-barcodescanner": "4.1.2",
  "nativescript-carousel": "7.0.1",
  "nativescript-ui-sidedrawer": "~9.0.0",
  "numeral": "^2.0.6",
  "sprintf-js": "^1.1.2",
  "webpack": "^5.64.1",
  "webpack-cli": "^4.9.1"
},
"devDependencies": {
  "@nativescript/android": "8.0.0",
  "@nativescript/ios": "8.0.0",
  "@nativescript/types": "8.0.0",
  "@nativescript/webpack": "~5.0.1",
  "babel-traverse": "6.4.5",
  "babel-types": "6.4.5",
  "babylon": "6.4.5",
  "lazy": "1.0.11",
  "sass": "1.34.0",
  "tslint": "^5.9.1",
  "typescript": "~4.0.0"
}
```

### 

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
