### ISSUE TITLE
Unexpected Error "has underlying svelte-native code changed?" on ns run ios / ns run android

### ISSUE THREAD

**Issue by julianlaibach** [NativeScript/NativeScript#9704]
### Issue Description

When i run the Command ns run ios or ns run android the Project is builded succesfully but once the App is started it crashes with the Terminal Output below.

When i uncomment the else Block in "./node_modules/svelte-hmr/runtime/svelte-native/proxy-adapter-native.js" Line 132 everything works fine and the App is running

```
if (type === 'navigatedFrom') {
  this.navigatedFromHandler = handler
  if (ownOn) {
    originalNativeView.on = on
  } else {
    delete originalNativeView.on
  }
} else {
  throw new Error(
    'Unexpected call: has underlying svelte-native code changed?'
  )
}
```

My Plattform is an M1 Mac, ns doctor gives me no error output.

### Relevant log output (if applicable)

```shell
NativeScript encountered a fatal error: Uncaught Error: Unexpected call: has underlying svelte-native code changed?
at
originalNativeView.on(file: app/webpack:/simplemenu/node_modules/svelte-hmr/runtime/svelte-native/proxy-adapter-native.js:140:0)
at setWindowContent(file: app/webpack:/***/node_modules/@nativescript/core/application/index.ios.js:270:0)
at notifyAppStarted(file: app/webpack:/***/node_modules/@nativescript/core/application/index.ios.js:169:0)
at didFinishLaunchingWithOptions(file: app/webpack:/***/node_modules/@nativescript/core/application/index.ios.js:152:0)
at NotificationObserver.onReceive(file: app/webpack:/***/node_modules/@nativescript/core/application/index.ios.js:42:0)
```

### Environment

```yaml
OS: macOS 12.0.1
CPU: (10) x64 Apple M1 Pro
Shell: /bin/zsh
node: 14.15.1
npm: 8.3.0
nativescript: 8.1.5

# android
java: 15.0.2
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 13.1/13A1030d
cocoapods: 1.11.2
python: 2.7.18
python3: 3.9.7
ruby: 2.6.8
platforms: 
  - DriverKit 21.0.1
  - iOS 15.0
  - macOS 12.0
  - tvOS 15.0
  - watchOS 8.0
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "~8.1.1",
  "@nativescript/theme": "~3.0.1",
  "svelte-native": "~1.0.0"
},
"devDependencies": {
  "@nativescript/ios": "8.1.0",
  "@nativescript/types": "~8.1.1",
  "@nativescript/webpack": "~5.0.0",
  "svelte": "~3.44.0",
  "svelte-loader": "^3.1.2",
  "svelte-native-preprocessor": "^1.0.0",
  "svelte-preprocess": "^4.7.0",
  "typescript": "~4.3.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
