### ISSUE TITLE
Splash Screen does not appear correctly in Android 12

### ISSUE THREAD

**Issue by rbudnar** [NativeScript/NativeScript#9707]
### Issue Description

After upgrading an android device to android 12 or using an android 12 emulator, the splash screen image no longer appears when the app loads. This has been brought up in discord at least twice, but there has been no response or guidance.

Google has posted documentation on migrating splash screens here: https://developer.android.com/guide/topics/ui/splash-screen/migrate

### Reproduction

1. Set up an emulator that uses android 12 (api 31)
2. Create a new sample NS project using the ns cli (tested on 8.1.4). Note that I needed to follow the solution posted in https://github.com/NativeScript/NativeScript/issues/9659 and add `android:exported="true"` to the application node in the AndroidManifest.xml file
3. Run the project as usual (`ns debug android`, etc.) and observe the logo does not appear (the background does appear, though):
<details>

![image](https://user-images.githubusercontent.com/1072625/146646196-934122c9-b7c0-46b2-a86e-fe6591c4f9e9.png)
</details>

### Relevant log output (if applicable)

```shell
n/a
```

### Environment

```yaml
OS: Windows 10 10.0.19042
CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
Shell: Not Found
node: 12.18.1
npm: 6.14.5
nativescript: Not Found

# android
java: 1.8.0_192
ndk: Not Found
apis: 28, 29, 30, 31
build_tools: 29.0.3, 30.0.3, 31.0.0, 32.0.0, 32.0.0
system_images:
  - android-28 | Intel x86 Atom_64
  - android-28 | Google APIs Intel x86 Atom
  - android-28 | Google Play Intel x86 Atom
  - android-29 | Google APIs Intel x86 Atom
  - android-30 | Google APIs Intel x86 Atom
  - android-30 | Google APIs Intel x86 Atom_64
  - android-30 | Google Play Intel x86 Atom
  - android-31 | Google APIs Intel x86 Atom_64

# ios
xcode: Not Found
cocoapods: Not Found
python: 3.9.7
python3: Not Found
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "^12.2.0",
  "@angular/common": "^12.2.0",
  "@angular/compiler": "^12.2.0",
  "@angular/core": "^12.2.0",
  "@angular/forms": "^12.2.0",
  "@angular/platform-browser": "^12.2.0",
  "@angular/platform-browser-dynamic": "^12.2.0",
  "@angular/router": "^12.2.0",
  "@nativescript/angular": "^12.2.0",
  "@nativescript/core": "~8.1.1",
  "@nativescript/theme": "~3.0.1",
  "rxjs": "~7.3.0",
  "zone.js": "~0.11.4"
},
"devDependencies": {
  "@angular/compiler-cli": "^12.2.0",
  "@nativescript/android": "8.1.1",
  "@nativescript/types": "~8.1.1",
  "@nativescript/webpack": "~5.0.0",
  "@ngtools/webpack": "^12.2.0",
  "typescript": "~4.3.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
