### ISSUE TITLE
on ios "ns run" displays a lot of low level log messages

### ISSUE THREAD

**Issue by mrh1997** [NativeScript/NativeScript#9764]
### Issue Description

When running a app on ios I get a lot of messages as soon as touch events are seen (in contrary to android!). This makes debugging much more difficult, as my own debug log messages get lost within this amount of log irrelevant messages.

### Reproduction

To repoduce:

```
1. start a app on ios
2. touch the phones surface to generate touch-messages
```

### Relevant log output (if applicable)

```shell
Sending UIEvent type: 0; subtype: 0; to windows: 1
Sending UIEvent type: 0; subtype: 0; to window: <UIWindow: 0x108b0fd60>; contextId: 0x683206F2
Evaluating dispatch of UIEvent: 0x2807c0240; type: 0; subtype: 0; backing type: 11; shouldSend: 0; ignoreInteractionEvents: 0, systemGestureStateChange: 1
Evaluating dispatch of UIEvent: 0x2807c0240; type: 0; subtype: 0; backing type: 11; shouldSend: 1; ignoreInteractionEvents: 0, systemGestureStateChange: 0
Sending UIEvent type: 0; subtype: 0; to windows: 1
Sending UIEvent type: 0; subtype: 0; to window: <UIWindow: 0x108b0fd60>; contextId: 0x683206F2
Key window needs update: 0; currentKeyWindowScene: 0x0; evaluatedKeyWindowScene: 0x0; currentApplicationKeyWindow: 0x0; evaluatedApplicationKeyWindow: 0x0; reason: UIWindowScene: 0x108b125e0: Window requested to become key in scene: 0x108b0fd60
Evaluating dispatch of UIEvent: 0x2807c0240; type: 0; subtype: 0; backing type: 11; shouldSend: 1; ignoreInteractionEvents: 0, systemGestureStateChange: 0
Sending UIEvent type: 0; subtype: 0; to windows: 1
Sending UIEvent type: 0; subtype: 0; to window: <UIWindow: 0x108b0fd60>; contextId: 0x683206F2
Evaluating dispatch of UIEvent: 0x2807c0240; type: 0; subtype: 0; backing type: 11; shouldSend: 0; ignoreInteractionEvents: 0, systemGestureStateChange: 1
Evaluating dispatch of UIEvent: 0x2807c0240; type: 0; subtype: 0; backing type: 11; shouldSend: 1; ignoreInteractionEvents: 0, systemGestureStateChange: 0
Sending UIEvent type: 0; subtype: 0; to windows: 1
```

### Environment

```yaml
OS: macOS 11.4
CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
Shell: /bin/zsh
node: 14.15.0
npm: 6.14.8
nativescript: 8.1.5

# android
java: 1.8.0_275
ndk: Not Found
apis: 28
build_tools: 28.0.3
system_images: Not Found

# ios
xcode: 13.2.1/13C100
cocoapods: 1.10.0
python: 2.7.16
python3: 3.8.9
ruby: 2.6.3
platforms: 
  - DriverKit 21.2
  - iOS 15.2
  - macOS 12.1
  - tvOS 15.2
  - watchOS 8.3
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "8.1.1",
  "@nativescript/theme": "~3.0.1",
  "nativescript-vue": "~2.9.0",
  "vue-class-decorator": "^7.6.3",
  "vue-property-decorator": "^9.1.2"
},
"devDependencies": {
  "@nativescript/ios": "8.1.0",
  "@nativescript/types-ios": "8.1.0",
  "@nativescript/android": "8.1.0",
  "@nativescript/types-android": "8.1.0",
  "@nativescript/types": "~8.1.1",
  "@nativescript/webpack": "~5.0.0",
  "@types/node": "~14.6.2",
  "nativescript-vue-template-compiler": "~2.9.0",
  "typescript": "~4.3.5",
  "vue": "~2.6.12"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
