### ISSUE TITLE
Support for advanced CSS selectors

### ISSUE THREAD

**Issue by bundyo** [NativeScript/NativeScript#98]
Currently such support in NativeScript's CSS is missing. It will be good to at least have child and sibling selectors, like these here:
https://css-tricks.com/child-and-sibling-selectors/

and possibly more advanced CSS3 ones later.

**Comment by alejonext** [comment]
thats is #191

**Comment by NathanaelA** [comment]
Please note; my issue (622) that was referenced to this bug was just talking about simple selector combining of the existing selectors like:
Button.className and Button#idName 
IMHO, these should be supported first; then the more advanced child selectors as @bundyo has referenced..

**Comment by PanayotCankov** [comment]
[CSS Attribute Selectors](http://www.w3schools.com/css/css_attribute_selectors.asp)

As an use case these can be quite powerful when combined with control state, similar to pseudo selectors, but more extesible since they work with all attributes (in our case properties) and are not predefined. Consider the possibility to style states with code such as:
``` CSS
TabViewItem.home {
    icon-source: url("res://home.gray")
}
TabViewItem[isSelected=true].home {
    icon-source: url("res://home.colorful");
}

TabViewItem.settings {
    icon-source: url("res://settings.gray")
}
TabViewItem[isSelected=true].settings {
    icon-source: url("res://settings.colorful");
}

/* etc. */
```
