### ISSUE TITLE
Environment variables from a .env file are not processed into project

### ISSUE THREAD

**Issue by Itemshopp** [NativeScript/NativeScript#9803]
### Issue Description

When I add a .env file into my project, I can't retrieve the variables anywhere in my code.

It normally should work like it is indicated on the webpack section : https://docs.nativescript.org/webpack.html#using-a-env-file

When, in my app.js, I console.log( process ), I only get an empty object.

### Reproduction

- `ns create helloWorld --js`

- `cd helloWorld`

- modify `"@nativescript/webpack": "beta"` as `"@nativescript/webpack": "^5.0.4"`

- add `.env` file in root folder [ HELLO="Hello World" as first line ]

- add `console.log( process )` in `app.js`

- `ns run` 

result : ```JS: undefined```

### Environment

```yaml
OS: macOS 10.15.7
CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
Shell: /bin/zsh
node: 17.4.0
npm: 8.3.1
nativescript: Not Found

# android
java: 1.8.0_292
ndk: 22.1.7171670
apis: 30
build_tools: 30.0.3
system_images: Not Found

# ios
xcode: 12.4/12D4e
cocoapods: 1.11.2
python: 2.7.16
python3: 3.6.6
ruby: 2.7.5
platforms:
  - iOS 14.4
  - DriverKit 20.2
  - macOS 11.1
  - tvOS 14.3
  - watchOS 7.2
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "~8.0.0",
  "@nativescript/theme": "~3.0.1"
},
"devDependencies": {
  "@nativescript/android": "8.0.0",
  "@nativescript/webpack": "^5.0.4"
}

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
