### ISSUE TITLE
NS 8.2.0+ iOS Base64 images disappearing after scrolling ListView/RadListView

### ISSUE THREAD

**Issue by felixkrautschuk** [NativeScript/NativeScript#9820]
### Issue Description

When upgrading @nativescript/core from 8.1.5 to latest 8.2.1 (or 8.2.0), I notice that images inside ListView/RadListView are disappearing after scrolling when using base64 ImageSources on iOS. They appear again when removing the items from ObservableArray and add them again.

```
<ListView items="{{ items }}">
            <ListView.itemTemplate>
                <GridLayout columns="auto,20,*>
                    <Image col="0" src="{{ imageSrc }}" className="image-list"/>
                    <Label col="2" text="{{ title }}" verticalAlignment="center"/>
                </GridLayout>
            </ListView.itemTemplate>
</ListView>
```

```
export const vm = fromObject({
  items: new ObservableArray([
      {title: "Item 1", imageSrc: ImageSource.fromBase64Sync("/9j/4AAQSkZJRgABAQAASABIAAD/4QCMRXhpZg...")},
      {title: "Item 2", imageSrc: ImageSource.fromBase64Sync("/9j/4AAQSkZJRgABAQEBLAEsAAD/7QJoUGhvdG...")},
      {title: "Item 3", imageSrc: null},
      //...
  ])
});
```

The output:
https://user-images.githubusercontent.com/6443021/157667068-8effbe14-f17d-4360-ac4b-f8d1f2157712.mov

With nativescript/core 8.1.5, it was working as expected:

https://user-images.githubusercontent.com/6443021/157667249-c57d8be4-3b16-4e3f-9238-6efe862a557c.mov

### Reproduction

Sample app to reproduce:
[ns-8-2-ios-image.zip](https://github.com/NativeScript/NativeScript/files/8223567/ns-8-2-ios-image.zip)

- run the app on ios
- tap the first button to navigate to the page with RadListView and base64 images
- scroll the list down and up again -> images disappearing

### Relevant log output (if applicable)

```shell
-
```

### Environment

```yaml
OS: macOS 12.2.1
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Shell: /bin/zsh
node: 14.18.1
npm: 6.14.15
nativescript: 8.1.5

# android
java: 11.0.11
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 13.2.1/13C100
cocoapods: 1.11.2
python: 2.7.18
python3: 3.9.7
ruby: 2.7.4
platforms: 
  - DriverKit 21.2
  - iOS 15.2
  - macOS 12.1
  - tvOS 15.2
  - watchOS 8.3
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "^8.2.1",
  "nativescript-ui-listview": "^10.0.2"
},
"devDependencies": {
  "@nativescript/android": "^8.2.2",
  "@nativescript/ios": "^8.2.1",
  "@nativescript/types": "~8.2.0",
  "@nativescript/webpack": "~5.0.6",
  "typescript": "~4.5.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
