### ISSUE TITLE
android: Gradle error "Could not find method compile() for arguments" = 'compile' needs to be 'implementation'

### ISSUE THREAD

**Issue by patrick-nurt** [NativeScript/NativeScript#9827]
### Issue Description

When building with latest release I get the following error:

```
Script '/node_modules/nativescript-qr-generator/platforms/android/include.gradle' line: 13
A problem occurred evaluating script.
Could not find method compile() for arguments [com.github.kenglxn.QRGen:android:2.6.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Command ./gradlew failed with exit code 1
error Command failed with exit code 127.
```

This was working prior to updating nativescript.

### Reproduction

ns run android

### Relevant log output (if applicable)

```shell
Script '/node_modules/nativescript-qr-generator/platforms/android/include.gradle' line: 13
A problem occurred evaluating script.
Could not find method compile() for arguments [com.github.kenglxn.QRGen:android:2.6.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Command ./gradlew failed with exit code 1
error Command failed with exit code 127.
```

### Environment

```yaml
OS: macOS 11.6
CPU: (8) arm64 Apple M1
Shell: /bin/zsh
node: 16.13.0
npm: 8.1.0
nativescript: 8.2.2

# android
java: 15.0.2
ndk: Not Found
apis: 25, 27, 28, 29, 30
build_tools: 28.0.3, 31.0.0
system_images: 
  - android-25 | Google APIs ARM 64 v8a
  - android-25 | Google APIs ARM EABI v7a
  - android-28 | Google APIs ARM 64 v8a
  - android-29 | Google APIs ARM 64 v8a
  - android-30 | Google APIs ARM 64 v8a
  - android-30 | Google APIs Intel x86 Atom
  - android-31 | Google APIs ARM 64 v8a

# ios
xcode: 12.5.1/12E507
cocoapods: 1.10.1
python: 2.7.16
python3: 3.9.1
ruby: 2.7.5
platforms: 
  - iOS 14.5
  - DriverKit 20.4
  - macOS 11.3
  - tvOS 14.5
  - watchOS 7.4
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "^13.1.0",
  "@angular/common": "^13.1.0",
  "@angular/compiler": "^13.1.0",
  "@angular/core": "^13.1.0",
  "@angular/forms": "^13.1.0",
  "@angular/platform-browser": "^13.1.0",
  "@angular/platform-browser-dynamic": "^13.1.0",
  "@angular/router": "^13.1.0",
  "@extenda/nativescript-okhttp-sse": "file:plugins/extenda-nativescript-okhttp-sse-1.0.0.tgz",
  "@nativescript-community/ui-material-tabs": "^7.0.0",
  "@nativescript-community/ui-persistent-bottomsheet": "^0.0.19",
  "@nativescript/angular": "^13.0.0",
  "@nativescript/core": "8.2.1",
  "@nativescript/datetimepicker": "^2.0.4",
  "@nativescript/firebase-analytics": "^1.1.1",
  "@nativescript/firebase-auth": "^1.1.1",
  "@nativescript/firebase-core": "^1.1.1",
  "@nativescript/firebase-crashlytics": "^1.1.1",
  "@nativescript/firebase-firestore": "^1.1.1",
  "@nativescript/firebase-functions": "^1.1.1",
  "@nativescript/firebase-storage": "^1.1.1",
  "@ngrx/effects": "^13.0.0",
  "@ngrx/entity": "^13.0.0",
  "@ngrx/router-store": "^13.0.0",
  "@ngrx/store": "^13.0.0",
  "@ngx-translate/core": "^14.0.0",
  "@ngx-translate/http-loader": "^7.0.0",
  "@nstudio/nativescript-floatingactionbutton": "^3.0.4",
  "@turf/distance": "^6.3.0",
  "compare-versions": "^3.5.1",
  "eventemitter3": "^4.0.7",
  "geodist": "^0.2.1",
  "lodash.clonedeep": "^4.5.0",
  "nativescript-dna-deviceinfo": "^3.0.0",
  "nativescript-download-progress": "^1.7.0",
  "nativescript-ngx-fonticon": "^7.0.0",
  "nativescript-permissions": "^1.3.11",
  "nativescript-qr-generator": "^2.0.0",
  "rfc6902": "^5.0.0",
  "rxjs": "^7.0.0",
  "turf-point": "^2.0.1",
  "zone.js": "~0.11.4"
},
"devDependencies": {
  "@angular-devkit/build-angular": "^13.2.0",
  "@angular/compiler-cli": "^13.1.0",
  "@nativescript/android": "8.2.2",
  "@nativescript/types": "~8.2.0",
  "@nativescript/webpack": "^5.0.0",
  "@ngtools/webpack": "^13.2.0",
  "typescript": "~4.4.4"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
