### ISSUE TITLE
Not able to take Build for Android

### ISSUE THREAD

**Issue by skmani** [NativeScript/NativeScript#9828]
### Issue Description

When I am trying to take a build in Android I am getting an Error as below but I can able to take build in IOS.

**ERROR in ../node_modules/nativescript-permissions/permissions.js
Module not found: Error: Can't resolve '@master.technology/permissions' in** 
'/node_modules/nativescript-permissions'
@ ../node_modules/nativescript-permissions/permissions.js 13:17-58
@ ../node_modules/nativescript-camera/camera.js
@ ./app/virtualevent/virtualevent.component.ts
@ ./app/app.module.tns.ts
@ ./main.tns.ts
Webpack compilation complete.
Executing webpack failed with exit code 2.
 

### Environment

```yaml
OS: macOS 12.3
CPU: (10) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 14.18.2
npm: 6.14.15
nativescript: 8.1.5

# android
java: 17.0.2
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 13.3/13E113
cocoapods: 1.11.2
python: Not Found
python3: 3.8.9
ruby: 2.7.5
platforms: 
  - DriverKit 21.4
  - iOS 15.4
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "^12.2.5",
  "@angular/common": "^12.2.5",
  "@angular/compiler": "^12.2.5",
  "@angular/core": "^12.2.5",
  "@angular/forms": "^12.2.5",
  "@angular/http": "~8.0.0-beta.10",
  "@angular/platform-browser": "^12.2.5",
  "@angular/platform-browser-dynamic": "^12.2.5",
  "@angular/router": "^12.2.5",
  "@nativescript/theme": "~2.2.1",
  "@nstudio/nativescript-checkbox": "^1.0.0",
  "base-64": "^1.0.0",
  "core-js": "^2.6.9",
  "material-ui-search-bar": "^0.4.2",
  "nativescript-accordion": "^6.0.0-beta.2",
  "nativescript-app-tour-updated": "^2.0.2",
  "nativescript-camera": "^4.5.0",
  "nativescript-collectionview": "^2.0.36",
  "nativescript-danem-drop-down": "^1.0.3",
  "nativescript-datetimepicker": "^1.2.2",
  "nativescript-email": "^1.6.0",
  "nativescript-google-places-autocomplete": "^1.0.3",
  "nativescript-imagecropper": "^4.0.0",
  "nativescript-imagepicker": "^7.1.0",
  "nativescript-iqkeyboardmanager": "^1.5.1",
  "nativescript-oauth": "^2.1.8",
  "nativescript-oauth2": "^2.4.0",
  "nativescript-permissions": "^1.3.9",
  "nativescript-plugin-firebase": "^10.5.2",
  "nativescript-slides": "^2.3.0",
  "nativescript-ui-autocomplete": "^6.0.1",
  "nativescript-ui-sidedrawer": "^8.0.1",
  "nativescript-websockets": "^1.5.6",
  "pusher-nativescript": "^1.0.0",
  "reflect-metadata": "~0.1.12",
  "rxjs": "~7.3.0",
  "rxjs-compat": "^6.5.5",
  "tslib": "1.10.0",
  "zone.js": "~0.11.4",
  "@nativescript/core": "~8.1.1",
  "@nativescript/angular": "^12.2.0"
},
"devDependencies": {
  "@angular-devkit/build-angular": "^13.2.5",
  "@angular/cli": "^12.2.5",
  "@angular/compiler-cli": "^12.2.5",
  "@nativescript/android": "~8.1.1",
  "@nativescript/ios": "~8.1.0",
  "@nativescript/schematics": "~1.0.0",
  "@nativescript/tslint-rules": "~0.0.5",
  "@nativescript/webpack": "~5.0.0",
  "@ngtools/webpack": "^13.2.5",
  "@types/jasmine": "~3.3.8",
  "@types/jasminewd2": "~2.0.3",
  "@types/node": "~8.9.4",
  "codelyzer": "^5.0.0",
  "jasmine-core": "~3.4.0",
  "jasmine-spec-reporter": "~4.2.1",
  "karma": "^5.2.3",
  "karma-chrome-launcher": "~2.2.0",
  "karma-coverage-istanbul-reporter": "~2.0.1",
  "karma-jasmine": "~2.0.1",
  "karma-jasmine-html-reporter": "^1.4.0",
  "protractor": "^7.0.0",
  "sass": "~1.39.0",
  "ts-node": "~7.0.0",
  "tslint": "~5.15.0",
  "typescript": "~4.3.5"
}
``` 

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
