### ISSUE TITLE
[TextBase] `lineHeight` broken on iOS

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/NativeScript#9830]
### Issue Description

Current `lineHeight` on iOS is broken.
It happened in this commit https://github.com/NativeScript/NativeScript/commit/9d3977ea4fd6d6aedeab55e0472999c05ed5a7bd
if you compare before and after you ll see that before the `lineHeight` was correct (same as Android) and now it does not correspond to the value (almost double what it should be).

### Reproduction

Rollback to 8.2.0.alpha7 and compare `lineHeight` on iOS

### Environment

```yaml
OS: macOS 11.6
CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Shell: /bin/zsh
node: 17.6.0
npm: 8.5.1
nativescript: Not Found

# android
java: 15.0.2
ndk: 20.0.5594570
apis: 27, 28, 29, 30, 31
build_tools: 28.0.2, 29.0.2, 29.0.3, 30.0.1, 30.0.2, 30.0.3, 32.0.0
system_images: 
  - android-19 | Intel x86 Atom
  - android-26 | Intel x86 Atom_64
  - android-29 | Intel x86 Atom_64
  - android-30 | Intel x86 Atom_64
  - android-31 | Intel x86 Atom_64

# ios
xcode: 13.0/13A233
cocoapods: 1.11.2
python: 3.9.7
python3: 3.9.10
ruby: 2.6.3
platforms: 
  - iOS 15.0
  - DriverKit 20.4
  - macOS 11.3
  - tvOS 15.0
  - watchOS 8.0
```

### Dependencies

```json
"dependencies": {
  "@akylas/nativescript": "file:../NativeScript/dist/packages/core",
  "@akylas/nativescript-audio": "6.2.9",
  "@akylas/nativescript-inappbrowser": "3.1.6",
  "@corefortech/garmin": "file:./nativescript-garmin/plugin",
  "@mdi/font": "6.5.95",
  "@nativescript-community/ble": "3.1.6",
  "@nativescript-community/extendedinfo": "1.3.0",
  "@nativescript-community/gesturehandler": "0.1.52",
  "@nativescript-community/gps": "3.1.3",
  "@nativescript-community/https": "3.4.2",
  "@nativescript-community/l": "4.2.23",
  "@nativescript-community/perms": "2.2.6",
  "@nativescript-community/sensors": "1.2.1",
  "@nativescript-community/sentry": "3.1.1",
  "@nativescript-community/systemui": "1.1.8",
  "@nativescript-community/text": "1.5.3",
  "@nativescript-community/texttospeech": "3.0.5",
  "@nativescript-community/tween": "0.0.14",
  "@nativescript-community/ui-canvas": "4.4.0",
  "@nativescript-community/ui-canvaslabel": "1.1.2",
  "@nativescript-community/ui-chart": "1.2.14",
  "@nativescript-community/ui-collectionview": "4.0.48",
  "@nativescript-community/ui-image": "4.1.6",
  "@nativescript-community/ui-label": "1.2.6",
  "@nativescript-community/ui-material-activityindicator": "7.0.0",
  "@nativescript-community/ui-material-bottomsheet": "7.0.0",
  "@nativescript-community/ui-material-button": "7.0.0",
  "@nativescript-community/ui-material-dialogs": "7.0.0",
  "@nativescript-community/ui-material-progress": "7.0.0",
  "@nativescript-community/ui-material-snackbar": "7.0.0",
  "@nativescript-community/ui-pager": "13.0.34",
  "@nativescript-community/ui-pulltorefresh": "2.5.0",
  "@nativescript-community/ui-share-file": "1.2.3",
  "@nativescript-community/ui-svg": "0.0.8",
  "@nativescript/email": "2.0.5",
  "@nativescript/imagepicker": "1.0.6",
  "@nativescript/local-notifications": "^5.0.3",
  "@nstudio/nativescript-checkbox": "2.0.4",
  "dayjs": "1.10.8",
  "duration": "0.2.2",
  "helpful-decorators": "2.1.0",
  "make-error": "1.3.6",
  "merge-options": "3.0.4",
  "nativescript-inappbrowser": "^3.1.2",
  "nativescript-vibrate": "4.0.1",
  "nativescript-vue": "2.9.0",
  "vue-string-filter": "2.1.0"
},
"devDependencies": {
  "@akylas/fontmin": "^0.9.9",
  "@babel/core": "7.17.5",
  "@nativescript/android": "8.2.2",
  "@nativescript/core": "8.2.1",
  "@nativescript/ios": "6.5.4",
  "@nativescript/types-android": "8.2.0",
  "@nativescript/types-ios": "8.2.1",
  "@nativescript/webpack": "5.0.6",
  "@sentry/webpack-plugin": "^1.18.5",
  "@typescript-eslint/eslint-plugin": "5.14.0",
  "@typescript-eslint/parser": "5.14.0",
  "@vue/eslint-config-typescript": "^10.0.0",
  "babel-loader": "^8.2.3",
  "cross-var": "1.1.0",
  "eslint": "8.11.0",
  "eslint-config-prettier": "^8.5.0",
  "eslint-plugin-prettier": "^4.0.0",
  "eslint-plugin-vue": "^8.5.0",
  "nativescript-set-version": "0.3.0",
  "nativescript-vue-template-compiler": "2.9.1",
  "prettier": "^2.5.1",
  "rimraf": "3.0.2",
  "sass": "^1.49.9",
  "sass-loader": "^12.6.0",
  "scss-symbols-parser": "^2.0.1",
  "string-replace-loader": "^3.1.0",
  "typescript": "~4.6.2",
  "vue": "2.6.14",
  "vue-class-component": "7.2.6",
  "vue-i18n": "9.1.9",
  "vue-loader": "15.9.8",
  "vue-property-decorator": "~9.1.2"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
