### ISSUE TITLE
iOS build issue after update to macOS Monterey (12.3)

### ISSUE THREAD

**Issue by ipald** [NativeScript/NativeScript#9833]
### Issue Description

Hello all,
after updating my Mac to 12.3 (macOS Monterey) Xcode fails in archive/build with the error:

```
env: python: No such file or directory
Command Ld failed with a nonzero exit code
```

I cannot find any information about this error except [this thread on stackoverflow](https://stackoverflow.com/questions/71468590/env-python-no-such-file-or-directory-when-building-app-with-xcode) (where I've posted because proposed solution doesn't work in my case)

The issue occurs with any app.

Someone have any suggestion?

### Reproduction

Open XCode
Select any workspace
From top menu selct "Product > Archive"

### Relevant log output (if applicable)

```shell
./.build_env_vars.sh: line 454: declare: UID: readonly variable
NSLD: Swift bridging header '*-Swift.h' not found under '/Users/projects/Library/Developer/Xcode/DerivedData/myapp-emltoukfgkimqnglbyjtvysfhqvp/Build/Intermediates.noindex/ArchiveIntermediates/myapp/IntermediateBuildFilesPath/myapp.build/Release-iphoneos/app4box.build/Objects-normal/arm64'
Generating metadata...~/Projects/myfolder/myapp/platforms/ios/internal/metadata-generator-arm64/bin ~/Projects/myfolder/myapp/platforms/ios
env: python: No such file or directory
Command Ld failed with a nonzero exit code
```

### Environment

```yaml
OS: macOS 12.3
CPU: (8) x64 Apple M1
Shell: /bin/zsh
node: 12.22.10
npm: 6.14.16
nativescript: 8.1.5

# android
java: 11.0.14
ndk: Not Found
apis: 22, 30, 32
build_tools: 22.0.1, 30.0.3, 32.0.0, 32.1.0
system_images: 
  - android-29 | Google APIs ARM 64 v8a
  - android-30 | Google APIs ARM 64 v8a
  - android-32 | Google APIs ARM 64 v8a

# ios
xcode: 13.2.1/13C100
cocoapods: 1.11.2
python: 3.9.10
python3: 3.9.10
ruby: 2.7.5
platforms: 
  - DriverKit 21.2
  - iOS 15.2
  - macOS 12.1
  - tvOS 15.2
  - watchOS 8.3
```

### Dependencies

```json
"dependencies": {},
"devDependencies": {}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
