### ISSUE TITLE
TabView properties tab-text-color and tab-text-font-size are not working on iOS

### ISSUE THREAD

**Issue by Lucia-Bader** [NativeScript/NativeScript#9844]
### Issue Description

I'm using Angular with NativeScript and TypeScript. To customize the appereance of the TabView I use tab-text-color and tab-text-font-size. On Android it's working as expected but on iOS my changes take no effect. That means on iOS, the TabView color remains gray even though I set it to white. 

### Environment

```yaml
OS: macOS 11.6
CPU: (4) x64 Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
Shell: /bin/zsh
node: 14.17.6
npm: 6.14.15
nativescript: 8.1.4

# android
java: 1.8.0_292
ndk: Not Found
apis: 28, 29, 30, 31
build_tools: 28.0.3, 31.0.0
system_images: Not Found

# ios
xcode: 13.0/13A233
cocoapods: 1.11.2
python: 2.7.16
python3: 3.8.9
ruby: 3.0.2
platforms: 
  - iOS 15.0
  - DriverKit 20.4
  - macOS 11.3
  - tvOS 15.0
  - watchOS 8.0
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~11.2.7",
  "@angular/common": "~11.2.7",
  "@angular/compiler": "~11.2.7",
  "@angular/core": "~11.2.7",
  "@angular/forms": "~11.2.7",
  "@angular/platform-browser": "~11.2.7",
  "@angular/platform-browser-dynamic": "~11.2.7",
  "@angular/router": "~11.2.7",
  "@nativescript/angular": "^11.8.1",
  "@nativescript/core": "^8.2.1",
  "@nativescript/localize": "^5.0.4",
  "@nativescript/theme": "^3.0.1",
  "nativescript-angular": "^10.0.0",
  "nativescript-barcodescanner": "^4.1.2",
  "nativescript-theme-core": "^2.0.24",
  "reflect-metadata": "~0.1.13",
  "rxjs": "~6.6.7",
  "zone.js": "~0.11.4"
},
"devDependencies": {
  "@angular/compiler-cli": "~11.2.7",
  "@nativescript/android": "^8.1.1",
  "@nativescript/ios": "8.1.0",
  "@nativescript/types": "^8.0.1",
  "@nativescript/webpack": "^5.0.2",
  "@ngtools/webpack": "^11.2.14",
  "nativescript-dev-sass": "^1.7.0",
  "typescript": "~4.0.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
