### ISSUE TITLE
Can not find iOS class name when upgrade @nativescript/types from 8.1.1 to 8.2.0

### ISSUE THREAD

**Issue by coolboy0961** [NativeScript/NativeScript#9848]
### Issue Description

When upgrade @nativescript/types from 8.1.1 to 8.2.0, can not find iOS class name.
<img width="1903" alt="image" src="https://user-images.githubusercontent.com/12973893/160815794-8ff7c751-7b68-47ba-98ac-c21514aec5a8.png">

I searched stackoverflow, but there is no solution.
https://stackoverflow.com/questions/71470306/nativescript-8-2-cannot-find-name-cllocationmanager-cllocationmanagerdelegate
https://stackoverflow.com/questions/71460252/nativescript-6-5-1-to-8-2-cannot-find-name-cllocationmanager-cllocationmanage/71640446

### Reproduction

If you downgrade to 8.1.1, it will be fine.

### Environment

```yaml
OS: macOS 12.1
CPU: (10) arm64 Apple M1 Max
Shell: /bin/zsh
node: 14.17.0
npm: 6.14.13
nativescript: 8.2.2

# android
java: 11.0.14.1
ndk: Not Found
apis: 29, 30, 31, 32
build_tools: 29.0.3, 30.0.3, 32.0.0, 32.1.0
system_images: 
  - android-30 | Google Play ARM 64 v8a
  - android-31 | Google Play ARM 64 v8a
  - android-32 | Google APIs ARM 64 v8a

# ios
xcode: 13.3/13E113
cocoapods: 1.11.3
python: 3.9.7
python3: 3.9.7
ruby: 3.0.2
platforms: 
  - DriverKit 21.4
  - iOS 15.4
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@nativescript-community/ui-lottie": "^4.1.2",
  "@nativescript/auto-fit-text": "^1.0.1",
  "@nativescript/core": "^8.1.5",
  "@nativescript/firebase-analytics": "^1.2.0",
  "@nativescript/firebase-core": "^1.2.0",
  "@nativescript/firebase-crashlytics": "^1.2.0",
  "@nativescript/iqkeyboardmanager": "^2.0.0",
  "@nativescript/secure-storage": "^3.0.0",
  "@nativescript/theme": "~3.0.1",
  "@nstudio/nativescript-loading-indicator": "^4.1.0",
  "@nstudio/nativescript-tracking-transparency": "^1.0.0",
  "@plmservices/nativescript-outline-label": "^2.0.2",
  "axios": "0.21.1",
  "lodash": "^4.17.21",
  "maskdata": "^1.1.4",
  "nativescript-clipboard": "^2.1.1",
  "nativescript-dna-deviceinfo": "^3.7.1",
  "nativescript-vue": "~2.9.0",
  "nativescript-vue-router-ns": "^1.0.4",
  "url-parse": "^1.5.3",
  "vue-class-component": "^7.2.6",
  "vue-property-decorator": "^9.1.2",
  "vuelidate-property-decorators": "^1.0.28",
  "vuex": "^3.6.2",
  "vuex-class": "^0.3.2",
  "vuex-module-decorators": "^1.0.1"
},
"devDependencies": {
  "@babel/preset-env": "^7.14.2",
  "@nativescript/android": "^8.1.1",
  "@nativescript/eslint-plugin": "0.0.4",
  "@nativescript/ios": "^8.2.2",
  "@nativescript/types": "^8.2.0",
  "@nativescript/webpack": "5.0.0",
  "@types/jest": "^26.0.23",
  "@types/lodash": "^4.14.170",
  "@types/node": "~14.6.2",
  "@types/vuelidate": "^0.7.14",
  "@typescript-eslint/eslint-plugin": "^4.27.0",
  "@typescript-eslint/parser": "^4.27.0",
  "@vue/eslint-config-typescript": "^7.0.0",
  "@vue/test-utils": "^1.2.2",
  "axios-mock-adapter": "^1.19.0",
  "babel-core": "^7.0.0-bridge.0",
  "babel-jest": "^26.6.3",
  "cli-table": "https://github.com/telerik/cli-table/tarball/v0.3.1.2",
  "cpx": "^1.5.0",
  "eslint": "^7.28.0",
  "eslint-config-prettier": "^8.3.0",
  "eslint-plugin-prettier": "^3.4.0",
  "eslint-plugin-vue": "^7.11.1",
  "flush-promises": "^1.0.2",
  "jest": "^26.6.3",
  "jest-html-reporter": "^3.4.0",
  "jest-sonar-reporter": "^2.0.0",
  "license-checker": "^25.0.1",
  "marked-terminal": "https://github.com/NativeScript/marked-terminal/tarball/v3.1.1n",
  "nativescript": "^8.1.5",
  "nativescript-vue-jest": "^3.0.4",
  "nativescript-vue-template-compiler": "~2.9.0",
  "npm-run-all": "^4.1.5",
  "prettier": "^2.3.0",
  "sonarqube-scanner": "^2.8.1",
  "tns-platform-declarations": "^6.5.15",
  "ts-jest": "^26.5.6",
  "typescript": "~4.0.0",
  "vue": "^2.6.12",
  "vue-eslint-parser": "^7.6.0",
  "vue-jest": "^3.0.7",
  "vue-template-compiler": "^2.6.12"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
