### ISSUE TITLE
Error: Calling js method onCreateView failed; Expected the adapter to be 'fresh' while restoring state.

### ISSUE THREAD

**Issue by dlcole** [NativeScript/NativeScript#9856]
### Issue Description

On Android, if my app navigates away from the app (such as opening a Google map) and then returns, returning to the prior page via the back button causes this error:  

```
JS: app.js uncaught error: Error: Calling js method onCreateView failed
JS: Error: java.lang.IllegalStateException: Expected the adapter to be 'fresh' while restoring state.
ActivityManager: Process tech.govia.rrr (pid 22075) has died: fore TOP (326,1134)
ActivityManager: setHasOverlayUi called on unknown pid: 22075
```

I was able to identify the problem in @nativescript/core/ui/frame/index.android.js starting at line 755:

```
 const savedState = entry.viewSavedState;
        if (savedState) { 
            page.nativeViewProtected.restoreHierarchyState(savedState);
            entry.viewSavedState = null;
        }
```
The problem is that `savedState` in this case is an empty object, but tests for true.  I replaced line 756 with 

`if (savedState && Object.keys(savedState).length > 0) {`

and this is now working correctly.  

### Reproduction

Mine is a Nativecript JavaScript project; this problem likely applies to other project types as well.  On a secondary page within your app, open a window that causes the app to be suspended, such as opening a Contacts selection window or a Google map.  Upon returning to your app, tap the back button so as to return to the prior page.  The error shown above will occur.  This problem only occurs on Android. 

### Environment

```yaml
OS: macOS 12.2.1
CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
Shell: /bin/bash
node: 16.13.0
npm: 8.1.0
nativescript: 8.1.5

# android
java: 11.0.13
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 13.3/13E113
cocoapods: 1.8.4
python: 2.7.18
python3: 3.9.5
ruby: 2.6.8
platforms: 
  - DriverKit 21.4
  - iOS 15.4
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@bradmartin/nativescript-urlhandler": "^2.0.1",
  "@kefah/nativescript-google-maps": "^1.0.7",
  "@master.technology/permissions": "^2.0.1",
  "@nativescript-community/ui-material-bottom-navigation": "^7.0.2",
  "@nativescript/appversion": "^2.0.0",
  "@nativescript/contacts": "^2.0.4",
  "@nativescript/core": "^8.2.1",
  "@nativescript/email": "^2.0.5",
  "@nativescript/firebase": "^11.1.3",
  "@nativescript/geolocation": "^8.0.2",
  "@nativescript/iqkeyboardmanager": "^2.0.0",
  "@nativescript/theme": "^3.0.2",
  "@triniwiz/nativescript-toasty": "^4.1.3",
  "base-64": "^1.0.0",
  "nativescript-bitmap-factory": "^1.8.1",
  "nativescript-clipboard": "^2.1.1",
  "nativescript-danem-google-maps-utils": "^1.0.18",
  "nativescript-drop-down": "^6.0.1",
  "nativescript-pdf-view": "^3.0.0-1",
  "nativescript-phone": "^3.0.3",
  "nativescript-screenshot": "^0.0.2",
  "nativescript-sqlite": "^2.8.6",
  "nativescript-ui-listview": "^10.0.2",
  "nativescript-ui-sidedrawer": "^10.0.2",
  "patch-package": "^6.4.7"
},
"devDependencies": {
  "@nativescript/android": "8.1.1",
  "@nativescript/ios": "8.2.3",
  "@nativescript/webpack": "^5.0.6"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
