### ISSUE TITLE
Long startup delay on iOS; "restarting application" occurs multiple times

### ISSUE THREAD

**Issue by dlcole** [NativeScript/NativeScript#9865]
### Issue Description

I have migrated my JavaScript app from {N} 6.5 to 8.x.  Things mostly work OK, EXCEPT that I now have a long delay, some 12-14 seconds,  on iOS before the app's home screen is displayed. On Android, startup takes around 5 seconds which is acceptable.  

Looking through the logs, I'm seeing that the app is restarted twice, and I'm guessing this contributes to the delay. I can't see, though, why this would happen.  

I've created a couple logs.  In each case, the app was deleted from the device prior to starting.  
iOS log:  [http://rrr.govia.tech/logs/rrr_ios.log.txt](http://rrr.govia.tech/logs/rrr_ios.log.txt)
iOS log w/ {N} tracing:  [http://rrr.govia.tech/logs/rrr_ios_trace_all.log.txt](http://rrr.govia.tech/logs/rrr_ios_trace_all.log.txt)

In the log there are these lines:  

```
CONSOLE LOG: main-page.js entering at 4/08/2022 at 8:52am 33.157
kExcludedFromBackupXattrName set on path: <private>
Successfully transferred all files on device 00008030-001A55C93E60802E.
Refreshing application on device 00008030-001A55C93E60802E...
Successfully transferred all files on device 00008030-001A55C93E60802E.
Restarting application on device 00008030-001A55C93E60802E...
```

After entering home screen's code-behind file (main-page-js), it seems the app's files are transferred again and the app refreshed.  This is with a debug build, but the same delay occurs on a release build when run through Xcode (13.3).  In both cases the device is running iOS 15.4. 

I'm at a real loss here.  I need to publish my app as soon as possible, but this startup delay is a blocking defect.  I'd really appreciate any help from the community. 

### Reproduction

`tns run ios`

### Relevant log output (if applicable)

```shell
See description with links, above.
```

### Environment

```yaml
OS: macOS 12.2.1
CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
Shell: /bin/bash
node: 16.13.0
npm: 8.1.0
nativescript: 8.1.5

# android
java: 11.0.13
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 13.3/13E113
cocoapods: 1.8.4
python: 2.7.18
python3: 3.9.5
ruby: 2.6.8
platforms: 
  - DriverKit 21.4
  - iOS 15.4
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@bradmartin/nativescript-urlhandler": "^2.0.1",
  "@kefah/nativescript-google-maps": "^1.0.7",
  "@master.technology/permissions": "^2.0.1",
  "@nativescript-community/ui-material-bottom-navigation": "^7.0.2",
  "@nativescript/appversion": "^2.0.0",
  "@nativescript/contacts": "^2.0.4",
  "@nativescript/core": "^8.2.1",
  "@nativescript/email": "^2.0.5",
  "@nativescript/firebase": "^11.1.3",
  "@nativescript/geolocation": "^8.0.2",
  "@nativescript/iqkeyboardmanager": "^2.0.0",
  "@nativescript/theme": "^3.0.2",
  "@triniwiz/nativescript-toasty": "^4.1.3",
  "base-64": "^1.0.0",
  "nativescript-bitmap-factory": "^1.8.1",
  "nativescript-clipboard": "^2.1.1",
  "nativescript-danem-google-maps-utils": "^1.0.18",
  "nativescript-drop-down": "^6.0.1",
  "nativescript-pdf-view": "^3.0.0-1",
  "nativescript-phone": "^3.0.3",
  "nativescript-screenshot": "^0.0.2",
  "nativescript-sqlite": "^2.8.6",
  "nativescript-ui-listview": "^10.0.2",
  "nativescript-ui-sidedrawer": "^10.0.2",
  "patch-package": "^6.4.7"
},
"devDependencies": {
  "@nativescript/android": "8.1.1",
  "@nativescript/ios": "8.2.3",
  "@nativescript/webpack": "^5.0.6"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
