### ISSUE TITLE
iOS and Android: Application.off does not unregister resume event

### ISSUE THREAD

**Issue by cjohn001** [NativeScript/NativeScript#9890]
### Issue Description

I am registering and unregistering a resume event for an angular component as follows:

export class MainComponent implements OnInit, OnDestroy 
ngOnInit() {
 Application.on(Application.resumeEvent, this.resumeEventListener, this);
}

ngOnDestroy() {
Application.off(Application.resumeEvent, this.resumeEventListener, this);
}

public resumeEventListener() {
	console.log('resume event main page');
}

However, the unregistering does not work. When the page is recreated several times, with each additional time the resumeEventListener is called one time more. Hence after recreating the page the second time resume event is called twice, after third time 3 times and so on.

### Environment

```yaml
OS: macOS 12.3.1
CPU: (10) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 16.13.0
npm: 8.1.2
nativescript: 8.2.3

# android
java: 11.0.11
ndk: Not Found
apis: 28, 29, 31, 32
build_tools: 32.1.0
system_images: 
  - android-24 | Google APIs ARM 64 v8a
  - android-28 | Google ARM64-V8a Play ARM 64 v8a
  - android-29 | Google APIs ARM 64 v8a
  - android-31 | ARM 64 v8a
  - android-32 | Google Play ARM 64 v8a
  - android-Sv2 | Google APIs ARM 64 v8a

# ios
xcode: 13.3.1/13E500a
cocoapods: 1.11.2
python: 3.9.10
python3: 3.9.10
ruby: 2.7.5
platforms: 
  - DriverKit 21.4
  - iOS 15.4
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "13.3.5",
  "@angular/common": "13.3.5",
  "@angular/compiler": "13.3.5",
  "@angular/core": "13.3.5",
  "@angular/forms": "13.3.5",
  "@angular/platform-browser": "13.3.5",
  "@angular/platform-browser-dynamic": "13.3.5",
  "@angular/router": "13.3.5",
  "@apollo/client": "3.6.1",
  "@nativescript-community/ui-material-tabs": "6.2.14",
  "@nativescript/angular": "13.0.3",
  "@nativescript/core": "8.2.3",
  "@nativescript/iqkeyboardmanager": "2.0.0",
  "@nativescript/localize": "5.0.4",
  "@nativescript/mlkit-barcode-scanning": "1.0.4",
  "@nativescript/mlkit-core": "1.0.4",
  "@nativescript/secure-storage": "3.0.0",
  "@nativescript/theme": "3.0.2",
  "@nativescript/ui-charts": "0.2.2",
  "apollo-angular": "3.0.1",
  "apollo3-cache-persist": "0.14.0",
  "d3-ease": "3.0.1",
  "graphql": "16.4.0",
  "graphql-tag": "2.12.6",
  "intl": "1.2.5",
  "moment": "2.29.3",
  "nativescript-health-data": "file:../mnd-custom-plugins/nativescript-health-data/publish/package/nativescript-health-data-2.0.0.tgz",
  "nativescript-oauth2-ext": "file:../mnd-custom-plugins/nativescript-oauth2-ext/publish/package/nativescript-oauth2-ext-3.0.0.tgz",
  "nativescript-sqlite": "2.8.6",
  "nativescript-ui-autocomplete": "8.0.1",
  "nativescript-ui-calendar": "file:../mnd-custom-plugins/plugins-ui/dist/packages/ui-calendar/nativescript-ui-calendar-8.0.2.tgz",
  "nativescript-ui-gauge": "8.0.1",
  "rxjs": "7.5.5",
  "uuid": "8.3.2",
  "zone.js": "0.11.5"
},
"devDependencies": {
  "@angular-devkit/build-angular": "13.3.4",
  "@angular/compiler-cli": "13.3.5",
  "@graphql-codegen/cli": "2.6.2",
  "@graphql-codegen/fragment-matcher": "3.2.1",
  "@graphql-codegen/introspection": "2.1.1",
  "@graphql-codegen/typescript": "2.4.8",
  "@graphql-codegen/typescript-apollo-angular": "3.4.7",
  "@graphql-codegen/typescript-operations": "2.3.5",
  "@nativescript/android": "8.2.2",
  "@nativescript/ios": "8.2.3",
  "@nativescript/types": "8.2.0",
  "@nativescript/webpack": "5.0.6",
  "@ngtools/webpack": "13.3.4",
  "@types/d3-ease": "3.0.0",
  "@types/intl": "1.2.0",
  "@types/node": "16.11.6",
  "@types/uuid": "8.3.4",
  "keycloak-request-token": "0.1.0",
  "rimraf": "3.0.2",
  "sass": "1.51.0",
  "ts-node": "10.7.0",
  "typescript": "4.6.4"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
