### ISSUE TITLE
[ios] HtmlView no longer displaying images innside html

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#9899]
### Issue Description

We have some html (html string fetched from api) content that we show inn our apps. For Android we use WebView, but since it does not work on iOS, we use HtmlView here instead. 

HtmlView on iOS used to work fine not that long ago, using ns 8.1 we had no issues. But in 8.2 we are seeing some. One of them is that no images are being shown. We've tested this outside our app also, same issue. And also by testing with several image urls. 

This is an example of what we see:
![Screenshot 2022-05-06 at 20 36 18](https://user-images.githubusercontent.com/3605066/167198103-6bbf57fd-8b67-419c-9a35-a5e2a87795c7.png)

### Reproduction

```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
    <ActionBar title="My App" icon="" />

    <ScrollView>
            <HtmlView id="htmlView" html="{{ data }}" margin="10,6,0,6" backgroundColor="transparent"/>
    </ScrollView>
</Page>
```

```js
export function navigatingTo(args: EventData) {

  const page = <Page>args.object;
  var pageData = new Observable();
  page.bindingContext = pageData;
  
  const htmlData = `
        <html>
          <head></head>
          <body>
              <div>
                <p>some text here...</p>
                <img src="https://media.fkzeljeznicar.ba/zeljo_county.jpg" width="350px" />
                <p>some text here...</p>
              </div>
          </body>
        </html>`;

  pageData.set("data", htmlData);
}
```

### Environment

```yaml
OS: macOS 12.2
CPU: (8) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 16.15.0
npm: 8.5.5
nativescript: 8.2.3

# android
java: 11.0.15
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 13.3.1/13E500a
cocoapods: 1.11.3
python: 2.7.18
python3: 3.8.9
ruby: 2.6.8
platforms: 
  - DriverKit 21.4
  - iOS 15.4
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "8.2.3",
  "@nativescript/theme": "~3.0.2"
},
"devDependencies": {
  "@nativescript/ios": "8.2.3",
  "@nativescript/types": "~8.2.0",
  "@nativescript/webpack": "~5.0.6",
  "typescript": "~4.5.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
