### ISSUE TITLE
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3)

### ISSUE THREAD

**Issue by nmandyam** [NativeScript/NativeScript#9907]
### Issue Description

I upgraded to Xcode 15.3.3 earlier today. After that, when I run either of these commands with a simulator:
  `ns debug ios` OR `ns run ios`
I see this error and the app refuses to restart. The app does run OK when I click on it.
```
Error while trying to start application <my app> on device <device id>. Error is: Command xcrun with arguments simctl terminate <device id> <my app> failed with exit code 3. Error output:
 An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
Application termination failed.
FBSSystemService reported failure without an error, possibly because the app is not currently running.
```
Obviously, this is a serious problem, since I can't debug and fix code simultaneously.
BTW, I see a StackOverflow entry about this 20 days ago with no response.

### Reproduction

ns run ios
OR
ns debug ios

### Environment

```yaml
OS: macOS 12.3.1
CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
Shell: /bin/zsh
node: 10.21.0
npm: 6.14.4
nativescript: 7.2.1

# android
java: 1.8.0_252
ndk: Not Found
apis: 28, 29
build_tools: 28.0.2, 28.0.3
system_images: 
  - android-28 | Google APIs Intel x86 Atom

# ios
xcode: 13.3.1/13E500a
cocoapods: 1.11.3
python: 3.8.9
python3: 3.8.9
ruby: 2.6.8
platforms: 
  - DriverKit 21.4
  - iOS 15.4
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@nstudio/nativescript-cardview": "^1.0.0",
  "@nstudio/nativescript-checkbox": "^1.0.0",
  "@proplugins/nativescript-dom": "^2.2.3",
  "@proplugins/nativescript-platform-css": "^2.0.0",
  "cheerio": "^1.0.0-rc.3",
  "child_process": "^1.0.2",
  "cookie": "^0.3.1",
  "crypto-js": "^3.1.9-1",
  "deepmerge-json": "^1.3.2",
  "delay": "^4.3.0",
  "email-validator": "^2.0.4",
  "html-entities": "^1.2.1",
  "https-proxy-agent": "^3.0.0",
  "hydra-page-previewer": "^0.2.1",
  "jsdom": "^15.1.1",
  "linkifyjs": "^2.1.8",
  "moment": "^2.14.1",
  "moment-timezone": "^0.5.25",
  "nativescript-animated-circle": "^1.2.0",
  "nativescript-background-http": "^4.2.1",
  "nativescript-camera": "^4.5.0",
  "nativescript-cfalert-dialog": "^1.0.15",
  "nativescript-clipboard": "^2.1.1",
  "nativescript-dev-webpack": "^1.5.1",
  "nativescript-drawingpad": "^3.1.0",
  "nativescript-drop-down": "^5.0.4",
  "nativescript-exit": "^1.0.1",
  "nativescript-fancyalert": "^3.0.9",
  "nativescript-geolocation": "^5.1.0",
  "nativescript-google-places-autocomplete": "^1.0.3",
  "nativescript-imagepicker": "^7.1.0",
  "nativescript-iqkeyboardmanager": "^1.5.1",
  "nativescript-local-notifications": "^4.2.0",
  "nativescript-mediafilepicker": "^4.0.2",
  "nativescript-menu": "^1.1.3",
  "nativescript-modal-datetimepicker": "^1.2.2",
  "nativescript-multi-select": "^1.0.6",
  "nativescript-plugin-firebase": "^10.5.2",
  "nativescript-popup": "^1.5.0",
  "nativescript-social-share": "^1.6.0",
  "nativescript-statusbar": "^5.0.0",
  "nativescript-timedatepicker": "^1.2.1",
  "nativescript-toasts": "^1.0.3",
  "nativescript-ui-calendar": "^6.0.0",
  "nativescript-ui-chart": "^7.1.1",
  "nativescript-ui-listview": "^8.0.1",
  "nativescript-ui-sidedrawer": "^8.0.0",
  "nativescript-urlhandler": "^1.3.0",
  "nativescript-videorecorder-x": "^1.0.3-android-x",
  "net": "^1.0.2",
  "node-html-parser": "^1.1.16",
  "node-schedule": "^1.3.2",
  "promise-map-series": "^0.2.3",
  "tls": "0.0.1",
  "tns-core-modules": "^6.5.4"
},
"devDependencies": {
  "babel-traverse": "6.13.0",
  "babel-types": "6.13.0",
  "babylon": "6.9.0",
  "gulp": "^4.0.2",
  "gulp-jshint": "^2.1.0",
  "jshint": "^2.11.0-rc1",
  "lazy": "1.0.11",
  "tns-android": "6.2.0",
  "tns-ios": "6.5.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
