### ISSUE TITLE
text transform capitalize is capitalizing after apostrophe 

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/NativeScript#9940]
### Issue Description

Bug:

![Screenshot_20220617_121728](https://user-images.githubusercontent.com/6006148/174347125-a4a8f515-639d-4009-a16d-83899479e3c4.png)

Fixed:
![Screenshot_20220617_121245](https://user-images.githubusercontent.com/6006148/174346597-f45a034f-6fc2-43bb-9de1-0614f56c8cc0.png)

Line https://github.com/NativeScript/NativeScript/blob/master/packages/core/ui/text-base/index.android.ts#L499 in text-base is the issue. Removed the `'` from the `replace()` and text looks how it should.

### Reproduction

Run android app with 

```xml
   <button
            textTransform="capitalize"
            textWrap="true"
          >
            <FormattedString>
              <span class="text-left" text=" Manage My Physician's Info"></span>
            </FormattedString>
          </button>
```

Will produce `Physician'S` instead of `Physician's`.

### Environment

npx: installed 3 in 1.917s

```yaml
OS: macOS 12.4
CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Shell: /bin/zsh
node: 12.22.12
npm: 6.14.16
nativescript: 8.2.4-alpha.1

# android
java: 15.0.2
ndk: Not Found
apis: 23, 24, 26, 28, 29, 30, 31, 32, 33
build_tools: 25.0.3, 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.1.0, 33.0.0, 33.0.0
system_images: 
  - android-28 | Wear OS Intel x86 Atom
  - android-28 | Google Play Intel x86 Atom
  - android-29 | Google APIs Intel x86 Atom_64
  - android-29 | Google Play Intel x86 Atom
  - android-30 | Wear OS 3 - Preview Intel x86 Atom
  - android-30 | Google APIs Intel x86 Atom
  - android-30 | Google Play Intel x86 Atom
  - android-31 | Google Play Intel x86 Atom_64
  - android-32 | Google Play Intel x86 Atom_64

# ios
xcode: 13.4.1/13F100
cocoapods: 1.11.3
python: 2.7.18
python3: 3.7.2
ruby: 2.7.5
platforms: 
  - DriverKit 21.4
  - iOS 15.5
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~13.2.0",
  "@angular/common": "~13.2.0",
  "@angular/compiler": "~13.2.0",
  "@angular/core": "~13.2.0",
  "@angular/forms": "~13.2.0",
  "@angular/platform-browser": "~13.2.0",
  "@angular/platform-browser-dynamic": "~13.2.0",
  "@angular/router": "~13.2.0",
  "@byram/nativescript-scss": "file:../../xplat/nativescript/scss",
  "@byram/scss": "file:../../libs/scss",
  "@nativescript/angular": "~13.0.0",
  "@nativescript/apple-pay": "~0.1.1",
  "@nativescript/camera": "~5.0.12",
  "@nativescript/core": "~8.2.5",
  "@nativescript/fingerprint-auth": "~8.1.0",
  "@nativescript/firebase-analytics": "~2.1.0",
  "@nativescript/firebase-core": "~2.1.0",
  "@nativescript/firebase-crashlytics": "~2.1.0",
  "@nativescript/firebase-messaging": "~2.1.0",
  "@nativescript/google-pay": "~0.1.2",
  "@nativescript/iqkeyboardmanager": "~2.0.0",
  "@nativescript/secure-storage": "~3.0.0",
  "@nativescript/theme": "~3.0.2",
  "@ngx-translate/core": "~13.0.0",
  "@nstudio/nativescript-checkbox": "~2.0.5",
  "@nstudio/nativescript-exoplayer": "~5.0.9",
  "@nstudio/nativescript-filterable-listpicker": "~3.0.1",
  "@nstudio/nativescript-input-mask": "~0.1.2",
  "@nstudio/nativescript-loading-indicator": "~4.1.2",
  "crypto-js": "~4.1.1",
  "email-validator": "~2.0.4",
  "kinvey-js-sdk": "~6.0.2",
  "kinvey-nativescript-sdk": "file:../patches/kinvey-nativescript-sdk",
  "nativescript-feedback": "~2.0.0",
  "nativescript-ngx-fonticon": "~7.0.0",
  "nativescript-ui-sidedrawer": "~10.0.2",
  "rxjs": "~7.5.0",
  "zone.js": "~0.11.5"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~13.2.0",
  "@angular/compiler-cli": "~13.2.0",
  "@nativescript/android": "~8.2.3",
  "@nativescript/ios": "~8.3.0",
  "@nativescript/types": "~8.2.0",
  "@nativescript/webpack": "~5.0.6",
  "@ngtools/webpack": "~13.2.0",
  "@types/crypto-js": "~4.1.1",
  "crypto-browserify": "~3.12.0",
  "sass": "~1.52.3",
  "sass-loader": "~10.0.0",
  "scss-to-json": "file:../patches/scss-to-json",
  "prompts": "~2.3.2",
  "stream-browserify": "~3.0.0",
  "ts-patch": "~2.0.1",
  "typescript": "~4.5.5",
  "util": "~0.12.4"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
