### ISSUE TITLE
Memory allocation keeps increasing in Nativescript RadListView

### ISSUE THREAD

**Issue by banchasf** [NativeScript/NativeScript#9953]
### Issue Description

When I navigate to the page contains RadListView and navigate out to another page, the allocated memory is not freed from iOS device. Even though the leak is not indicated but the memory allocation keeps increasing when I revisit the RadListView page. It can be observed from the item “VM: TKListViewCellBackgroundView (CALayer)” in the allocation’s category in the attachment.

### Reproduction

Run the code in the repository https://github.com/banchasf/nativescript-radlistview-sample

### Environment

```yaml
OS: macOS 12.4
CPU: (10) arm64 Apple M1 Max
Shell: /bin/zsh
node: 14.19.2
npm: 6.14.17
nativescript: 8.2.3

# android
java: 11.0.15
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 13.3.1/13E500a
cocoapods: 1.11.3
python: 3.9.4
python3: 3.9.4
ruby: 2.7.6
platforms: 
  - DriverKit 21.4
  - iOS 15.4
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~14.0.0",
  "@angular/common": "~14.0.0",
  "@angular/compiler": "~14.0.0",
  "@angular/core": "~14.0.0",
  "@angular/forms": "~14.0.0",
  "@angular/platform-browser": "~14.0.0",
  "@angular/platform-browser-dynamic": "~14.0.0",
  "@angular/router": "~14.0.0",
  "@nativescript/angular": "^14.0.0",
  "@nativescript/core": "~8.2.0",
  "@nativescript/theme": "~3.0.2",
  "nativescript-ui-listview": "10.2.0",
  "rxjs": "~7.5.0",
  "zone.js": "~0.11.5"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~14.0.0",
  "@angular/compiler-cli": "~14.0.0",
  "@nativescript/ios": "8.3.0",
  "@nativescript/types": "~8.2.0",
  "@nativescript/webpack": "~5.0.6",
  "@ngtools/webpack": "~14.0.0",
  "nativescript": "8.2.3",
  "typescript": "~4.7.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
