### ISSUE TITLE
Cannot use publish

### ISSUE THREAD

**Issue by bradrice** [NativeScript/NativeScript#9964]
### Issue Description

when I try to publish using ns publish I get this for ios

Cannot read property 'summaries' of null

### Reproduction

build and publish as usual using the command line.

### Relevant log output (if applicable)

```shell
Cannot read property 'summaries' of null
```

### Environment

```yaml
OS: macOS 12.5
CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
Shell: /bin/zsh
node: 14.17.5
npm: 6.14.14
nativescript: 8.2.3

# android
java: 15.0.2
ndk: Not Found
apis: 26, 27, 28, 29, 30
build_tools: 30.0.2
system_images:
  - android-26 | Google APIs Intel x86 Atom
  - android-27 | Google APIs Intel x86 Atom
  - android-29 | Google Play Intel x86 Atom
  - android-30 | Google APIs Intel x86 Atom

# ios
xcode: 13.4.1/13F100
cocoapods: 1.11.2
python: 3.7.4
python3: 3.7.4
ruby: 2.6.8
platforms:
  - DriverKit 21.4
  - iOS 15.5
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~13.2.0",
  "@angular/common": "~13.2.0",
  "@angular/compiler": "~13.2.0",
  "@angular/core": "~13.2.0",
  "@angular/forms": "~13.2.0",
  "@angular/platform-browser": "~13.2.0",
  "@angular/platform-browser-dynamic": "~13.2.0",
  "@angular/router": "~13.2.0",
  "@nativescript/angular": "^13.0.0",
  "@nativescript/core": "~8.3.0",
  "@nativescript/theme": "~3.0.2",
  "async-await": "^0.1.40",
  "buffer": "^6.0.3",
  "config": "^3.3.6",
  "emitter": "^0.0.5",
  "lodash": "^4.17.21",
  "minimatch": "^5.0.1",
  "moment": "2.24.0",
  "nativescript-audio": "^6.2.1",
  "nativescript-pdf-view": "^3.0.0-1",
  "nativescript-theme-core": "^1.0.4",
  "nativescript-ui-listview": "^10.0.0",
  "nativescript-ui-sidedrawer": "^10.0.1",
  "nativescript-videoplayer": "^5.0.1",
  "nativescript-xml2js": "^0.5.2",
  "reflect-metadata": "~0.1.8",
  "rxjs": "~7.5.0",
  "sass-loader": "^12.1.0",
  "stream": "^0.0.2",
  "stream-browserify": "^3.0.0",
  "timer": "^1.0.1",
  "timers": "^0.1.1",
  "timers-browserify": "^2.0.12",
  "util": "^0.12.4",
  "zone.js": "~0.11.4"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~13.2.0",
  "@angular/compiler-cli": "~13.2.0",
  "@nativescript/android": "8.2.3",
  "@nativescript/ios": "8.3.0",
  "@nativescript/types": "~8.2.0",
  "@nativescript/webpack": "~5.0.6",
  "@ngtools/webpack": "~13.2.0",
  "@types/lodash": "4.14.108",
  "@types/node": "10.0.3",
  "ajv": "^6.12.6",
  "lazy": "1.0.11",
  "sass": "~1.49.9",
  "semver": "^7.3.5",
  "ts-node": "8.3.0",
  "tslint": "5.18.0",
  "typescript": "~4.5.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
