### ISSUE TITLE
core >= 8.3.0: nativeView issues with Stack, Absolute, DockLayout inside ContentView->Frame; Vue

### ISSUE THREAD

**Issue by mBaldasty** [NativeScript/NativeScript#9971]
### Issue Description

When using a ScrollView inside a Page-Element in a component that is wrapped inside ContentView->Frame either without any Layout around it or with any of the layouts mentioned in the title the applications crashes (exact error: Cannot set property 'contentInsetAdjustmentBehavior' of null),

This issue also occured when I had a simple Page with a StackLayout that contained only Buttons. there the error Cannot read property 'hasNonUniformBorder' of null gets thrown and the application crashes. The same happened when using the layouts in the title.

Both issues occur because on the onLayout methods the nativeView is null.

Worth mentioning that Grid, Wrap, Flexbox and RootLayout resolved that issue.

### Reproduction

I wasnt able to reproduce the issue sadly on a fresh project but I am trying to trim my project down as much as I can.

### Environment

```yaml
OS: macOS 12.3.1
CPU: (10) x64 Apple M1 Pro
Shell: /bin/zsh
node: 14.18.3
npm: 6.14.15
nativescript: 8.2.3

# android
java: 15.0.2
ndk: Not Found
apis: 24, 25, 29, 30, 31, 32
build_tools: 30.0.2, 30.0.3
system_images: 
  - android-24 | Google APIs ARM 64 v8a
  - android-25 | Google APIs ARM 64 v8a
  - android-29 | Android TV Intel x86 Atom
  - android-29 | Google APIs ARM 64 v8a
  - android-30 | Google APIs ARM 64 v8a
  - android-31 | Google APIs ARM 64 v8a
  - android-32 | Google APIs ARM 64 v8a

# ios
xcode: 13.4.1/13F100
cocoapods: 1.11.2
python: 2.7.18
python3: 3.8.9
ruby: 2.6.8
platforms: 
  - DriverKit 21.4
  - iOS 15.5
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@klippa/nativescript-http": "3.0.3",
  "@nativescript-community/tween": "0.0.14",
  "@nativescript-community/ui-canvaslabel": "1.1.4",
  "@nativescript-community/ui-collectionview": "4.0.57",
  "@nativescript-community/ui-drawer": "0.1.1",
  "@nativescript-community/ui-image": "4.3.2",
  "@nativescript-community/ui-label": "1.2.9",
  "@nativescript-community/ui-material-ripple": "7.0.25",
  "@nativescript-community/ui-material-tabs": "7.0.25",
  "@nativescript-community/ui-material-textfield": "7.0.25",
  "@nativescript-community/ui-pager": "13.0.40",
  "@nativescript-community/ui-svg": "0.1.0",
  "@nativescript/core": "8.3.1",
  "@nativescript/local-notifications": "6.0.0",
  "@nativescript/theme": "~3.0.1",
  "@nstudio/nativescript-camera-plus": "4.1.0",
  "@nstudio/nativescript-shimmer": "1.0.7",
  "@triniwiz/nativescript-image-zoom": "4.1.3",
  "assert": "2.0.0",
  "axios": "0.21.1",
  "browserify-zlib": "0.2.0",
  "buffer": "^6.0.3",
  "copy-webpack-plugin": "11.0.0",
  "https-browserify": "1.0.0",
  "nativescript-intl": "4.0.2",
  "nativescript-ui-calendar": "8.0.2",
  "nativescript-ui-listview": "10.1.1",
  "nativescript-vue": "2.9.2",
  "os-browserify": "0.3.0",
  "stream-browserify": "3.0.0",
  "stream-http": "^3.2.0",
  "tty-browserify": "0.0.1",
  "url": "0.11.0",
  "util": "0.12.4",
  "vuex": "3.6.2"
},
"devDependencies": {
  "@nativescript/android": "8.2.4",
  "@nativescript/ios": "8.3.2",
  "@nativescript/webpack": "5.0.7",
  "nativescript-vue-template-compiler": "2.9.2",
  "node-sass": "7.0.1",
  "sass": "^1.32.8",
  "sass-loader": "^12.6.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
