### ISSUE TITLE
Debug Mode crashes in VS Code by webpack

### ISSUE THREAD

**Issue by crechberger** [NativeScript/NativeScript#9979]
### Issue Description

When I create a new NS project from scratch with angular and want to debug the code of the sample project, it starts up the app in the simulator, however the debugger in VS Code crashes because of a webpack issue. 

### Reproduction

1. ns create myCoolApp --angular
2. Install VS Code
3. Install the extension NativeScript in VS Code
4. Open the project in VS Code
5. Click on the run and debug Menu
6. Click on "create a launch.json file"
7. Select "NativeScript"
8. Click on "Launch on iOS"
9. Then after starting the app in the simulator and after the debugger crashed you can see the debug output in the bottom menu "Debug Console" and select "Launch on iOS"

### Relevant log output (if applicable)

```shell
Error when trying to require webpack.config.js file from path '/Users/test/Desktop/myCoolApp/webpack.config.js'. Error is: Error: Cannot find module '/package.json'
Require stack:
- /Users/test/Desktop/myCoolApp/node_modules/@nativescript/webpack/dist/helpers/project.js
- /Users/test/Desktop/myCoolApp/node_modules/@nativescript/webpack/dist/helpers/dependencies.js
- /Users/test/Desktop/myCoolApp/node_modules/@nativescript/webpack/dist/helpers/externalConfigs.js
- /Users/test/Desktop/myCoolApp/node_modules/@nativescript/webpack/dist/index.js
- /Users/test/Desktop/myCoolApp/webpack.config.js
- /Users/test/.vscode/extensions/nativescript.nativescript-0.12.3/out/debug-adapter/nativeScriptDebugAdapter.js
- /Users/test/.vscode/extensions/nativescript.nativescript-0.12.3/out/debug-adapter/nativeScriptDebug.js
- /[eval]
```

### Environment

```yaml
OS: macOS 12.4
CPU: (8) arm64 Apple M1
Shell: /bin/zsh
node: 17.8.0
npm: 8.5.5
nativescript: 8.3.1

# android
java: 17.0.2
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 13.3.1/13E500a
cocoapods: 1.10.1
python: 3.9.7
python3: 3.9.7
ruby: 2.6.8
platforms: 
  - DriverKit 21.4
  - iOS 15.4
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~14.1.0",
  "@angular/common": "~14.1.0",
  "@angular/compiler": "~14.1.0",
  "@angular/core": "~14.1.0",
  "@angular/forms": "~14.1.0",
  "@angular/platform-browser": "~14.1.0",
  "@angular/platform-browser-dynamic": "~14.1.0",
  "@angular/router": "~14.1.0",
  "@nativescript/angular": "^14.0.0",
  "@nativescript/core": "~8.2.0",
  "@nativescript/theme": "~3.0.2",
  "rxjs": "~7.5.0",
  "zone.js": "~0.11.5"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~14.1.0",
  "@angular/compiler-cli": "~14.1.0",
  "@nativescript/ios": "8.3.2",
  "@nativescript/types": "~8.2.0",
  "@nativescript/webpack": "~5.0.6",
  "@ngtools/webpack": "~14.1.0",
  "typescript": "~4.7.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
